package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Aq.InternetAgentPrivsId;
import com.abctreinamentos.Aq.InternetAgents;

/**
 * Aq.InternetAgentPrivs generated by hbm2java
 */
public class Aq.InternetAgentPrivs  implements java.io.Serializable {


     private Aq.InternetAgentPrivsId id;
     private Aq.InternetAgents aq$InternetAgents;

    public Aq.InternetAgentPrivs() {
    }

    public Aq.InternetAgentPrivs(Aq.InternetAgentPrivsId id, Aq.InternetAgents aq$InternetAgents) {
       this.id = id;
       this.aq$InternetAgents = aq$InternetAgents;
    }
   
    public Aq.InternetAgentPrivsId getId() {
        return this.id;
    }
    
    public void setId(Aq.InternetAgentPrivsId id) {
        this.id = id;
    }
    public Aq.InternetAgents getAq$InternetAgents() {
        return this.aq$InternetAgents;
    }
    
    public void setAq$InternetAgents(Aq.InternetAgents aq$InternetAgents) {
        this.aq$InternetAgents = aq$InternetAgents;
    }




}


