package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Aq.SchedulesId;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Aq.Schedules generated by hbm2java
 */
public class Aq.Schedules  implements java.io.Serializable {


     private Aq.SchedulesId id;
     private Date startTime;
     private String duration;
     private String nextTime;
     private String latency;
     private Date lastTime;
     private BigDecimal jobno;

    public Aq.Schedules() {
    }

	
    public Aq.Schedules(Aq.SchedulesId id) {
        this.id = id;
    }
    public Aq.Schedules(Aq.SchedulesId id, Date startTime, String duration, String nextTime, String latency, Date lastTime, BigDecimal jobno) {
       this.id = id;
       this.startTime = startTime;
       this.duration = duration;
       this.nextTime = nextTime;
       this.latency = latency;
       this.lastTime = lastTime;
       this.jobno = jobno;
    }
   
    public Aq.SchedulesId getId() {
        return this.id;
    }
    
    public void setId(Aq.SchedulesId id) {
        this.id = id;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public String getDuration() {
        return this.duration;
    }
    
    public void setDuration(String duration) {
        this.duration = duration;
    }
    public String getNextTime() {
        return this.nextTime;
    }
    
    public void setNextTime(String nextTime) {
        this.nextTime = nextTime;
    }
    public String getLatency() {
        return this.latency;
    }
    
    public void setLatency(String latency) {
        this.latency = latency;
    }
    public Date getLastTime() {
        return this.lastTime;
    }
    
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }
    public BigDecimal getJobno() {
        return this.jobno;
    }
    
    public void setJobno(BigDecimal jobno) {
        this.jobno = jobno;
    }




}


