package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrAttribute.Id;
import java.math.BigDecimal;

/**
 * LogmnrAttribute. generated by hbm2java
 */
public class LogmnrAttribute.  implements java.io.Serializable {


     private LogmnrAttribute.Id id;
     private String name;
     private byte[] attrToid;
     private BigDecimal attrVersion#;
     private BigDecimal synobj#;
     private BigDecimal properties;
     private BigDecimal charsetid;
     private BigDecimal charsetform;
     private BigDecimal length;
     private BigDecimal precision#;
     private BigDecimal scale;
     private String externname;
     private BigDecimal xflags;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private BigDecimal spare3;
     private BigDecimal spare4;
     private BigDecimal spare5;
     private BigDecimal setter;
     private BigDecimal getter;
     private BigDecimal logmnrFlags;

    public LogmnrAttribute.() {
    }

	
    public LogmnrAttribute.(LogmnrAttribute.Id id) {
        this.id = id;
    }
    public LogmnrAttribute.(LogmnrAttribute.Id id, String name, byte[] attrToid, BigDecimal attrVersion#, BigDecimal synobj#, BigDecimal properties, BigDecimal charsetid, BigDecimal charsetform, BigDecimal length, BigDecimal precision#, BigDecimal scale, String externname, BigDecimal xflags, BigDecimal spare1, BigDecimal spare2, BigDecimal spare3, BigDecimal spare4, BigDecimal spare5, BigDecimal setter, BigDecimal getter, BigDecimal logmnrFlags) {
       this.id = id;
       this.name = name;
       this.attrToid = attrToid;
       this.attrVersion# = attrVersion#;
       this.synobj# = synobj#;
       this.properties = properties;
       this.charsetid = charsetid;
       this.charsetform = charsetform;
       this.length = length;
       this.precision# = precision#;
       this.scale = scale;
       this.externname = externname;
       this.xflags = xflags;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.spare3 = spare3;
       this.spare4 = spare4;
       this.spare5 = spare5;
       this.setter = setter;
       this.getter = getter;
       this.logmnrFlags = logmnrFlags;
    }
   
    public LogmnrAttribute.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrAttribute.Id id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getAttrToid() {
        return this.attrToid;
    }
    
    public void setAttrToid(byte[] attrToid) {
        this.attrToid = attrToid;
    }
    public BigDecimal getAttrVersion#() {
        return this.attrVersion#;
    }
    
    public void setAttrVersion#(BigDecimal attrVersion#) {
        this.attrVersion# = attrVersion#;
    }
    public BigDecimal getSynobj#() {
        return this.synobj#;
    }
    
    public void setSynobj#(BigDecimal synobj#) {
        this.synobj# = synobj#;
    }
    public BigDecimal getProperties() {
        return this.properties;
    }
    
    public void setProperties(BigDecimal properties) {
        this.properties = properties;
    }
    public BigDecimal getCharsetid() {
        return this.charsetid;
    }
    
    public void setCharsetid(BigDecimal charsetid) {
        this.charsetid = charsetid;
    }
    public BigDecimal getCharsetform() {
        return this.charsetform;
    }
    
    public void setCharsetform(BigDecimal charsetform) {
        this.charsetform = charsetform;
    }
    public BigDecimal getLength() {
        return this.length;
    }
    
    public void setLength(BigDecimal length) {
        this.length = length;
    }
    public BigDecimal getPrecision#() {
        return this.precision#;
    }
    
    public void setPrecision#(BigDecimal precision#) {
        this.precision# = precision#;
    }
    public BigDecimal getScale() {
        return this.scale;
    }
    
    public void setScale(BigDecimal scale) {
        this.scale = scale;
    }
    public String getExternname() {
        return this.externname;
    }
    
    public void setExternname(String externname) {
        this.externname = externname;
    }
    public BigDecimal getXflags() {
        return this.xflags;
    }
    
    public void setXflags(BigDecimal xflags) {
        this.xflags = xflags;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public BigDecimal getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(BigDecimal spare3) {
        this.spare3 = spare3;
    }
    public BigDecimal getSpare4() {
        return this.spare4;
    }
    
    public void setSpare4(BigDecimal spare4) {
        this.spare4 = spare4;
    }
    public BigDecimal getSpare5() {
        return this.spare5;
    }
    
    public void setSpare5(BigDecimal spare5) {
        this.spare5 = spare5;
    }
    public BigDecimal getSetter() {
        return this.setter;
    }
    
    public void setSetter(BigDecimal setter) {
        this.setter = setter;
    }
    public BigDecimal getGetter() {
        return this.getter;
    }
    
    public void setGetter(BigDecimal getter) {
        this.getter = getter;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


