package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LogmnrTabpart.Id generated by hbm2java
 */
public class LogmnrTabpart.Id  implements java.io.Serializable {


     private BigDecimal logmnrUid;
     private BigDecimal obj#;
     private BigDecimal bo#;

    public LogmnrTabpart.Id() {
    }

	
    public LogmnrTabpart.Id(BigDecimal bo#) {
        this.bo# = bo#;
    }
    public LogmnrTabpart.Id(BigDecimal logmnrUid, BigDecimal obj#, BigDecimal bo#) {
       this.logmnrUid = logmnrUid;
       this.obj# = obj#;
       this.bo# = bo#;
    }
   
    public BigDecimal getLogmnrUid() {
        return this.logmnrUid;
    }
    
    public void setLogmnrUid(BigDecimal logmnrUid) {
        this.logmnrUid = logmnrUid;
    }
    public BigDecimal getObj#() {
        return this.obj#;
    }
    
    public void setObj#(BigDecimal obj#) {
        this.obj# = obj#;
    }
    public BigDecimal getBo#() {
        return this.bo#;
    }
    
    public void setBo#(BigDecimal bo#) {
        this.bo# = bo#;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrTabpart.Id) ) return false;
		 LogmnrTabpart.Id castOther = ( LogmnrTabpart.Id ) other; 
         
		 return ( (this.getLogmnrUid()==castOther.getLogmnrUid()) || ( this.getLogmnrUid()!=null && castOther.getLogmnrUid()!=null && this.getLogmnrUid().equals(castOther.getLogmnrUid()) ) )
 && ( (this.getObj#()==castOther.getObj#()) || ( this.getObj#()!=null && castOther.getObj#()!=null && this.getObj#().equals(castOther.getObj#()) ) )
 && ( (this.getBo#()==castOther.getBo#()) || ( this.getBo#()!=null && castOther.getBo#()!=null && this.getBo#().equals(castOther.getBo#()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogmnrUid() == null ? 0 : this.getLogmnrUid().hashCode() );
         result = 37 * result + ( getObj#() == null ? 0 : this.getObj#().hashCode() );
         result = 37 * result + ( getBo#() == null ? 0 : this.getBo#().hashCode() );
         return result;
   }   


}


