package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrLog.Id;
import java.math.BigDecimal;
import java.util.Date;

/**
 * LogmnrLog. generated by hbm2java
 */
public class LogmnrLog.  implements java.io.Serializable {


     private LogmnrLog.Id id;
     private Date timestamp;
     private BigDecimal nextChange#;
     private Date firstTime;
     private Date nextTime;
     private String fileName;
     private BigDecimal status;
     private String info;
     private String dictBegin;
     private String dictEnd;
     private String statusInfo;
     private BigDecimal prevResetlogsChange#;
     private BigDecimal prevResetTimestamp;
     private BigDecimal blocks;
     private BigDecimal blockSize;
     private BigDecimal flags;
     private BigDecimal contents;
     private BigDecimal recid;
     private BigDecimal recstamp;
     private BigDecimal markDeleteTimestamp;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private BigDecimal spare3;
     private BigDecimal spare4;
     private BigDecimal spare5;

    public LogmnrLog.() {
    }

	
    public LogmnrLog.(LogmnrLog.Id id) {
        this.id = id;
    }
    public LogmnrLog.(LogmnrLog.Id id, BigDecimal nextChange#, Date firstTime, Date nextTime, String fileName, BigDecimal status, String info, String dictBegin, String dictEnd, String statusInfo, BigDecimal prevResetlogsChange#, BigDecimal prevResetTimestamp, BigDecimal blocks, BigDecimal blockSize, BigDecimal flags, BigDecimal contents, BigDecimal recid, BigDecimal recstamp, BigDecimal markDeleteTimestamp, BigDecimal spare1, BigDecimal spare2, BigDecimal spare3, BigDecimal spare4, BigDecimal spare5) {
       this.id = id;
       this.nextChange# = nextChange#;
       this.firstTime = firstTime;
       this.nextTime = nextTime;
       this.fileName = fileName;
       this.status = status;
       this.info = info;
       this.dictBegin = dictBegin;
       this.dictEnd = dictEnd;
       this.statusInfo = statusInfo;
       this.prevResetlogsChange# = prevResetlogsChange#;
       this.prevResetTimestamp = prevResetTimestamp;
       this.blocks = blocks;
       this.blockSize = blockSize;
       this.flags = flags;
       this.contents = contents;
       this.recid = recid;
       this.recstamp = recstamp;
       this.markDeleteTimestamp = markDeleteTimestamp;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.spare3 = spare3;
       this.spare4 = spare4;
       this.spare5 = spare5;
    }
   
    public LogmnrLog.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrLog.Id id) {
        this.id = id;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public BigDecimal getNextChange#() {
        return this.nextChange#;
    }
    
    public void setNextChange#(BigDecimal nextChange#) {
        this.nextChange# = nextChange#;
    }
    public Date getFirstTime() {
        return this.firstTime;
    }
    
    public void setFirstTime(Date firstTime) {
        this.firstTime = firstTime;
    }
    public Date getNextTime() {
        return this.nextTime;
    }
    
    public void setNextTime(Date nextTime) {
        this.nextTime = nextTime;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public String getDictBegin() {
        return this.dictBegin;
    }
    
    public void setDictBegin(String dictBegin) {
        this.dictBegin = dictBegin;
    }
    public String getDictEnd() {
        return this.dictEnd;
    }
    
    public void setDictEnd(String dictEnd) {
        this.dictEnd = dictEnd;
    }
    public String getStatusInfo() {
        return this.statusInfo;
    }
    
    public void setStatusInfo(String statusInfo) {
        this.statusInfo = statusInfo;
    }
    public BigDecimal getPrevResetlogsChange#() {
        return this.prevResetlogsChange#;
    }
    
    public void setPrevResetlogsChange#(BigDecimal prevResetlogsChange#) {
        this.prevResetlogsChange# = prevResetlogsChange#;
    }
    public BigDecimal getPrevResetTimestamp() {
        return this.prevResetTimestamp;
    }
    
    public void setPrevResetTimestamp(BigDecimal prevResetTimestamp) {
        this.prevResetTimestamp = prevResetTimestamp;
    }
    public BigDecimal getBlocks() {
        return this.blocks;
    }
    
    public void setBlocks(BigDecimal blocks) {
        this.blocks = blocks;
    }
    public BigDecimal getBlockSize() {
        return this.blockSize;
    }
    
    public void setBlockSize(BigDecimal blockSize) {
        this.blockSize = blockSize;
    }
    public BigDecimal getFlags() {
        return this.flags;
    }
    
    public void setFlags(BigDecimal flags) {
        this.flags = flags;
    }
    public BigDecimal getContents() {
        return this.contents;
    }
    
    public void setContents(BigDecimal contents) {
        this.contents = contents;
    }
    public BigDecimal getRecid() {
        return this.recid;
    }
    
    public void setRecid(BigDecimal recid) {
        this.recid = recid;
    }
    public BigDecimal getRecstamp() {
        return this.recstamp;
    }
    
    public void setRecstamp(BigDecimal recstamp) {
        this.recstamp = recstamp;
    }
    public BigDecimal getMarkDeleteTimestamp() {
        return this.markDeleteTimestamp;
    }
    
    public void setMarkDeleteTimestamp(BigDecimal markDeleteTimestamp) {
        this.markDeleteTimestamp = markDeleteTimestamp;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public BigDecimal getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(BigDecimal spare3) {
        this.spare3 = spare3;
    }
    public BigDecimal getSpare4() {
        return this.spare4;
    }
    
    public void setSpare4(BigDecimal spare4) {
        this.spare4 = spare4;
    }
    public BigDecimal getSpare5() {
        return this.spare5;
    }
    
    public void setSpare5(BigDecimal spare5) {
        this.spare5 = spare5;
    }




}


