package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrGtTabInclude.Id;

/**
 * LogmnrGtTabInclude. generated by hbm2java
 */
public class LogmnrGtTabInclude.  implements java.io.Serializable {


     private LogmnrGtTabInclude.Id id;

    public LogmnrGtTabInclude.() {
    }

    public LogmnrGtTabInclude.(LogmnrGtTabInclude.Id id) {
       this.id = id;
    }
   
    public LogmnrGtTabInclude.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrGtTabInclude.Id id) {
        this.id = id;
    }




}


