package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrGlobal.Id;

/**
 * LogmnrGlobal. generated by hbm2java
 */
public class LogmnrGlobal.  implements java.io.Serializable {


     private LogmnrGlobal.Id id;

    public LogmnrGlobal.() {
    }

    public LogmnrGlobal.(LogmnrGlobal.Id id) {
       this.id = id;
    }
   
    public LogmnrGlobal.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrGlobal.Id id) {
        this.id = id;
    }




}


