package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrNtab.Id;
import java.math.BigDecimal;

/**
 * LogmnrNtab. generated by hbm2java
 */
public class LogmnrNtab.  implements java.io.Serializable {


     private LogmnrNtab.Id id;
     private BigDecimal col#;
     private BigDecimal ntab#;
     private String name;
     private BigDecimal logmnrFlags;

    public LogmnrNtab.() {
    }

	
    public LogmnrNtab.(LogmnrNtab.Id id) {
        this.id = id;
    }
    public LogmnrNtab.(LogmnrNtab.Id id, BigDecimal col#, BigDecimal ntab#, String name, BigDecimal logmnrFlags) {
       this.id = id;
       this.col# = col#;
       this.ntab# = ntab#;
       this.name = name;
       this.logmnrFlags = logmnrFlags;
    }
   
    public LogmnrNtab.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrNtab.Id id) {
        this.id = id;
    }
    public BigDecimal getCol#() {
        return this.col#;
    }
    
    public void setCol#(BigDecimal col#) {
        this.col# = col#;
    }
    public BigDecimal getNtab#() {
        return this.ntab#;
    }
    
    public void setNtab#(BigDecimal ntab#) {
        this.ntab# = ntab#;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


