package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrGtUserInclude.Id;

/**
 * LogmnrGtUserInclude. generated by hbm2java
 */
public class LogmnrGtUserInclude.  implements java.io.Serializable {


     private LogmnrGtUserInclude.Id id;

    public LogmnrGtUserInclude.() {
    }

    public LogmnrGtUserInclude.(LogmnrGtUserInclude.Id id) {
       this.id = id;
    }
   
    public LogmnrGtUserInclude.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrGtUserInclude.Id id) {
        this.id = id;
    }




}


