package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrCol.Id;
import java.math.BigDecimal;

/**
 * LogmnrCol. generated by hbm2java
 */
public class LogmnrCol.  implements java.io.Serializable {


     private LogmnrCol.Id id;
     private BigDecimal col#;
     private BigDecimal segcol#;
     private String name;
     private BigDecimal type#;
     private BigDecimal length;
     private BigDecimal precision#;
     private BigDecimal scale;
     private BigDecimal null$;
     private BigDecimal property;
     private BigDecimal charsetid;
     private BigDecimal charsetform;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private BigDecimal logmnrFlags;
     private BigDecimal collid;
     private BigDecimal collintcol#;
     private BigDecimal acdrrescol#;

    public LogmnrCol.() {
    }

	
    public LogmnrCol.(LogmnrCol.Id id) {
        this.id = id;
    }
    public LogmnrCol.(LogmnrCol.Id id, BigDecimal col#, BigDecimal segcol#, String name, BigDecimal type#, BigDecimal length, BigDecimal precision#, BigDecimal scale, BigDecimal null$, BigDecimal property, BigDecimal charsetid, BigDecimal charsetform, BigDecimal spare1, BigDecimal spare2, BigDecimal logmnrFlags, BigDecimal collid, BigDecimal collintcol#, BigDecimal acdrrescol#) {
       this.id = id;
       this.col# = col#;
       this.segcol# = segcol#;
       this.name = name;
       this.type# = type#;
       this.length = length;
       this.precision# = precision#;
       this.scale = scale;
       this.null$ = null$;
       this.property = property;
       this.charsetid = charsetid;
       this.charsetform = charsetform;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.logmnrFlags = logmnrFlags;
       this.collid = collid;
       this.collintcol# = collintcol#;
       this.acdrrescol# = acdrrescol#;
    }
   
    public LogmnrCol.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrCol.Id id) {
        this.id = id;
    }
    public BigDecimal getCol#() {
        return this.col#;
    }
    
    public void setCol#(BigDecimal col#) {
        this.col# = col#;
    }
    public BigDecimal getSegcol#() {
        return this.segcol#;
    }
    
    public void setSegcol#(BigDecimal segcol#) {
        this.segcol# = segcol#;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getType#() {
        return this.type#;
    }
    
    public void setType#(BigDecimal type#) {
        this.type# = type#;
    }
    public BigDecimal getLength() {
        return this.length;
    }
    
    public void setLength(BigDecimal length) {
        this.length = length;
    }
    public BigDecimal getPrecision#() {
        return this.precision#;
    }
    
    public void setPrecision#(BigDecimal precision#) {
        this.precision# = precision#;
    }
    public BigDecimal getScale() {
        return this.scale;
    }
    
    public void setScale(BigDecimal scale) {
        this.scale = scale;
    }
    public BigDecimal getNull$() {
        return this.null$;
    }
    
    public void setNull$(BigDecimal null$) {
        this.null$ = null$;
    }
    public BigDecimal getProperty() {
        return this.property;
    }
    
    public void setProperty(BigDecimal property) {
        this.property = property;
    }
    public BigDecimal getCharsetid() {
        return this.charsetid;
    }
    
    public void setCharsetid(BigDecimal charsetid) {
        this.charsetid = charsetid;
    }
    public BigDecimal getCharsetform() {
        return this.charsetform;
    }
    
    public void setCharsetform(BigDecimal charsetform) {
        this.charsetform = charsetform;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }
    public BigDecimal getCollid() {
        return this.collid;
    }
    
    public void setCollid(BigDecimal collid) {
        this.collid = collid;
    }
    public BigDecimal getCollintcol#() {
        return this.collintcol#;
    }
    
    public void setCollintcol#(BigDecimal collintcol#) {
        this.collintcol# = collintcol#;
    }
    public BigDecimal getAcdrrescol#() {
        return this.acdrrescol#;
    }
    
    public void setAcdrrescol#(BigDecimal acdrrescol#) {
        this.acdrrescol# = acdrrescol#;
    }




}


