package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LogmnrSessionActions.Id generated by hbm2java
 */
public class LogmnrSessionActions.Id  implements java.io.Serializable {


     private BigDecimal logmnrsession#;
     private String actionname;

    public LogmnrSessionActions.Id() {
    }

    public LogmnrSessionActions.Id(BigDecimal logmnrsession#, String actionname) {
       this.logmnrsession# = logmnrsession#;
       this.actionname = actionname;
    }
   
    public BigDecimal getLogmnrsession#() {
        return this.logmnrsession#;
    }
    
    public void setLogmnrsession#(BigDecimal logmnrsession#) {
        this.logmnrsession# = logmnrsession#;
    }
    public String getActionname() {
        return this.actionname;
    }
    
    public void setActionname(String actionname) {
        this.actionname = actionname;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrSessionActions.Id) ) return false;
		 LogmnrSessionActions.Id castOther = ( LogmnrSessionActions.Id ) other; 
         
		 return ( (this.getLogmnrsession#()==castOther.getLogmnrsession#()) || ( this.getLogmnrsession#()!=null && castOther.getLogmnrsession#()!=null && this.getLogmnrsession#().equals(castOther.getLogmnrsession#()) ) )
 && ( (this.getActionname()==castOther.getActionname()) || ( this.getActionname()!=null && castOther.getActionname()!=null && this.getActionname().equals(castOther.getActionname()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogmnrsession#() == null ? 0 : this.getLogmnrsession#().hashCode() );
         result = 37 * result + ( getActionname() == null ? 0 : this.getActionname().hashCode() );
         return result;
   }   


}


