package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrIndpart.Id;
import java.math.BigDecimal;

/**
 * LogmnrIndpart. generated by hbm2java
 */
public class LogmnrIndpart.  implements java.io.Serializable {


     private LogmnrIndpart.Id id;
     private BigDecimal part#;
     private BigDecimal ts#;
     private BigDecimal logmnrFlags;

    public LogmnrIndpart.() {
    }

	
    public LogmnrIndpart.(LogmnrIndpart.Id id, BigDecimal ts#) {
        this.id = id;
        this.ts# = ts#;
    }
    public LogmnrIndpart.(LogmnrIndpart.Id id, BigDecimal part#, BigDecimal ts#, BigDecimal logmnrFlags) {
       this.id = id;
       this.part# = part#;
       this.ts# = ts#;
       this.logmnrFlags = logmnrFlags;
    }
   
    public LogmnrIndpart.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrIndpart.Id id) {
        this.id = id;
    }
    public BigDecimal getPart#() {
        return this.part#;
    }
    
    public void setPart#(BigDecimal part#) {
        this.part# = part#;
    }
    public BigDecimal getTs#() {
        return this.ts#;
    }
    
    public void setTs#(BigDecimal ts#) {
        this.ts# = ts#;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


