package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrTabcompart.Id;
import java.math.BigDecimal;

/**
 * LogmnrTabcompart. generated by hbm2java
 */
public class LogmnrTabcompart.  implements java.io.Serializable {


     private LogmnrTabcompart.Id id;
     private BigDecimal bo#;
     private BigDecimal part#;
     private BigDecimal logmnrFlags;

    public LogmnrTabcompart.() {
    }

	
    public LogmnrTabcompart.(LogmnrTabcompart.Id id, BigDecimal part#) {
        this.id = id;
        this.part# = part#;
    }
    public LogmnrTabcompart.(LogmnrTabcompart.Id id, BigDecimal bo#, BigDecimal part#, BigDecimal logmnrFlags) {
       this.id = id;
       this.bo# = bo#;
       this.part# = part#;
       this.logmnrFlags = logmnrFlags;
    }
   
    public LogmnrTabcompart.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrTabcompart.Id id) {
        this.id = id;
    }
    public BigDecimal getBo#() {
        return this.bo#;
    }
    
    public void setBo#(BigDecimal bo#) {
        this.bo# = bo#;
    }
    public BigDecimal getPart#() {
        return this.part#;
    }
    
    public void setPart#(BigDecimal part#) {
        this.part# = part#;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


