package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrError.Id;

/**
 * LogmnrError. generated by hbm2java
 */
public class LogmnrError.  implements java.io.Serializable {


     private LogmnrError.Id id;

    public LogmnrError.() {
    }

    public LogmnrError.(LogmnrError.Id id) {
       this.id = id;
    }
   
    public LogmnrError.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrError.Id id) {
        this.id = id;
    }




}


