package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrKopm.Id;
import java.math.BigDecimal;

/**
 * LogmnrKopm. generated by hbm2java
 */
public class LogmnrKopm.  implements java.io.Serializable {


     private LogmnrKopm.Id id;
     private BigDecimal length;
     private byte[] metadata;
     private BigDecimal logmnrFlags;

    public LogmnrKopm.() {
    }

	
    public LogmnrKopm.(LogmnrKopm.Id id) {
        this.id = id;
    }
    public LogmnrKopm.(LogmnrKopm.Id id, BigDecimal length, byte[] metadata, BigDecimal logmnrFlags) {
       this.id = id;
       this.length = length;
       this.metadata = metadata;
       this.logmnrFlags = logmnrFlags;
    }
   
    public LogmnrKopm.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrKopm.Id id) {
        this.id = id;
    }
    public BigDecimal getLength() {
        return this.length;
    }
    
    public void setLength(BigDecimal length) {
        this.length = length;
    }
    public byte[] getMetadata() {
        return this.metadata;
    }
    
    public void setMetadata(byte[] metadata) {
        this.metadata = metadata;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


