package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * LogmnrcTsId generated by hbm2java
 */
public class LogmnrcTsId implements java.io.Serializable {

	private BigDecimal logmnrUid;
	private BigDecimal ts#;
	private BigDecimal startScn;

	public LogmnrcTsId() {
	}

	public LogmnrcTsId(BigDecimal logmnrUid, BigDecimal ts#, BigDecimal startScn) {
       this.logmnrUid = logmnrUid;
       this.ts# = ts#;
       this.startScn = startScn;
    }

	public BigDecimal getLogmnrUid() {
		return this.logmnrUid;
	}

	public void setLogmnrUid(BigDecimal logmnrUid) {
		this.logmnrUid = logmnrUid;
	}

	public BigDecimal getTs#()
	{
        return this.ts#;
    }

	public void setTs#(
	BigDecimal ts#)
	{
        this.ts# = ts#;
    }

	public BigDecimal getStartScn() {
		return this.startScn;
	}

	public void setStartScn(BigDecimal startScn) {
		this.startScn = startScn;
	}

	public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrcTsId) ) return false;
		 LogmnrcTsId castOther = ( LogmnrcTsId ) other; 
         
		 return ( (this.getLogmnrUid()==castOther.getLogmnrUid()) || ( this.getLogmnrUid()!=null && castOther.getLogmnrUid()!=null && this.getLogmnrUid().equals(castOther.getLogmnrUid()) ) )
 && ( (this.getTs#()==castOther.getTs#()) || ( this.getTs#()!=null && castOther.getTs#()!=null && this.getTs#().equals(castOther.getTs#()) ) )
 && ( (this.getStartScn()==castOther.getStartScn()) || ( this.getStartScn()!=null && castOther.getStartScn()!=null && this.getStartScn().equals(castOther.getStartScn()) ) );
   }

	public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogmnrUid() == null ? 0 : this.getLogmnrUid().hashCode() );
         result = 37 * result + ( getTs#() == null ? 0 : this.getTs#().hashCode() );
         result = 37 * result + ( getStartScn() == null ? 0 : this.getStartScn().hashCode() );
         return result;
   }

}
