package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrIcol.Id;
import java.math.BigDecimal;

/**
 * LogmnrIcol. generated by hbm2java
 */
public class LogmnrIcol.  implements java.io.Serializable {


     private LogmnrIcol.Id id;
     private BigDecimal bo#;
     private BigDecimal col#;
     private BigDecimal pos#;
     private BigDecimal segcol#;
     private BigDecimal logmnrFlags;

    public LogmnrIcol.() {
    }

	
    public LogmnrIcol.(LogmnrIcol.Id id) {
        this.id = id;
    }
    public LogmnrIcol.(LogmnrIcol.Id id, BigDecimal bo#, BigDecimal col#, BigDecimal pos#, BigDecimal segcol#, BigDecimal logmnrFlags) {
       this.id = id;
       this.bo# = bo#;
       this.col# = col#;
       this.pos# = pos#;
       this.segcol# = segcol#;
       this.logmnrFlags = logmnrFlags;
    }
   
    public LogmnrIcol.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrIcol.Id id) {
        this.id = id;
    }
    public BigDecimal getBo#() {
        return this.bo#;
    }
    
    public void setBo#(BigDecimal bo#) {
        this.bo# = bo#;
    }
    public BigDecimal getCol#() {
        return this.col#;
    }
    
    public void setCol#(BigDecimal col#) {
        this.col# = col#;
    }
    public BigDecimal getPos#() {
        return this.pos#;
    }
    
    public void setPos#(BigDecimal pos#) {
        this.pos# = pos#;
    }
    public BigDecimal getSegcol#() {
        return this.segcol#;
    }
    
    public void setSegcol#(BigDecimal segcol#) {
        this.segcol# = segcol#;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


