package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrObj.Id;
import java.math.BigDecimal;
import java.util.Date;

/**
 * LogmnrObj. generated by hbm2java
 */
public class LogmnrObj.  implements java.io.Serializable {


     private LogmnrObj.Id id;
     private BigDecimal objv#;
     private BigDecimal owner#;
     private String name;
     private BigDecimal namespace;
     private String subname;
     private BigDecimal type#;
     private byte[] oid$;
     private String remoteowner;
     private String linkname;
     private BigDecimal flags;
     private BigDecimal spare3;
     private Date stime;
     private BigDecimal logmnrFlags;
     private BigDecimal startScnbas;
     private BigDecimal startScnwrp;

    public LogmnrObj.() {
    }

	
    public LogmnrObj.(LogmnrObj.Id id) {
        this.id = id;
    }
    public LogmnrObj.(LogmnrObj.Id id, BigDecimal objv#, BigDecimal owner#, String name, BigDecimal namespace, String subname, BigDecimal type#, byte[] oid$, String remoteowner, String linkname, BigDecimal flags, BigDecimal spare3, Date stime, BigDecimal logmnrFlags, BigDecimal startScnbas, BigDecimal startScnwrp) {
       this.id = id;
       this.objv# = objv#;
       this.owner# = owner#;
       this.name = name;
       this.namespace = namespace;
       this.subname = subname;
       this.type# = type#;
       this.oid$ = oid$;
       this.remoteowner = remoteowner;
       this.linkname = linkname;
       this.flags = flags;
       this.spare3 = spare3;
       this.stime = stime;
       this.logmnrFlags = logmnrFlags;
       this.startScnbas = startScnbas;
       this.startScnwrp = startScnwrp;
    }
   
    public LogmnrObj.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrObj.Id id) {
        this.id = id;
    }
    public BigDecimal getObjv#() {
        return this.objv#;
    }
    
    public void setObjv#(BigDecimal objv#) {
        this.objv# = objv#;
    }
    public BigDecimal getOwner#() {
        return this.owner#;
    }
    
    public void setOwner#(BigDecimal owner#) {
        this.owner# = owner#;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getNamespace() {
        return this.namespace;
    }
    
    public void setNamespace(BigDecimal namespace) {
        this.namespace = namespace;
    }
    public String getSubname() {
        return this.subname;
    }
    
    public void setSubname(String subname) {
        this.subname = subname;
    }
    public BigDecimal getType#() {
        return this.type#;
    }
    
    public void setType#(BigDecimal type#) {
        this.type# = type#;
    }
    public byte[] getOid$() {
        return this.oid$;
    }
    
    public void setOid$(byte[] oid$) {
        this.oid$ = oid$;
    }
    public String getRemoteowner() {
        return this.remoteowner;
    }
    
    public void setRemoteowner(String remoteowner) {
        this.remoteowner = remoteowner;
    }
    public String getLinkname() {
        return this.linkname;
    }
    
    public void setLinkname(String linkname) {
        this.linkname = linkname;
    }
    public BigDecimal getFlags() {
        return this.flags;
    }
    
    public void setFlags(BigDecimal flags) {
        this.flags = flags;
    }
    public BigDecimal getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(BigDecimal spare3) {
        this.spare3 = spare3;
    }
    public Date getStime() {
        return this.stime;
    }
    
    public void setStime(Date stime) {
        this.stime = stime;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }
    public BigDecimal getStartScnbas() {
        return this.startScnbas;
    }
    
    public void setStartScnbas(BigDecimal startScnbas) {
        this.startScnbas = startScnbas;
    }
    public BigDecimal getStartScnwrp() {
        return this.startScnwrp;
    }
    
    public void setStartScnwrp(BigDecimal startScnwrp) {
        this.startScnwrp = startScnwrp;
    }




}


