package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrPartobj.Id;
import java.math.BigDecimal;

/**
 * LogmnrPartobj. generated by hbm2java
 */
public class LogmnrPartobj.  implements java.io.Serializable {


     private LogmnrPartobj.Id id;
     private BigDecimal parttype;
     private BigDecimal partcnt;
     private BigDecimal partkeycols;
     private BigDecimal flags;
     private BigDecimal defts#;
     private BigDecimal defpctfree;
     private BigDecimal defpctused;
     private BigDecimal defpctthres;
     private BigDecimal definitrans;
     private BigDecimal defmaxtrans;
     private BigDecimal deftiniexts;
     private BigDecimal defextsize;
     private BigDecimal defminexts;
     private BigDecimal defmaxexts;
     private BigDecimal defextpct;
     private BigDecimal deflists;
     private BigDecimal defgroups;
     private BigDecimal deflogging;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private BigDecimal spare3;
     private BigDecimal definclcol;
     private String parameters;
     private BigDecimal logmnrFlags;

    public LogmnrPartobj.() {
    }

	
    public LogmnrPartobj.(LogmnrPartobj.Id id) {
        this.id = id;
    }
    public LogmnrPartobj.(LogmnrPartobj.Id id, BigDecimal parttype, BigDecimal partcnt, BigDecimal partkeycols, BigDecimal flags, BigDecimal defts#, BigDecimal defpctfree, BigDecimal defpctused, BigDecimal defpctthres, BigDecimal definitrans, BigDecimal defmaxtrans, BigDecimal deftiniexts, BigDecimal defextsize, BigDecimal defminexts, BigDecimal defmaxexts, BigDecimal defextpct, BigDecimal deflists, BigDecimal defgroups, BigDecimal deflogging, BigDecimal spare1, BigDecimal spare2, BigDecimal spare3, BigDecimal definclcol, String parameters, BigDecimal logmnrFlags) {
       this.id = id;
       this.parttype = parttype;
       this.partcnt = partcnt;
       this.partkeycols = partkeycols;
       this.flags = flags;
       this.defts# = defts#;
       this.defpctfree = defpctfree;
       this.defpctused = defpctused;
       this.defpctthres = defpctthres;
       this.definitrans = definitrans;
       this.defmaxtrans = defmaxtrans;
       this.deftiniexts = deftiniexts;
       this.defextsize = defextsize;
       this.defminexts = defminexts;
       this.defmaxexts = defmaxexts;
       this.defextpct = defextpct;
       this.deflists = deflists;
       this.defgroups = defgroups;
       this.deflogging = deflogging;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.spare3 = spare3;
       this.definclcol = definclcol;
       this.parameters = parameters;
       this.logmnrFlags = logmnrFlags;
    }
   
    public LogmnrPartobj.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrPartobj.Id id) {
        this.id = id;
    }
    public BigDecimal getParttype() {
        return this.parttype;
    }
    
    public void setParttype(BigDecimal parttype) {
        this.parttype = parttype;
    }
    public BigDecimal getPartcnt() {
        return this.partcnt;
    }
    
    public void setPartcnt(BigDecimal partcnt) {
        this.partcnt = partcnt;
    }
    public BigDecimal getPartkeycols() {
        return this.partkeycols;
    }
    
    public void setPartkeycols(BigDecimal partkeycols) {
        this.partkeycols = partkeycols;
    }
    public BigDecimal getFlags() {
        return this.flags;
    }
    
    public void setFlags(BigDecimal flags) {
        this.flags = flags;
    }
    public BigDecimal getDefts#() {
        return this.defts#;
    }
    
    public void setDefts#(BigDecimal defts#) {
        this.defts# = defts#;
    }
    public BigDecimal getDefpctfree() {
        return this.defpctfree;
    }
    
    public void setDefpctfree(BigDecimal defpctfree) {
        this.defpctfree = defpctfree;
    }
    public BigDecimal getDefpctused() {
        return this.defpctused;
    }
    
    public void setDefpctused(BigDecimal defpctused) {
        this.defpctused = defpctused;
    }
    public BigDecimal getDefpctthres() {
        return this.defpctthres;
    }
    
    public void setDefpctthres(BigDecimal defpctthres) {
        this.defpctthres = defpctthres;
    }
    public BigDecimal getDefinitrans() {
        return this.definitrans;
    }
    
    public void setDefinitrans(BigDecimal definitrans) {
        this.definitrans = definitrans;
    }
    public BigDecimal getDefmaxtrans() {
        return this.defmaxtrans;
    }
    
    public void setDefmaxtrans(BigDecimal defmaxtrans) {
        this.defmaxtrans = defmaxtrans;
    }
    public BigDecimal getDeftiniexts() {
        return this.deftiniexts;
    }
    
    public void setDeftiniexts(BigDecimal deftiniexts) {
        this.deftiniexts = deftiniexts;
    }
    public BigDecimal getDefextsize() {
        return this.defextsize;
    }
    
    public void setDefextsize(BigDecimal defextsize) {
        this.defextsize = defextsize;
    }
    public BigDecimal getDefminexts() {
        return this.defminexts;
    }
    
    public void setDefminexts(BigDecimal defminexts) {
        this.defminexts = defminexts;
    }
    public BigDecimal getDefmaxexts() {
        return this.defmaxexts;
    }
    
    public void setDefmaxexts(BigDecimal defmaxexts) {
        this.defmaxexts = defmaxexts;
    }
    public BigDecimal getDefextpct() {
        return this.defextpct;
    }
    
    public void setDefextpct(BigDecimal defextpct) {
        this.defextpct = defextpct;
    }
    public BigDecimal getDeflists() {
        return this.deflists;
    }
    
    public void setDeflists(BigDecimal deflists) {
        this.deflists = deflists;
    }
    public BigDecimal getDefgroups() {
        return this.defgroups;
    }
    
    public void setDefgroups(BigDecimal defgroups) {
        this.defgroups = defgroups;
    }
    public BigDecimal getDeflogging() {
        return this.deflogging;
    }
    
    public void setDeflogging(BigDecimal deflogging) {
        this.deflogging = deflogging;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public BigDecimal getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(BigDecimal spare3) {
        this.spare3 = spare3;
    }
    public BigDecimal getDefinclcol() {
        return this.definclcol;
    }
    
    public void setDefinclcol(BigDecimal definclcol) {
        this.definclcol = definclcol;
    }
    public String getParameters() {
        return this.parameters;
    }
    
    public void setParameters(String parameters) {
        this.parameters = parameters;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


