package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * LogmnrShardTs generated by hbm2java
 */
public class LogmnrShardTs implements java.io.Serializable {

	private LogmnrShardTsId id;
	private BigDecimal chunkNumber;
	private BigDecimal startScnbas;
	private BigDecimal startScnwrp;

	public LogmnrShardTs() {
	}

	public LogmnrShardTs(LogmnrShardTsId id, BigDecimal chunkNumber) {
		this.id = id;
		this.chunkNumber = chunkNumber;
	}

	public LogmnrShardTs(LogmnrShardTsId id, BigDecimal chunkNumber, BigDecimal startScnbas, BigDecimal startScnwrp) {
		this.id = id;
		this.chunkNumber = chunkNumber;
		this.startScnbas = startScnbas;
		this.startScnwrp = startScnwrp;
	}

	public LogmnrShardTsId getId() {
		return this.id;
	}

	public void setId(LogmnrShardTsId id) {
		this.id = id;
	}

	public BigDecimal getChunkNumber() {
		return this.chunkNumber;
	}

	public void setChunkNumber(BigDecimal chunkNumber) {
		this.chunkNumber = chunkNumber;
	}

	public BigDecimal getStartScnbas() {
		return this.startScnbas;
	}

	public void setStartScnbas(BigDecimal startScnbas) {
		this.startScnbas = startScnbas;
	}

	public BigDecimal getStartScnwrp() {
		return this.startScnwrp;
	}

	public void setStartScnwrp(BigDecimal startScnwrp) {
		this.startScnwrp = startScnwrp;
	}

}
