package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LogmnrCon.Id generated by hbm2java
 */
public class LogmnrCon.Id  implements java.io.Serializable {


     private BigDecimal logmnrUid;
     private BigDecimal con#;

    public LogmnrCon.Id() {
    }

	
    public LogmnrCon.Id(BigDecimal con#) {
        this.con# = con#;
    }
    public LogmnrCon.Id(BigDecimal logmnrUid, BigDecimal con#) {
       this.logmnrUid = logmnrUid;
       this.con# = con#;
    }
   
    public BigDecimal getLogmnrUid() {
        return this.logmnrUid;
    }
    
    public void setLogmnrUid(BigDecimal logmnrUid) {
        this.logmnrUid = logmnrUid;
    }
    public BigDecimal getCon#() {
        return this.con#;
    }
    
    public void setCon#(BigDecimal con#) {
        this.con# = con#;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrCon.Id) ) return false;
		 LogmnrCon.Id castOther = ( LogmnrCon.Id ) other; 
         
		 return ( (this.getLogmnrUid()==castOther.getLogmnrUid()) || ( this.getLogmnrUid()!=null && castOther.getLogmnrUid()!=null && this.getLogmnrUid().equals(castOther.getLogmnrUid()) ) )
 && ( (this.getCon#()==castOther.getCon#()) || ( this.getCon#()!=null && castOther.getCon#()!=null && this.getCon#().equals(castOther.getCon#()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogmnrUid() == null ? 0 : this.getLogmnrUid().hashCode() );
         result = 37 * result + ( getCon#() == null ? 0 : this.getCon#().hashCode() );
         return result;
   }   


}


