package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrCcol.Id;
import java.math.BigDecimal;

/**
 * LogmnrCcol. generated by hbm2java
 */
public class LogmnrCcol.  implements java.io.Serializable {


     private LogmnrCcol.Id id;
     private BigDecimal obj#;
     private BigDecimal col#;
     private BigDecimal pos#;
     private BigDecimal logmnrFlags;

    public LogmnrCcol.() {
    }

	
    public LogmnrCcol.(LogmnrCcol.Id id) {
        this.id = id;
    }
    public LogmnrCcol.(LogmnrCcol.Id id, BigDecimal obj#, BigDecimal col#, BigDecimal pos#, BigDecimal logmnrFlags) {
       this.id = id;
       this.obj# = obj#;
       this.col# = col#;
       this.pos# = pos#;
       this.logmnrFlags = logmnrFlags;
    }
   
    public LogmnrCcol.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrCcol.Id id) {
        this.id = id;
    }
    public BigDecimal getObj#() {
        return this.obj#;
    }
    
    public void setObj#(BigDecimal obj#) {
        this.obj# = obj#;
    }
    public BigDecimal getCol#() {
        return this.col#;
    }
    
    public void setCol#(BigDecimal col#) {
        this.col# = col#;
    }
    public BigDecimal getPos#() {
        return this.pos#;
    }
    
    public void setPos#(BigDecimal pos#) {
        this.pos# = pos#;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


