package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrOpqtype.Id;
import java.math.BigDecimal;

/**
 * LogmnrOpqtype. generated by hbm2java
 */
public class LogmnrOpqtype.  implements java.io.Serializable {


     private LogmnrOpqtype.Id id;
     private BigDecimal type;
     private BigDecimal flags;
     private BigDecimal lobcol;
     private BigDecimal objcol;
     private BigDecimal extracol;
     private byte[] schemaoid;
     private BigDecimal elemnum;
     private String schemaurl;
     private BigDecimal logmnrFlags;

    public LogmnrOpqtype.() {
    }

	
    public LogmnrOpqtype.(LogmnrOpqtype.Id id) {
        this.id = id;
    }
    public LogmnrOpqtype.(LogmnrOpqtype.Id id, BigDecimal type, BigDecimal flags, BigDecimal lobcol, BigDecimal objcol, BigDecimal extracol, byte[] schemaoid, BigDecimal elemnum, String schemaurl, BigDecimal logmnrFlags) {
       this.id = id;
       this.type = type;
       this.flags = flags;
       this.lobcol = lobcol;
       this.objcol = objcol;
       this.extracol = extracol;
       this.schemaoid = schemaoid;
       this.elemnum = elemnum;
       this.schemaurl = schemaurl;
       this.logmnrFlags = logmnrFlags;
    }
   
    public LogmnrOpqtype.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrOpqtype.Id id) {
        this.id = id;
    }
    public BigDecimal getType() {
        return this.type;
    }
    
    public void setType(BigDecimal type) {
        this.type = type;
    }
    public BigDecimal getFlags() {
        return this.flags;
    }
    
    public void setFlags(BigDecimal flags) {
        this.flags = flags;
    }
    public BigDecimal getLobcol() {
        return this.lobcol;
    }
    
    public void setLobcol(BigDecimal lobcol) {
        this.lobcol = lobcol;
    }
    public BigDecimal getObjcol() {
        return this.objcol;
    }
    
    public void setObjcol(BigDecimal objcol) {
        this.objcol = objcol;
    }
    public BigDecimal getExtracol() {
        return this.extracol;
    }
    
    public void setExtracol(BigDecimal extracol) {
        this.extracol = extracol;
    }
    public byte[] getSchemaoid() {
        return this.schemaoid;
    }
    
    public void setSchemaoid(byte[] schemaoid) {
        this.schemaoid = schemaoid;
    }
    public BigDecimal getElemnum() {
        return this.elemnum;
    }
    
    public void setElemnum(BigDecimal elemnum) {
        this.elemnum = elemnum;
    }
    public String getSchemaurl() {
        return this.schemaurl;
    }
    
    public void setSchemaurl(String schemaurl) {
        this.schemaurl = schemaurl;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


