package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * LogmnrSession. generated by hbm2java
 */
public class LogmnrSession.  implements java.io.Serializable {


     private BigDecimal session#;
     private String version;
     private BigDecimal client#;
     private String sessionName;
     private BigDecimal dbId;
     private BigDecimal resetlogsChange#;
     private BigDecimal sessionAttr;
     private String sessionAttrVerbose;
     private BigDecimal startScn;
     private BigDecimal endScn;
     private BigDecimal spillScn;
     private Date spillTime;
     private BigDecimal oldestScn;
     private BigDecimal resumeScn;
     private String globalDbName;
     private BigDecimal resetTimestamp;
     private BigDecimal branchScn;
     private String redoCompat;
     private BigDecimal spare1;
     private BigDecimal purgeScn;
     private BigDecimal spare3;
     private BigDecimal spare4;
     private BigDecimal spare5;
     private Date spare6;
     private String spare7;
     private String spare8;
     private BigDecimal spare9;

    public LogmnrSession.() {
    }

	
    public LogmnrSession.(BigDecimal session#, String sessionName) {
        this.session# = session#;
        this.sessionName = sessionName;
    }
    public LogmnrSession.(BigDecimal session#, BigDecimal client#, String sessionName, BigDecimal dbId, BigDecimal resetlogsChange#, BigDecimal sessionAttr, String sessionAttrVerbose, BigDecimal startScn, BigDecimal endScn, BigDecimal spillScn, Date spillTime, BigDecimal oldestScn, BigDecimal resumeScn, String globalDbName, BigDecimal resetTimestamp, BigDecimal branchScn, String redoCompat, BigDecimal spare1, BigDecimal purgeScn, BigDecimal spare3, BigDecimal spare4, BigDecimal spare5, Date spare6, String spare7, String spare8, BigDecimal spare9) {
       this.session# = session#;
       this.client# = client#;
       this.sessionName = sessionName;
       this.dbId = dbId;
       this.resetlogsChange# = resetlogsChange#;
       this.sessionAttr = sessionAttr;
       this.sessionAttrVerbose = sessionAttrVerbose;
       this.startScn = startScn;
       this.endScn = endScn;
       this.spillScn = spillScn;
       this.spillTime = spillTime;
       this.oldestScn = oldestScn;
       this.resumeScn = resumeScn;
       this.globalDbName = globalDbName;
       this.resetTimestamp = resetTimestamp;
       this.branchScn = branchScn;
       this.redoCompat = redoCompat;
       this.spare1 = spare1;
       this.purgeScn = purgeScn;
       this.spare3 = spare3;
       this.spare4 = spare4;
       this.spare5 = spare5;
       this.spare6 = spare6;
       this.spare7 = spare7;
       this.spare8 = spare8;
       this.spare9 = spare9;
    }
   
    public BigDecimal getSession#() {
        return this.session#;
    }
    
    public void setSession#(BigDecimal session#) {
        this.session# = session#;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public BigDecimal getClient#() {
        return this.client#;
    }
    
    public void setClient#(BigDecimal client#) {
        this.client# = client#;
    }
    public String getSessionName() {
        return this.sessionName;
    }
    
    public void setSessionName(String sessionName) {
        this.sessionName = sessionName;
    }
    public BigDecimal getDbId() {
        return this.dbId;
    }
    
    public void setDbId(BigDecimal dbId) {
        this.dbId = dbId;
    }
    public BigDecimal getResetlogsChange#() {
        return this.resetlogsChange#;
    }
    
    public void setResetlogsChange#(BigDecimal resetlogsChange#) {
        this.resetlogsChange# = resetlogsChange#;
    }
    public BigDecimal getSessionAttr() {
        return this.sessionAttr;
    }
    
    public void setSessionAttr(BigDecimal sessionAttr) {
        this.sessionAttr = sessionAttr;
    }
    public String getSessionAttrVerbose() {
        return this.sessionAttrVerbose;
    }
    
    public void setSessionAttrVerbose(String sessionAttrVerbose) {
        this.sessionAttrVerbose = sessionAttrVerbose;
    }
    public BigDecimal getStartScn() {
        return this.startScn;
    }
    
    public void setStartScn(BigDecimal startScn) {
        this.startScn = startScn;
    }
    public BigDecimal getEndScn() {
        return this.endScn;
    }
    
    public void setEndScn(BigDecimal endScn) {
        this.endScn = endScn;
    }
    public BigDecimal getSpillScn() {
        return this.spillScn;
    }
    
    public void setSpillScn(BigDecimal spillScn) {
        this.spillScn = spillScn;
    }
    public Date getSpillTime() {
        return this.spillTime;
    }
    
    public void setSpillTime(Date spillTime) {
        this.spillTime = spillTime;
    }
    public BigDecimal getOldestScn() {
        return this.oldestScn;
    }
    
    public void setOldestScn(BigDecimal oldestScn) {
        this.oldestScn = oldestScn;
    }
    public BigDecimal getResumeScn() {
        return this.resumeScn;
    }
    
    public void setResumeScn(BigDecimal resumeScn) {
        this.resumeScn = resumeScn;
    }
    public String getGlobalDbName() {
        return this.globalDbName;
    }
    
    public void setGlobalDbName(String globalDbName) {
        this.globalDbName = globalDbName;
    }
    public BigDecimal getResetTimestamp() {
        return this.resetTimestamp;
    }
    
    public void setResetTimestamp(BigDecimal resetTimestamp) {
        this.resetTimestamp = resetTimestamp;
    }
    public BigDecimal getBranchScn() {
        return this.branchScn;
    }
    
    public void setBranchScn(BigDecimal branchScn) {
        this.branchScn = branchScn;
    }
    public String getRedoCompat() {
        return this.redoCompat;
    }
    
    public void setRedoCompat(String redoCompat) {
        this.redoCompat = redoCompat;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getPurgeScn() {
        return this.purgeScn;
    }
    
    public void setPurgeScn(BigDecimal purgeScn) {
        this.purgeScn = purgeScn;
    }
    public BigDecimal getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(BigDecimal spare3) {
        this.spare3 = spare3;
    }
    public BigDecimal getSpare4() {
        return this.spare4;
    }
    
    public void setSpare4(BigDecimal spare4) {
        this.spare4 = spare4;
    }
    public BigDecimal getSpare5() {
        return this.spare5;
    }
    
    public void setSpare5(BigDecimal spare5) {
        this.spare5 = spare5;
    }
    public Date getSpare6() {
        return this.spare6;
    }
    
    public void setSpare6(Date spare6) {
        this.spare6 = spare6;
    }
    public String getSpare7() {
        return this.spare7;
    }
    
    public void setSpare7(String spare7) {
        this.spare7 = spare7;
    }
    public String getSpare8() {
        return this.spare8;
    }
    
    public void setSpare8(String spare8) {
        this.spare8 = spare8;
    }
    public BigDecimal getSpare9() {
        return this.spare9;
    }
    
    public void setSpare9(BigDecimal spare9) {
        this.spare9 = spare9;
    }




}


