package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LogmnrUser.Id generated by hbm2java
 */
public class LogmnrUser.Id  implements java.io.Serializable {


     private BigDecimal logmnrUid;
     private BigDecimal user#;

    public LogmnrUser.Id() {
    }

    public LogmnrUser.Id(BigDecimal logmnrUid, BigDecimal user#) {
       this.logmnrUid = logmnrUid;
       this.user# = user#;
    }
   
    public BigDecimal getLogmnrUid() {
        return this.logmnrUid;
    }
    
    public void setLogmnrUid(BigDecimal logmnrUid) {
        this.logmnrUid = logmnrUid;
    }
    public BigDecimal getUser#() {
        return this.user#;
    }
    
    public void setUser#(BigDecimal user#) {
        this.user# = user#;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrUser.Id) ) return false;
		 LogmnrUser.Id castOther = ( LogmnrUser.Id ) other; 
         
		 return ( (this.getLogmnrUid()==castOther.getLogmnrUid()) || ( this.getLogmnrUid()!=null && castOther.getLogmnrUid()!=null && this.getLogmnrUid().equals(castOther.getLogmnrUid()) ) )
 && ( (this.getUser#()==castOther.getUser#()) || ( this.getUser#()!=null && castOther.getUser#()!=null && this.getUser#().equals(castOther.getUser#()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogmnrUid() == null ? 0 : this.getLogmnrUid().hashCode() );
         result = 37 * result + ( getUser#() == null ? 0 : this.getUser#().hashCode() );
         return result;
   }   


}


