package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrSessionActions.Id;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * LogmnrSessionActions. generated by hbm2java
 */
public class LogmnrSessionActions.  implements java.io.Serializable {


     private LogmnrSessionActions.Id id;
     private BigDecimal flagsruntime;
     private BigDecimal dropscn;
     private Serializable modifytime;
     private Serializable dispatchtime;
     private Serializable droptime;
     private BigDecimal lcrcount;
     private BigDecimal processrole#;
     private BigDecimal actiontype#;
     private BigDecimal flagsdefinetime;
     private Serializable createtime;
     private BigDecimal xidusn;
     private BigDecimal xidslt;
     private BigDecimal xidsqn;
     private BigDecimal thread#;
     private BigDecimal startscn;
     private BigDecimal startsubscn;
     private BigDecimal endscn;
     private BigDecimal endsubscn;
     private BigDecimal rbasqn;
     private BigDecimal rbablk;
     private BigDecimal rbabyte;
     private BigDecimal session#;
     private BigDecimal obj#;
     private BigDecimal attr1;
     private BigDecimal attr2;
     private BigDecimal attr3;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private Serializable spare3;
     private String spare4;
     private BigDecimal pdbid;
     private String pdbName;

    public LogmnrSessionActions.() {
    }

	
    public LogmnrSessionActions.(LogmnrSessionActions.Id id, BigDecimal processrole#, BigDecimal actiontype#) {
        this.id = id;
        this.processrole# = processrole#;
        this.actiontype# = actiontype#;
    }
    public LogmnrSessionActions.(LogmnrSessionActions.Id id, BigDecimal flagsruntime, BigDecimal dropscn, Serializable modifytime, Serializable dispatchtime, Serializable droptime, BigDecimal lcrcount, BigDecimal processrole#, BigDecimal actiontype#, BigDecimal flagsdefinetime, Serializable createtime, BigDecimal xidusn, BigDecimal xidslt, BigDecimal xidsqn, BigDecimal thread#, BigDecimal startscn, BigDecimal startsubscn, BigDecimal endscn, BigDecimal endsubscn, BigDecimal rbasqn, BigDecimal rbablk, BigDecimal rbabyte, BigDecimal session#, BigDecimal obj#, BigDecimal attr1, BigDecimal attr2, BigDecimal attr3, BigDecimal spare1, BigDecimal spare2, Serializable spare3, String spare4, BigDecimal pdbid, String pdbName) {
       this.id = id;
       this.flagsruntime = flagsruntime;
       this.dropscn = dropscn;
       this.modifytime = modifytime;
       this.dispatchtime = dispatchtime;
       this.droptime = droptime;
       this.lcrcount = lcrcount;
       this.processrole# = processrole#;
       this.actiontype# = actiontype#;
       this.flagsdefinetime = flagsdefinetime;
       this.createtime = createtime;
       this.xidusn = xidusn;
       this.xidslt = xidslt;
       this.xidsqn = xidsqn;
       this.thread# = thread#;
       this.startscn = startscn;
       this.startsubscn = startsubscn;
       this.endscn = endscn;
       this.endsubscn = endsubscn;
       this.rbasqn = rbasqn;
       this.rbablk = rbablk;
       this.rbabyte = rbabyte;
       this.session# = session#;
       this.obj# = obj#;
       this.attr1 = attr1;
       this.attr2 = attr2;
       this.attr3 = attr3;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.spare3 = spare3;
       this.spare4 = spare4;
       this.pdbid = pdbid;
       this.pdbName = pdbName;
    }
   
    public LogmnrSessionActions.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrSessionActions.Id id) {
        this.id = id;
    }
    public BigDecimal getFlagsruntime() {
        return this.flagsruntime;
    }
    
    public void setFlagsruntime(BigDecimal flagsruntime) {
        this.flagsruntime = flagsruntime;
    }
    public BigDecimal getDropscn() {
        return this.dropscn;
    }
    
    public void setDropscn(BigDecimal dropscn) {
        this.dropscn = dropscn;
    }
    public Serializable getModifytime() {
        return this.modifytime;
    }
    
    public void setModifytime(Serializable modifytime) {
        this.modifytime = modifytime;
    }
    public Serializable getDispatchtime() {
        return this.dispatchtime;
    }
    
    public void setDispatchtime(Serializable dispatchtime) {
        this.dispatchtime = dispatchtime;
    }
    public Serializable getDroptime() {
        return this.droptime;
    }
    
    public void setDroptime(Serializable droptime) {
        this.droptime = droptime;
    }
    public BigDecimal getLcrcount() {
        return this.lcrcount;
    }
    
    public void setLcrcount(BigDecimal lcrcount) {
        this.lcrcount = lcrcount;
    }
    public BigDecimal getProcessrole#() {
        return this.processrole#;
    }
    
    public void setProcessrole#(BigDecimal processrole#) {
        this.processrole# = processrole#;
    }
    public BigDecimal getActiontype#() {
        return this.actiontype#;
    }
    
    public void setActiontype#(BigDecimal actiontype#) {
        this.actiontype# = actiontype#;
    }
    public BigDecimal getFlagsdefinetime() {
        return this.flagsdefinetime;
    }
    
    public void setFlagsdefinetime(BigDecimal flagsdefinetime) {
        this.flagsdefinetime = flagsdefinetime;
    }
    public Serializable getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Serializable createtime) {
        this.createtime = createtime;
    }
    public BigDecimal getXidusn() {
        return this.xidusn;
    }
    
    public void setXidusn(BigDecimal xidusn) {
        this.xidusn = xidusn;
    }
    public BigDecimal getXidslt() {
        return this.xidslt;
    }
    
    public void setXidslt(BigDecimal xidslt) {
        this.xidslt = xidslt;
    }
    public BigDecimal getXidsqn() {
        return this.xidsqn;
    }
    
    public void setXidsqn(BigDecimal xidsqn) {
        this.xidsqn = xidsqn;
    }
    public BigDecimal getThread#() {
        return this.thread#;
    }
    
    public void setThread#(BigDecimal thread#) {
        this.thread# = thread#;
    }
    public BigDecimal getStartscn() {
        return this.startscn;
    }
    
    public void setStartscn(BigDecimal startscn) {
        this.startscn = startscn;
    }
    public BigDecimal getStartsubscn() {
        return this.startsubscn;
    }
    
    public void setStartsubscn(BigDecimal startsubscn) {
        this.startsubscn = startsubscn;
    }
    public BigDecimal getEndscn() {
        return this.endscn;
    }
    
    public void setEndscn(BigDecimal endscn) {
        this.endscn = endscn;
    }
    public BigDecimal getEndsubscn() {
        return this.endsubscn;
    }
    
    public void setEndsubscn(BigDecimal endsubscn) {
        this.endsubscn = endsubscn;
    }
    public BigDecimal getRbasqn() {
        return this.rbasqn;
    }
    
    public void setRbasqn(BigDecimal rbasqn) {
        this.rbasqn = rbasqn;
    }
    public BigDecimal getRbablk() {
        return this.rbablk;
    }
    
    public void setRbablk(BigDecimal rbablk) {
        this.rbablk = rbablk;
    }
    public BigDecimal getRbabyte() {
        return this.rbabyte;
    }
    
    public void setRbabyte(BigDecimal rbabyte) {
        this.rbabyte = rbabyte;
    }
    public BigDecimal getSession#() {
        return this.session#;
    }
    
    public void setSession#(BigDecimal session#) {
        this.session# = session#;
    }
    public BigDecimal getObj#() {
        return this.obj#;
    }
    
    public void setObj#(BigDecimal obj#) {
        this.obj# = obj#;
    }
    public BigDecimal getAttr1() {
        return this.attr1;
    }
    
    public void setAttr1(BigDecimal attr1) {
        this.attr1 = attr1;
    }
    public BigDecimal getAttr2() {
        return this.attr2;
    }
    
    public void setAttr2(BigDecimal attr2) {
        this.attr2 = attr2;
    }
    public BigDecimal getAttr3() {
        return this.attr3;
    }
    
    public void setAttr3(BigDecimal attr3) {
        this.attr3 = attr3;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public Serializable getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(Serializable spare3) {
        this.spare3 = spare3;
    }
    public String getSpare4() {
        return this.spare4;
    }
    
    public void setSpare4(String spare4) {
        this.spare4 = spare4;
    }
    public BigDecimal getPdbid() {
        return this.pdbid;
    }
    
    public void setPdbid(BigDecimal pdbid) {
        this.pdbid = pdbid;
    }
    public String getPdbName() {
        return this.pdbName;
    }
    
    public void setPdbName(String pdbName) {
        this.pdbName = pdbName;
    }




}


