package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrAgeSpill.Id;
import java.math.BigDecimal;
import java.sql.Blob;

/**
 * LogmnrAgeSpill. generated by hbm2java
 */
public class LogmnrAgeSpill.  implements java.io.Serializable {


     private LogmnrAgeSpill.Id id;
     private BigDecimal offset;
     private Blob spillData;
     private BigDecimal spare1;
     private BigDecimal spare2;

    public LogmnrAgeSpill.() {
    }

	
    public LogmnrAgeSpill.(LogmnrAgeSpill.Id id) {
        this.id = id;
    }
    public LogmnrAgeSpill.(LogmnrAgeSpill.Id id, BigDecimal offset, Blob spillData, BigDecimal spare1, BigDecimal spare2) {
       this.id = id;
       this.offset = offset;
       this.spillData = spillData;
       this.spare1 = spare1;
       this.spare2 = spare2;
    }
   
    public LogmnrAgeSpill.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrAgeSpill.Id id) {
        this.id = id;
    }
    public BigDecimal getOffset() {
        return this.offset;
    }
    
    public void setOffset(BigDecimal offset) {
        this.offset = offset;
    }
    public Blob getSpillData() {
        return this.spillData;
    }
    
    public void setSpillData(Blob spillData) {
        this.spillData = spillData;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }




}


