package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LogmnrDictionary. generated by hbm2java
 */
public class LogmnrDictionary.  implements java.io.Serializable {


     private BigDecimal logmnrUid;
     private String dbName;
     private BigDecimal dbId;
     private String dbCreated;
     private String dbDictCreated;
     private BigDecimal dbDictScn;
     private byte[] dbThreadMap;
     private BigDecimal dbTxnScnbas;
     private BigDecimal dbTxnScnwrp;
     private BigDecimal dbResetlogsChange#;
     private String dbResetlogsTime;
     private String dbVersionTime;
     private String dbRedoTypeId;
     private String dbRedoRelease;
     private String dbCharacterSet;
     private String dbVersion;
     private String dbStatus;
     private String dbGlobalName;
     private BigDecimal dbDictMaxobjects;
     private BigDecimal dbDictObjectcount;
     private BigDecimal logmnrFlags;
     private String pdbName;
     private BigDecimal pdbId;
     private BigDecimal pdbUid;
     private BigDecimal pdbDbid;
     private byte[] pdbGuid;
     private BigDecimal pdbCreateScn;
     private BigDecimal pdbCount;
     private String pdbGlobalName;
     private BigDecimal fedRootConId#;

    public LogmnrDictionary.() {
    }

	
    public LogmnrDictionary.(BigDecimal logmnrUid, BigDecimal dbDictObjectcount) {
        this.logmnrUid = logmnrUid;
        this.dbDictObjectcount = dbDictObjectcount;
    }
    public LogmnrDictionary.(BigDecimal logmnrUid, String dbName, BigDecimal dbId, String dbCreated, String dbDictCreated, BigDecimal dbDictScn, byte[] dbThreadMap, BigDecimal dbTxnScnbas, BigDecimal dbTxnScnwrp, BigDecimal dbResetlogsChange#, String dbResetlogsTime, String dbVersionTime, String dbRedoTypeId, String dbRedoRelease, String dbCharacterSet, String dbVersion, String dbStatus, String dbGlobalName, BigDecimal dbDictMaxobjects, BigDecimal dbDictObjectcount, BigDecimal logmnrFlags, String pdbName, BigDecimal pdbId, BigDecimal pdbUid, BigDecimal pdbDbid, byte[] pdbGuid, BigDecimal pdbCreateScn, BigDecimal pdbCount, String pdbGlobalName, BigDecimal fedRootConId#) {
       this.logmnrUid = logmnrUid;
       this.dbName = dbName;
       this.dbId = dbId;
       this.dbCreated = dbCreated;
       this.dbDictCreated = dbDictCreated;
       this.dbDictScn = dbDictScn;
       this.dbThreadMap = dbThreadMap;
       this.dbTxnScnbas = dbTxnScnbas;
       this.dbTxnScnwrp = dbTxnScnwrp;
       this.dbResetlogsChange# = dbResetlogsChange#;
       this.dbResetlogsTime = dbResetlogsTime;
       this.dbVersionTime = dbVersionTime;
       this.dbRedoTypeId = dbRedoTypeId;
       this.dbRedoRelease = dbRedoRelease;
       this.dbCharacterSet = dbCharacterSet;
       this.dbVersion = dbVersion;
       this.dbStatus = dbStatus;
       this.dbGlobalName = dbGlobalName;
       this.dbDictMaxobjects = dbDictMaxobjects;
       this.dbDictObjectcount = dbDictObjectcount;
       this.logmnrFlags = logmnrFlags;
       this.pdbName = pdbName;
       this.pdbId = pdbId;
       this.pdbUid = pdbUid;
       this.pdbDbid = pdbDbid;
       this.pdbGuid = pdbGuid;
       this.pdbCreateScn = pdbCreateScn;
       this.pdbCount = pdbCount;
       this.pdbGlobalName = pdbGlobalName;
       this.fedRootConId# = fedRootConId#;
    }
   
    public BigDecimal getLogmnrUid() {
        return this.logmnrUid;
    }
    
    public void setLogmnrUid(BigDecimal logmnrUid) {
        this.logmnrUid = logmnrUid;
    }
    public String getDbName() {
        return this.dbName;
    }
    
    public void setDbName(String dbName) {
        this.dbName = dbName;
    }
    public BigDecimal getDbId() {
        return this.dbId;
    }
    
    public void setDbId(BigDecimal dbId) {
        this.dbId = dbId;
    }
    public String getDbCreated() {
        return this.dbCreated;
    }
    
    public void setDbCreated(String dbCreated) {
        this.dbCreated = dbCreated;
    }
    public String getDbDictCreated() {
        return this.dbDictCreated;
    }
    
    public void setDbDictCreated(String dbDictCreated) {
        this.dbDictCreated = dbDictCreated;
    }
    public BigDecimal getDbDictScn() {
        return this.dbDictScn;
    }
    
    public void setDbDictScn(BigDecimal dbDictScn) {
        this.dbDictScn = dbDictScn;
    }
    public byte[] getDbThreadMap() {
        return this.dbThreadMap;
    }
    
    public void setDbThreadMap(byte[] dbThreadMap) {
        this.dbThreadMap = dbThreadMap;
    }
    public BigDecimal getDbTxnScnbas() {
        return this.dbTxnScnbas;
    }
    
    public void setDbTxnScnbas(BigDecimal dbTxnScnbas) {
        this.dbTxnScnbas = dbTxnScnbas;
    }
    public BigDecimal getDbTxnScnwrp() {
        return this.dbTxnScnwrp;
    }
    
    public void setDbTxnScnwrp(BigDecimal dbTxnScnwrp) {
        this.dbTxnScnwrp = dbTxnScnwrp;
    }
    public BigDecimal getDbResetlogsChange#() {
        return this.dbResetlogsChange#;
    }
    
    public void setDbResetlogsChange#(BigDecimal dbResetlogsChange#) {
        this.dbResetlogsChange# = dbResetlogsChange#;
    }
    public String getDbResetlogsTime() {
        return this.dbResetlogsTime;
    }
    
    public void setDbResetlogsTime(String dbResetlogsTime) {
        this.dbResetlogsTime = dbResetlogsTime;
    }
    public String getDbVersionTime() {
        return this.dbVersionTime;
    }
    
    public void setDbVersionTime(String dbVersionTime) {
        this.dbVersionTime = dbVersionTime;
    }
    public String getDbRedoTypeId() {
        return this.dbRedoTypeId;
    }
    
    public void setDbRedoTypeId(String dbRedoTypeId) {
        this.dbRedoTypeId = dbRedoTypeId;
    }
    public String getDbRedoRelease() {
        return this.dbRedoRelease;
    }
    
    public void setDbRedoRelease(String dbRedoRelease) {
        this.dbRedoRelease = dbRedoRelease;
    }
    public String getDbCharacterSet() {
        return this.dbCharacterSet;
    }
    
    public void setDbCharacterSet(String dbCharacterSet) {
        this.dbCharacterSet = dbCharacterSet;
    }
    public String getDbVersion() {
        return this.dbVersion;
    }
    
    public void setDbVersion(String dbVersion) {
        this.dbVersion = dbVersion;
    }
    public String getDbStatus() {
        return this.dbStatus;
    }
    
    public void setDbStatus(String dbStatus) {
        this.dbStatus = dbStatus;
    }
    public String getDbGlobalName() {
        return this.dbGlobalName;
    }
    
    public void setDbGlobalName(String dbGlobalName) {
        this.dbGlobalName = dbGlobalName;
    }
    public BigDecimal getDbDictMaxobjects() {
        return this.dbDictMaxobjects;
    }
    
    public void setDbDictMaxobjects(BigDecimal dbDictMaxobjects) {
        this.dbDictMaxobjects = dbDictMaxobjects;
    }
    public BigDecimal getDbDictObjectcount() {
        return this.dbDictObjectcount;
    }
    
    public void setDbDictObjectcount(BigDecimal dbDictObjectcount) {
        this.dbDictObjectcount = dbDictObjectcount;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }
    public String getPdbName() {
        return this.pdbName;
    }
    
    public void setPdbName(String pdbName) {
        this.pdbName = pdbName;
    }
    public BigDecimal getPdbId() {
        return this.pdbId;
    }
    
    public void setPdbId(BigDecimal pdbId) {
        this.pdbId = pdbId;
    }
    public BigDecimal getPdbUid() {
        return this.pdbUid;
    }
    
    public void setPdbUid(BigDecimal pdbUid) {
        this.pdbUid = pdbUid;
    }
    public BigDecimal getPdbDbid() {
        return this.pdbDbid;
    }
    
    public void setPdbDbid(BigDecimal pdbDbid) {
        this.pdbDbid = pdbDbid;
    }
    public byte[] getPdbGuid() {
        return this.pdbGuid;
    }
    
    public void setPdbGuid(byte[] pdbGuid) {
        this.pdbGuid = pdbGuid;
    }
    public BigDecimal getPdbCreateScn() {
        return this.pdbCreateScn;
    }
    
    public void setPdbCreateScn(BigDecimal pdbCreateScn) {
        this.pdbCreateScn = pdbCreateScn;
    }
    public BigDecimal getPdbCount() {
        return this.pdbCount;
    }
    
    public void setPdbCount(BigDecimal pdbCount) {
        this.pdbCount = pdbCount;
    }
    public String getPdbGlobalName() {
        return this.pdbGlobalName;
    }
    
    public void setPdbGlobalName(String pdbGlobalName) {
        this.pdbGlobalName = pdbGlobalName;
    }
    public BigDecimal getFedRootConId#() {
        return this.fedRootConId#;
    }
    
    public void setFedRootConId#(BigDecimal fedRootConId#) {
        this.fedRootConId# = fedRootConId#;
    }




}


