package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrTabpart.Id;
import java.math.BigDecimal;

/**
 * LogmnrTabpart. generated by hbm2java
 */
public class LogmnrTabpart.  implements java.io.Serializable {


     private LogmnrTabpart.Id id;
     private BigDecimal ts#;
     private BigDecimal part#;
     private BigDecimal logmnrFlags;

    public LogmnrTabpart.() {
    }

	
    public LogmnrTabpart.(LogmnrTabpart.Id id) {
        this.id = id;
    }
    public LogmnrTabpart.(LogmnrTabpart.Id id, BigDecimal ts#, BigDecimal part#, BigDecimal logmnrFlags) {
       this.id = id;
       this.ts# = ts#;
       this.part# = part#;
       this.logmnrFlags = logmnrFlags;
    }
   
    public LogmnrTabpart.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrTabpart.Id id) {
        this.id = id;
    }
    public BigDecimal getTs#() {
        return this.ts#;
    }
    
    public void setTs#(BigDecimal ts#) {
        this.ts# = ts#;
    }
    public BigDecimal getPart#() {
        return this.part#;
    }
    
    public void setPart#(BigDecimal part#) {
        this.part# = part#;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


