package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Logstdby.flashbackScn generated by hbm2java
 */
public class Logstdby.flashbackScn  implements java.io.Serializable {


     private BigDecimal primaryScn;
     private Date primaryTime;
     private BigDecimal standbyScn;
     private Date standbyTime;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private Date spare3;

    public Logstdby.flashbackScn() {
    }

	
    public Logstdby.flashbackScn(BigDecimal primaryScn) {
        this.primaryScn = primaryScn;
    }
    public Logstdby.flashbackScn(BigDecimal primaryScn, Date primaryTime, BigDecimal standbyScn, Date standbyTime, BigDecimal spare1, BigDecimal spare2, Date spare3) {
       this.primaryScn = primaryScn;
       this.primaryTime = primaryTime;
       this.standbyScn = standbyScn;
       this.standbyTime = standbyTime;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.spare3 = spare3;
    }
   
    public BigDecimal getPrimaryScn() {
        return this.primaryScn;
    }
    
    public void setPrimaryScn(BigDecimal primaryScn) {
        this.primaryScn = primaryScn;
    }
    public Date getPrimaryTime() {
        return this.primaryTime;
    }
    
    public void setPrimaryTime(Date primaryTime) {
        this.primaryTime = primaryTime;
    }
    public BigDecimal getStandbyScn() {
        return this.standbyScn;
    }
    
    public void setStandbyScn(BigDecimal standbyScn) {
        this.standbyScn = standbyScn;
    }
    public Date getStandbyTime() {
        return this.standbyTime;
    }
    
    public void setStandbyTime(Date standbyTime) {
        this.standbyTime = standbyTime;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public Date getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(Date spare3) {
        this.spare3 = spare3;
    }




}


