package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Logstdby.applyMilestoneId;

/**
 * Logstdby.applyMilestone generated by hbm2java
 */
public class Logstdby.applyMilestone  implements java.io.Serializable {


     private Logstdby.applyMilestoneId id;

    public Logstdby.applyMilestone() {
    }

    public Logstdby.applyMilestone(Logstdby.applyMilestoneId id) {
       this.id = id;
    }
   
    public Logstdby.applyMilestoneId getId() {
        return this.id;
    }
    
    public void setId(Logstdby.applyMilestoneId id) {
        this.id = id;
    }




}


