package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Logstdby.plsqlId;

/**
 * Logstdby.plsql generated by hbm2java
 */
public class Logstdby.plsql  implements java.io.Serializable {


     private Logstdby.plsqlId id;

    public Logstdby.plsql() {
    }

    public Logstdby.plsql(Logstdby.plsqlId id) {
       this.id = id;
    }
   
    public Logstdby.plsqlId getId() {
        return this.id;
    }
    
    public void setId(Logstdby.plsqlId id) {
        this.id = id;
    }




}


