package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Logstdby.skipId;

/**
 * Logstdby.skip generated by hbm2java
 */
public class Logstdby.skip  implements java.io.Serializable {


     private Logstdby.skipId id;

    public Logstdby.skip() {
    }

    public Logstdby.skip(Logstdby.skipId id) {
       this.id = id;
    }
   
    public Logstdby.skipId getId() {
        return this.id;
    }
    
    public void setId(Logstdby.skipId id) {
        this.id = id;
    }




}


