package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Logstdby.scnId;

/**
 * Logstdby.scn generated by hbm2java
 */
public class Logstdby.scn  implements java.io.Serializable {


     private Logstdby.scnId id;

    public Logstdby.scn() {
    }

    public Logstdby.scn(Logstdby.scnId id) {
       this.id = id;
    }
   
    public Logstdby.scnId getId() {
        return this.id;
    }
    
    public void setId(Logstdby.scnId id) {
        this.id = id;
    }




}


