package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Logstdby.eventsId;

/**
 * Logstdby.events generated by hbm2java
 */
public class Logstdby.events  implements java.io.Serializable {


     private Logstdby.eventsId id;

    public Logstdby.events() {
    }

    public Logstdby.events(Logstdby.eventsId id) {
       this.id = id;
    }
   
    public Logstdby.eventsId getId() {
        return this.id;
    }
    
    public void setId(Logstdby.eventsId id) {
        this.id = id;
    }




}


