package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Logstdby.scnId generated by hbm2java
 */
public class Logstdby.scnId  implements java.io.Serializable {


     private BigDecimal obj#;
     private String objname;
     private String schema;
     private String type;
     private BigDecimal scn;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private String spare3;

    public Logstdby.scnId() {
    }

    public Logstdby.scnId(BigDecimal obj#, String objname, String schema, String type, BigDecimal scn, BigDecimal spare1, BigDecimal spare2, String spare3) {
       this.obj# = obj#;
       this.objname = objname;
       this.schema = schema;
       this.type = type;
       this.scn = scn;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.spare3 = spare3;
    }
   
    public BigDecimal getObj#() {
        return this.obj#;
    }
    
    public void setObj#(BigDecimal obj#) {
        this.obj# = obj#;
    }
    public String getObjname() {
        return this.objname;
    }
    
    public void setObjname(String objname) {
        this.objname = objname;
    }
    public String getSchema() {
        return this.schema;
    }
    
    public void setSchema(String schema) {
        this.schema = schema;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public BigDecimal getScn() {
        return this.scn;
    }
    
    public void setScn(BigDecimal scn) {
        this.scn = scn;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public String getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(String spare3) {
        this.spare3 = spare3;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Logstdby.scnId) ) return false;
		 Logstdby.scnId castOther = ( Logstdby.scnId ) other; 
         
		 return ( (this.getObj#()==castOther.getObj#()) || ( this.getObj#()!=null && castOther.getObj#()!=null && this.getObj#().equals(castOther.getObj#()) ) )
 && ( (this.getObjname()==castOther.getObjname()) || ( this.getObjname()!=null && castOther.getObjname()!=null && this.getObjname().equals(castOther.getObjname()) ) )
 && ( (this.getSchema()==castOther.getSchema()) || ( this.getSchema()!=null && castOther.getSchema()!=null && this.getSchema().equals(castOther.getSchema()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && ( (this.getScn()==castOther.getScn()) || ( this.getScn()!=null && castOther.getScn()!=null && this.getScn().equals(castOther.getScn()) ) )
 && ( (this.getSpare1()==castOther.getSpare1()) || ( this.getSpare1()!=null && castOther.getSpare1()!=null && this.getSpare1().equals(castOther.getSpare1()) ) )
 && ( (this.getSpare2()==castOther.getSpare2()) || ( this.getSpare2()!=null && castOther.getSpare2()!=null && this.getSpare2().equals(castOther.getSpare2()) ) )
 && ( (this.getSpare3()==castOther.getSpare3()) || ( this.getSpare3()!=null && castOther.getSpare3()!=null && this.getSpare3().equals(castOther.getSpare3()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getObj#() == null ? 0 : this.getObj#().hashCode() );
         result = 37 * result + ( getObjname() == null ? 0 : this.getObjname().hashCode() );
         result = 37 * result + ( getSchema() == null ? 0 : this.getSchema().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + ( getScn() == null ? 0 : this.getScn().hashCode() );
         result = 37 * result + ( getSpare1() == null ? 0 : this.getSpare1().hashCode() );
         result = 37 * result + ( getSpare2() == null ? 0 : this.getSpare2().hashCode() );
         result = 37 * result + ( getSpare3() == null ? 0 : this.getSpare3().hashCode() );
         return result;
   }   


}


