package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Logstdby.applyProgressId;

/**
 * Logstdby.applyProgress generated by hbm2java
 */
public class Logstdby.applyProgress  implements java.io.Serializable {


     private Logstdby.applyProgressId id;

    public Logstdby.applyProgress() {
    }

    public Logstdby.applyProgress(Logstdby.applyProgressId id) {
       this.id = id;
    }
   
    public Logstdby.applyProgressId getId() {
        return this.id;
    }
    
    public void setId(Logstdby.applyProgressId id) {
        this.id = id;
    }




}


