package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Logstdby.skipSupportId;

/**
 * Logstdby.skipSupport generated by hbm2java
 */
public class Logstdby.skipSupport  implements java.io.Serializable {


     private Logstdby.skipSupportId id;

    public Logstdby.skipSupport() {
    }

    public Logstdby.skipSupport(Logstdby.skipSupportId id) {
       this.id = id;
    }
   
    public Logstdby.skipSupportId getId() {
        return this.id;
    }
    
    public void setId(Logstdby.skipSupportId id) {
        this.id = id;
    }




}


