package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Mview.AdvFilterId generated by hbm2java
 */
public class Mview.AdvFilterId  implements java.io.Serializable {


     private BigDecimal filterid#;
     private BigDecimal subfilternum#;

    public Mview.AdvFilterId() {
    }

    public Mview.AdvFilterId(BigDecimal filterid#, BigDecimal subfilternum#) {
       this.filterid# = filterid#;
       this.subfilternum# = subfilternum#;
    }
   
    public BigDecimal getFilterid#() {
        return this.filterid#;
    }
    
    public void setFilterid#(BigDecimal filterid#) {
        this.filterid# = filterid#;
    }
    public BigDecimal getSubfilternum#() {
        return this.subfilternum#;
    }
    
    public void setSubfilternum#(BigDecimal subfilternum#) {
        this.subfilternum# = subfilternum#;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Mview.AdvFilterId) ) return false;
		 Mview.AdvFilterId castOther = ( Mview.AdvFilterId ) other; 
         
		 return ( (this.getFilterid#()==castOther.getFilterid#()) || ( this.getFilterid#()!=null && castOther.getFilterid#()!=null && this.getFilterid#().equals(castOther.getFilterid#()) ) )
 && ( (this.getSubfilternum#()==castOther.getSubfilternum#()) || ( this.getSubfilternum#()!=null && castOther.getSubfilternum#()!=null && this.getSubfilternum#().equals(castOther.getSubfilternum#()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFilterid#() == null ? 0 : this.getFilterid#().hashCode() );
         result = 37 * result + ( getSubfilternum#() == null ? 0 : this.getSubfilternum#().hashCode() );
         return result;
   }   


}


