package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Mview.AdvJournalId generated by hbm2java
 */
public class Mview.AdvJournalId  implements java.io.Serializable {


     private BigDecimal runid#;
     private BigDecimal seq#;

    public Mview.AdvJournalId() {
    }

    public Mview.AdvJournalId(BigDecimal runid#, BigDecimal seq#) {
       this.runid# = runid#;
       this.seq# = seq#;
    }
   
    public BigDecimal getRunid#() {
        return this.runid#;
    }
    
    public void setRunid#(BigDecimal runid#) {
        this.runid# = runid#;
    }
    public BigDecimal getSeq#() {
        return this.seq#;
    }
    
    public void setSeq#(BigDecimal seq#) {
        this.seq# = seq#;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Mview.AdvJournalId) ) return false;
		 Mview.AdvJournalId castOther = ( Mview.AdvJournalId ) other; 
         
		 return ( (this.getRunid#()==castOther.getRunid#()) || ( this.getRunid#()!=null && castOther.getRunid#()!=null && this.getRunid#().equals(castOther.getRunid#()) ) )
 && ( (this.getSeq#()==castOther.getSeq#()) || ( this.getSeq#()!=null && castOther.getSeq#()!=null && this.getSeq#().equals(castOther.getSeq#()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRunid#() == null ? 0 : this.getRunid#().hashCode() );
         result = 37 * result + ( getSeq#() == null ? 0 : this.getSeq#().hashCode() );
         return result;
   }   


}


