package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1

/**
 * MviewEvaluations generated by hbm2java
 */
public class MviewEvaluations implements java.io.Serializable {

	private MviewEvaluationsId id;

	public MviewEvaluations() {
	}

	public MviewEvaluations(MviewEvaluationsId id) {
		this.id = id;
	}

	public MviewEvaluationsId getId() {
		return this.id;
	}

	public void setId(MviewEvaluationsId id) {
		this.id = id;
	}

}
