package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * MviewLogId generated by hbm2java
 */
public class MviewLogId implements java.io.Serializable {

	private BigDecimal id;
	private BigDecimal filterid;
	private Date runBegin;
	private Date runEnd;
	private String type;
	private String status;
	private String message;
	private BigDecimal completed;
	private BigDecimal total;
	private String errorCode;

	public MviewLogId() {
	}

	public MviewLogId(BigDecimal id) {
		this.id = id;
	}

	public MviewLogId(BigDecimal id, BigDecimal filterid, Date runBegin, Date runEnd, String type, String status,
			String message, BigDecimal completed, BigDecimal total, String errorCode) {
		this.id = id;
		this.filterid = filterid;
		this.runBegin = runBegin;
		this.runEnd = runEnd;
		this.type = type;
		this.status = status;
		this.message = message;
		this.completed = completed;
		this.total = total;
		this.errorCode = errorCode;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public BigDecimal getFilterid() {
		return this.filterid;
	}

	public void setFilterid(BigDecimal filterid) {
		this.filterid = filterid;
	}

	public Date getRunBegin() {
		return this.runBegin;
	}

	public void setRunBegin(Date runBegin) {
		this.runBegin = runBegin;
	}

	public Date getRunEnd() {
		return this.runEnd;
	}

	public void setRunEnd(Date runEnd) {
		this.runEnd = runEnd;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public BigDecimal getCompleted() {
		return this.completed;
	}

	public void setCompleted(BigDecimal completed) {
		this.completed = completed;
	}

	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MviewLogId))
			return false;
		MviewLogId castOther = (MviewLogId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getFilterid() == castOther.getFilterid()) || (this.getFilterid() != null
						&& castOther.getFilterid() != null && this.getFilterid().equals(castOther.getFilterid())))
				&& ((this.getRunBegin() == castOther.getRunBegin()) || (this.getRunBegin() != null
						&& castOther.getRunBegin() != null && this.getRunBegin().equals(castOther.getRunBegin())))
				&& ((this.getRunEnd() == castOther.getRunEnd()) || (this.getRunEnd() != null
						&& castOther.getRunEnd() != null && this.getRunEnd().equals(castOther.getRunEnd())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null
						&& this.getType().equals(castOther.getType())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getMessage() == castOther.getMessage()) || (this.getMessage() != null
						&& castOther.getMessage() != null && this.getMessage().equals(castOther.getMessage())))
				&& ((this.getCompleted() == castOther.getCompleted()) || (this.getCompleted() != null
						&& castOther.getCompleted() != null && this.getCompleted().equals(castOther.getCompleted())))
				&& ((this.getTotal() == castOther.getTotal()) || (this.getTotal() != null
						&& castOther.getTotal() != null && this.getTotal().equals(castOther.getTotal())))
				&& ((this.getErrorCode() == castOther.getErrorCode()) || (this.getErrorCode() != null
						&& castOther.getErrorCode() != null && this.getErrorCode().equals(castOther.getErrorCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getFilterid() == null ? 0 : this.getFilterid().hashCode());
		result = 37 * result + (getRunBegin() == null ? 0 : this.getRunBegin().hashCode());
		result = 37 * result + (getRunEnd() == null ? 0 : this.getRunEnd().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getMessage() == null ? 0 : this.getMessage().hashCode());
		result = 37 * result + (getCompleted() == null ? 0 : this.getCompleted().hashCode());
		result = 37 * result + (getTotal() == null ? 0 : this.getTotal().hashCode());
		result = 37 * result + (getErrorCode() == null ? 0 : this.getErrorCode().hashCode());
		return result;
	}

}
