package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Mview.AdvAjg;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Mview.AdvFjg generated by hbm2java
 */
public class Mview.AdvFjg  implements java.io.Serializable {


     private BigDecimal fjgid#;
     private Mview.AdvAjg mview$AdvAjg;
     private BigDecimal fjgdeslen;
     private byte[] fjgdes;
     private BigDecimal hashvalue;
     private BigDecimal frequency;
     private Set mview$AdvGcs = new HashSet(0);

    public Mview.AdvFjg() {
    }

	
    public Mview.AdvFjg(BigDecimal fjgid#, Mview.AdvAjg mview$AdvAjg, BigDecimal fjgdeslen, byte[] fjgdes, BigDecimal hashvalue) {
        this.fjgid# = fjgid#;
        this.mview$AdvAjg = mview$AdvAjg;
        this.fjgdeslen = fjgdeslen;
        this.fjgdes = fjgdes;
        this.hashvalue = hashvalue;
    }
    public Mview.AdvFjg(BigDecimal fjgid#, Mview.AdvAjg mview$AdvAjg, BigDecimal fjgdeslen, byte[] fjgdes, BigDecimal hashvalue, BigDecimal frequency, Set mview$AdvGcs) {
       this.fjgid# = fjgid#;
       this.mview$AdvAjg = mview$AdvAjg;
       this.fjgdeslen = fjgdeslen;
       this.fjgdes = fjgdes;
       this.hashvalue = hashvalue;
       this.frequency = frequency;
       this.mview$AdvGcs = mview$AdvGcs;
    }
   
    public BigDecimal getFjgid#() {
        return this.fjgid#;
    }
    
    public void setFjgid#(BigDecimal fjgid#) {
        this.fjgid# = fjgid#;
    }
    public Mview.AdvAjg getMview$AdvAjg() {
        return this.mview$AdvAjg;
    }
    
    public void setMview$AdvAjg(Mview.AdvAjg mview$AdvAjg) {
        this.mview$AdvAjg = mview$AdvAjg;
    }
    public BigDecimal getFjgdeslen() {
        return this.fjgdeslen;
    }
    
    public void setFjgdeslen(BigDecimal fjgdeslen) {
        this.fjgdeslen = fjgdeslen;
    }
    public byte[] getFjgdes() {
        return this.fjgdes;
    }
    
    public void setFjgdes(byte[] fjgdes) {
        this.fjgdes = fjgdes;
    }
    public BigDecimal getHashvalue() {
        return this.hashvalue;
    }
    
    public void setHashvalue(BigDecimal hashvalue) {
        this.hashvalue = hashvalue;
    }
    public BigDecimal getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(BigDecimal frequency) {
        this.frequency = frequency;
    }
    public Set getMview$AdvGcs() {
        return this.mview$AdvGcs;
    }
    
    public void setMview$AdvGcs(Set mview$AdvGcs) {
        this.mview$AdvGcs = mview$AdvGcs;
    }




}


