package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Mview.AdvFilterId;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Mview.AdvFilter generated by hbm2java
 */
public class Mview.AdvFilter  implements java.io.Serializable {


     private Mview.AdvFilterId id;
     private BigDecimal subfiltertype;
     private String strValue;
     private BigDecimal numValue1;
     private BigDecimal numValue2;
     private Date dateValue1;
     private Date dateValue2;

    public Mview.AdvFilter() {
    }

	
    public Mview.AdvFilter(Mview.AdvFilterId id, BigDecimal subfiltertype) {
        this.id = id;
        this.subfiltertype = subfiltertype;
    }
    public Mview.AdvFilter(Mview.AdvFilterId id, BigDecimal subfiltertype, String strValue, BigDecimal numValue1, BigDecimal numValue2, Date dateValue1, Date dateValue2) {
       this.id = id;
       this.subfiltertype = subfiltertype;
       this.strValue = strValue;
       this.numValue1 = numValue1;
       this.numValue2 = numValue2;
       this.dateValue1 = dateValue1;
       this.dateValue2 = dateValue2;
    }
   
    public Mview.AdvFilterId getId() {
        return this.id;
    }
    
    public void setId(Mview.AdvFilterId id) {
        this.id = id;
    }
    public BigDecimal getSubfiltertype() {
        return this.subfiltertype;
    }
    
    public void setSubfiltertype(BigDecimal subfiltertype) {
        this.subfiltertype = subfiltertype;
    }
    public String getStrValue() {
        return this.strValue;
    }
    
    public void setStrValue(String strValue) {
        this.strValue = strValue;
    }
    public BigDecimal getNumValue1() {
        return this.numValue1;
    }
    
    public void setNumValue1(BigDecimal numValue1) {
        this.numValue1 = numValue1;
    }
    public BigDecimal getNumValue2() {
        return this.numValue2;
    }
    
    public void setNumValue2(BigDecimal numValue2) {
        this.numValue2 = numValue2;
    }
    public Date getDateValue1() {
        return this.dateValue1;
    }
    
    public void setDateValue1(Date dateValue1) {
        this.dateValue1 = dateValue1;
    }
    public Date getDateValue2() {
        return this.dateValue2;
    }
    
    public void setDateValue2(Date dateValue2) {
        this.dateValue2 = dateValue2;
    }




}


