package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Mview.AdvLog;
import java.math.BigDecimal;

/**
 * Mview.AdvClique generated by hbm2java
 */
public class Mview.AdvClique  implements java.io.Serializable {


     private BigDecimal cliqueid#;
     private Mview.AdvLog mview$AdvLog;
     private BigDecimal cliquedeslen;
     private byte[] cliquedes;
     private BigDecimal hashvalue;
     private BigDecimal frequency;
     private BigDecimal bytecost;
     private BigDecimal rowsize;
     private BigDecimal numrows;

    public Mview.AdvClique() {
    }

    public Mview.AdvClique(BigDecimal cliqueid#, Mview.AdvLog mview$AdvLog, BigDecimal cliquedeslen, byte[] cliquedes, BigDecimal hashvalue, BigDecimal frequency, BigDecimal bytecost, BigDecimal rowsize, BigDecimal numrows) {
       this.cliqueid# = cliqueid#;
       this.mview$AdvLog = mview$AdvLog;
       this.cliquedeslen = cliquedeslen;
       this.cliquedes = cliquedes;
       this.hashvalue = hashvalue;
       this.frequency = frequency;
       this.bytecost = bytecost;
       this.rowsize = rowsize;
       this.numrows = numrows;
    }
   
    public BigDecimal getCliqueid#() {
        return this.cliqueid#;
    }
    
    public void setCliqueid#(BigDecimal cliqueid#) {
        this.cliqueid# = cliqueid#;
    }
    public Mview.AdvLog getMview$AdvLog() {
        return this.mview$AdvLog;
    }
    
    public void setMview$AdvLog(Mview.AdvLog mview$AdvLog) {
        this.mview$AdvLog = mview$AdvLog;
    }
    public BigDecimal getCliquedeslen() {
        return this.cliquedeslen;
    }
    
    public void setCliquedeslen(BigDecimal cliquedeslen) {
        this.cliquedeslen = cliquedeslen;
    }
    public byte[] getCliquedes() {
        return this.cliquedes;
    }
    
    public void setCliquedes(byte[] cliquedes) {
        this.cliquedes = cliquedes;
    }
    public BigDecimal getHashvalue() {
        return this.hashvalue;
    }
    
    public void setHashvalue(BigDecimal hashvalue) {
        this.hashvalue = hashvalue;
    }
    public BigDecimal getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(BigDecimal frequency) {
        this.frequency = frequency;
    }
    public BigDecimal getBytecost() {
        return this.bytecost;
    }
    
    public void setBytecost(BigDecimal bytecost) {
        this.bytecost = bytecost;
    }
    public BigDecimal getRowsize() {
        return this.rowsize;
    }
    
    public void setRowsize(BigDecimal rowsize) {
        this.rowsize = rowsize;
    }
    public BigDecimal getNumrows() {
        return this.numrows;
    }
    
    public void setNumrows(BigDecimal numrows) {
        this.numrows = numrows;
    }




}


