package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Mview.AdvInfoId;
import com.abctreinamentos.Mview.AdvLog;
import java.math.BigDecimal;

/**
 * Mview.AdvInfo generated by hbm2java
 */
public class Mview.AdvInfo  implements java.io.Serializable {


     private Mview.AdvInfoId id;
     private Mview.AdvLog mview$AdvLog;
     private BigDecimal type;
     private BigDecimal infolen;
     private byte[] info;
     private BigDecimal status;
     private BigDecimal flag;

    public Mview.AdvInfo() {
    }

	
    public Mview.AdvInfo(Mview.AdvInfoId id, Mview.AdvLog mview$AdvLog, BigDecimal type, BigDecimal infolen) {
        this.id = id;
        this.mview$AdvLog = mview$AdvLog;
        this.type = type;
        this.infolen = infolen;
    }
    public Mview.AdvInfo(Mview.AdvInfoId id, Mview.AdvLog mview$AdvLog, BigDecimal type, BigDecimal infolen, byte[] info, BigDecimal status, BigDecimal flag) {
       this.id = id;
       this.mview$AdvLog = mview$AdvLog;
       this.type = type;
       this.infolen = infolen;
       this.info = info;
       this.status = status;
       this.flag = flag;
    }
   
    public Mview.AdvInfoId getId() {
        return this.id;
    }
    
    public void setId(Mview.AdvInfoId id) {
        this.id = id;
    }
    public Mview.AdvLog getMview$AdvLog() {
        return this.mview$AdvLog;
    }
    
    public void setMview$AdvLog(Mview.AdvLog mview$AdvLog) {
        this.mview$AdvLog = mview$AdvLog;
    }
    public BigDecimal getType() {
        return this.type;
    }
    
    public void setType(BigDecimal type) {
        this.type = type;
    }
    public BigDecimal getInfolen() {
        return this.infolen;
    }
    
    public void setInfolen(BigDecimal infolen) {
        this.infolen = infolen;
    }
    public byte[] getInfo() {
        return this.info;
    }
    
    public void setInfo(byte[] info) {
        this.info = info;
    }
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }
    public BigDecimal getFlag() {
        return this.flag;
    }
    
    public void setFlag(BigDecimal flag) {
        this.flag = flag;
    }




}


