package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Mview.AdvEligibleId;
import com.abctreinamentos.Mview.AdvLog;
import java.math.BigDecimal;

/**
 * Mview.AdvEligible generated by hbm2java
 */
public class Mview.AdvEligible  implements java.io.Serializable {


     private Mview.AdvEligibleId id;
     private Mview.AdvLog mview$AdvLog;
     private BigDecimal bytecost;
     private BigDecimal flags;
     private BigDecimal frequency;

    public Mview.AdvEligible() {
    }

    public Mview.AdvEligible(Mview.AdvEligibleId id, Mview.AdvLog mview$AdvLog, BigDecimal bytecost, BigDecimal flags, BigDecimal frequency) {
       this.id = id;
       this.mview$AdvLog = mview$AdvLog;
       this.bytecost = bytecost;
       this.flags = flags;
       this.frequency = frequency;
    }
   
    public Mview.AdvEligibleId getId() {
        return this.id;
    }
    
    public void setId(Mview.AdvEligibleId id) {
        this.id = id;
    }
    public Mview.AdvLog getMview$AdvLog() {
        return this.mview$AdvLog;
    }
    
    public void setMview$AdvLog(Mview.AdvLog mview$AdvLog) {
        this.mview$AdvLog = mview$AdvLog;
    }
    public BigDecimal getBytecost() {
        return this.bytecost;
    }
    
    public void setBytecost(BigDecimal bytecost) {
        this.bytecost = bytecost;
    }
    public BigDecimal getFlags() {
        return this.flags;
    }
    
    public void setFlags(BigDecimal flags) {
        this.flags = flags;
    }
    public BigDecimal getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(BigDecimal frequency) {
        this.frequency = frequency;
    }




}


