package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mview.AdvWorkload generated by hbm2java
 */
public class Mview.AdvWorkload  implements java.io.Serializable {


     private BigDecimal queryid#;
     private BigDecimal collectionid#;
     private Date collecttime;
     private String application;
     private BigDecimal cardinality;
     private BigDecimal resultsize;
     private String uname;
     private Date qdate;
     private BigDecimal priority;
     private BigDecimal execTime;
     private String sqlText;
     private BigDecimal sqlTextlen;
     private BigDecimal sqlHash;
     private byte[] sqlAddr;
     private BigDecimal frequency;
     private Set mview$AdvBasetables = new HashSet(0);

    public Mview.AdvWorkload() {
    }

	
    public Mview.AdvWorkload(BigDecimal queryid#, BigDecimal collectionid#, Date collecttime, String uname, String sqlText, BigDecimal sqlTextlen) {
        this.queryid# = queryid#;
        this.collectionid# = collectionid#;
        this.collecttime = collecttime;
        this.uname = uname;
        this.sqlText = sqlText;
        this.sqlTextlen = sqlTextlen;
    }
    public Mview.AdvWorkload(BigDecimal queryid#, BigDecimal collectionid#, Date collecttime, String application, BigDecimal cardinality, BigDecimal resultsize, String uname, Date qdate, BigDecimal priority, BigDecimal execTime, String sqlText, BigDecimal sqlTextlen, BigDecimal sqlHash, byte[] sqlAddr, BigDecimal frequency, Set mview$AdvBasetables) {
       this.queryid# = queryid#;
       this.collectionid# = collectionid#;
       this.collecttime = collecttime;
       this.application = application;
       this.cardinality = cardinality;
       this.resultsize = resultsize;
       this.uname = uname;
       this.qdate = qdate;
       this.priority = priority;
       this.execTime = execTime;
       this.sqlText = sqlText;
       this.sqlTextlen = sqlTextlen;
       this.sqlHash = sqlHash;
       this.sqlAddr = sqlAddr;
       this.frequency = frequency;
       this.mview$AdvBasetables = mview$AdvBasetables;
    }
   
    public BigDecimal getQueryid#() {
        return this.queryid#;
    }
    
    public void setQueryid#(BigDecimal queryid#) {
        this.queryid# = queryid#;
    }
    public BigDecimal getCollectionid#() {
        return this.collectionid#;
    }
    
    public void setCollectionid#(BigDecimal collectionid#) {
        this.collectionid# = collectionid#;
    }
    public Date getCollecttime() {
        return this.collecttime;
    }
    
    public void setCollecttime(Date collecttime) {
        this.collecttime = collecttime;
    }
    public String getApplication() {
        return this.application;
    }
    
    public void setApplication(String application) {
        this.application = application;
    }
    public BigDecimal getCardinality() {
        return this.cardinality;
    }
    
    public void setCardinality(BigDecimal cardinality) {
        this.cardinality = cardinality;
    }
    public BigDecimal getResultsize() {
        return this.resultsize;
    }
    
    public void setResultsize(BigDecimal resultsize) {
        this.resultsize = resultsize;
    }
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public Date getQdate() {
        return this.qdate;
    }
    
    public void setQdate(Date qdate) {
        this.qdate = qdate;
    }
    public BigDecimal getPriority() {
        return this.priority;
    }
    
    public void setPriority(BigDecimal priority) {
        this.priority = priority;
    }
    public BigDecimal getExecTime() {
        return this.execTime;
    }
    
    public void setExecTime(BigDecimal execTime) {
        this.execTime = execTime;
    }
    public String getSqlText() {
        return this.sqlText;
    }
    
    public void setSqlText(String sqlText) {
        this.sqlText = sqlText;
    }
    public BigDecimal getSqlTextlen() {
        return this.sqlTextlen;
    }
    
    public void setSqlTextlen(BigDecimal sqlTextlen) {
        this.sqlTextlen = sqlTextlen;
    }
    public BigDecimal getSqlHash() {
        return this.sqlHash;
    }
    
    public void setSqlHash(BigDecimal sqlHash) {
        this.sqlHash = sqlHash;
    }
    public byte[] getSqlAddr() {
        return this.sqlAddr;
    }
    
    public void setSqlAddr(byte[] sqlAddr) {
        this.sqlAddr = sqlAddr;
    }
    public BigDecimal getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(BigDecimal frequency) {
        this.frequency = frequency;
    }
    public Set getMview$AdvBasetables() {
        return this.mview$AdvBasetables;
    }
    
    public void setMview$AdvBasetables(Set mview$AdvBasetables) {
        this.mview$AdvBasetables = mview$AdvBasetables;
    }




}


