package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Mview.AdvJournalId;
import com.abctreinamentos.Mview.AdvLog;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Mview.AdvJournal generated by hbm2java
 */
public class Mview.AdvJournal  implements java.io.Serializable {


     private Mview.AdvJournalId id;
     private Date timestamp;
     private Mview.AdvLog mview$AdvLog;
     private BigDecimal flags;
     private BigDecimal num;
     private String text;
     private BigDecimal textlen;

    public Mview.AdvJournal() {
    }

	
    public Mview.AdvJournal(Mview.AdvJournalId id, Mview.AdvLog mview$AdvLog, BigDecimal flags) {
        this.id = id;
        this.mview$AdvLog = mview$AdvLog;
        this.flags = flags;
    }
    public Mview.AdvJournal(Mview.AdvJournalId id, Mview.AdvLog mview$AdvLog, BigDecimal flags, BigDecimal num, String text, BigDecimal textlen) {
       this.id = id;
       this.mview$AdvLog = mview$AdvLog;
       this.flags = flags;
       this.num = num;
       this.text = text;
       this.textlen = textlen;
    }
   
    public Mview.AdvJournalId getId() {
        return this.id;
    }
    
    public void setId(Mview.AdvJournalId id) {
        this.id = id;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public Mview.AdvLog getMview$AdvLog() {
        return this.mview$AdvLog;
    }
    
    public void setMview$AdvLog(Mview.AdvLog mview$AdvLog) {
        this.mview$AdvLog = mview$AdvLog;
    }
    public BigDecimal getFlags() {
        return this.flags;
    }
    
    public void setFlags(BigDecimal flags) {
        this.flags = flags;
    }
    public BigDecimal getNum() {
        return this.num;
    }
    
    public void setNum(BigDecimal num) {
        this.num = num;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public BigDecimal getTextlen() {
        return this.textlen;
    }
    
    public void setTextlen(BigDecimal textlen) {
        this.textlen = textlen;
    }




}


