package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Mview.AdvTempId;

/**
 * Mview.AdvTemp generated by hbm2java
 */
public class Mview.AdvTemp  implements java.io.Serializable {


     private Mview.AdvTempId id;

    public Mview.AdvTemp() {
    }

    public Mview.AdvTemp(Mview.AdvTempId id) {
       this.id = id;
    }
   
    public Mview.AdvTempId getId() {
        return this.id;
    }
    
    public void setId(Mview.AdvTempId id) {
        this.id = id;
    }




}


