package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1

/**
 * RedoLog generated by hbm2java
 */
public class RedoLog implements java.io.Serializable {

	private RedoLogId id;

	public RedoLog() {
	}

	public RedoLog(RedoLogId id) {
		this.id = id;
	}

	public RedoLogId getId() {
		return this.id;
	}

	public void setId(RedoLogId id) {
		this.id = id;
	}

}
