package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1

/**
 * RedoDb generated by hbm2java
 */
public class RedoDb implements java.io.Serializable {

	private RedoDbId id;

	public RedoDb() {
	}

	public RedoDb(RedoDbId id) {
		this.id = id;
	}

	public RedoDbId getId() {
		return this.id;
	}

	public void setId(RedoDbId id) {
		this.id = id;
	}

}
