package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * RedoDbId generated by hbm2java
 */
public class RedoDbId implements java.io.Serializable {

	private BigDecimal dbid;
	private String globalDbname;
	private String dbuname;
	private String version;
	private BigDecimal thread#;
	private BigDecimal resetlogsScnBas;
	private BigDecimal resetlogsScnWrp;
	private BigDecimal resetlogsTime;
	private BigDecimal presetlogsScnBas;
	private BigDecimal presetlogsScnWrp;
	private BigDecimal presetlogsTime;
	private BigDecimal seqnoRcvCur;
	private BigDecimal seqnoRcvLo;
	private BigDecimal seqnoRcvHi;
	private BigDecimal seqnoDoneCur;
	private BigDecimal seqnoDoneLo;
	private BigDecimal seqnoDoneHi;
	private BigDecimal gapSeqno;
	private BigDecimal gapRet;
	private BigDecimal gapDone;
	private BigDecimal applySeqno;
	private BigDecimal applyDone;
	private BigDecimal purgeDone;
	private BigDecimal hasChild;
	private BigDecimal error1;
	private BigDecimal status;
	private Date createDate;
	private BigDecimal ts1;
	private BigDecimal ts2;
	private BigDecimal gapNextScn;
	private BigDecimal gapNextTime;
	private BigDecimal curscnTime;
	private BigDecimal resetlogsScn;
	private BigDecimal presetlogsScn;
	private BigDecimal gapRet2;
	private BigDecimal curlog;
	private BigDecimal endian;
	private BigDecimal enqidx;
	private BigDecimal spare4;
	private Date spare5;
	private String spare6;
	private String spare7;
	private BigDecimal ts3;
	private BigDecimal curblkno;
	private BigDecimal spare8;
	private BigDecimal spare9;
	private BigDecimal spare10;
	private BigDecimal spare11;
	private BigDecimal spare12;

	public RedoDbId() {
	}

	public RedoDbId(BigDecimal dbid, BigDecimal thread#, BigDecimal resetlogsTime, BigDecimal presetlogsTime, BigDecimal resetlogsScn, BigDecimal presetlogsScn) {
        this.dbid = dbid;
        this.thread# = thread#;
        this.resetlogsTime = resetlogsTime;
        this.presetlogsTime = presetlogsTime;
        this.resetlogsScn = resetlogsScn;
        this.presetlogsScn = presetlogsScn;
    }

	public RedoDbId(BigDecimal dbid, String globalDbname, String dbuname, String version, BigDecimal thread#, BigDecimal resetlogsScnBas, BigDecimal resetlogsScnWrp, BigDecimal resetlogsTime, BigDecimal presetlogsScnBas, BigDecimal presetlogsScnWrp, BigDecimal presetlogsTime, BigDecimal seqnoRcvCur, BigDecimal seqnoRcvLo, BigDecimal seqnoRcvHi, BigDecimal seqnoDoneCur, BigDecimal seqnoDoneLo, BigDecimal seqnoDoneHi, BigDecimal gapSeqno, BigDecimal gapRet, BigDecimal gapDone, BigDecimal applySeqno, BigDecimal applyDone, BigDecimal purgeDone, BigDecimal hasChild, BigDecimal error1, BigDecimal status, Date createDate, BigDecimal ts1, BigDecimal ts2, BigDecimal gapNextScn, BigDecimal gapNextTime, BigDecimal curscnTime, BigDecimal resetlogsScn, BigDecimal presetlogsScn, BigDecimal gapRet2, BigDecimal curlog, BigDecimal endian, BigDecimal enqidx, BigDecimal spare4, Date spare5, String spare6, String spare7, BigDecimal ts3, BigDecimal curblkno, BigDecimal spare8, BigDecimal spare9, BigDecimal spare10, BigDecimal spare11, BigDecimal spare12) {
       this.dbid = dbid;
       this.globalDbname = globalDbname;
       this.dbuname = dbuname;
       this.version = version;
       this.thread# = thread#;
       this.resetlogsScnBas = resetlogsScnBas;
       this.resetlogsScnWrp = resetlogsScnWrp;
       this.resetlogsTime = resetlogsTime;
       this.presetlogsScnBas = presetlogsScnBas;
       this.presetlogsScnWrp = presetlogsScnWrp;
       this.presetlogsTime = presetlogsTime;
       this.seqnoRcvCur = seqnoRcvCur;
       this.seqnoRcvLo = seqnoRcvLo;
       this.seqnoRcvHi = seqnoRcvHi;
       this.seqnoDoneCur = seqnoDoneCur;
       this.seqnoDoneLo = seqnoDoneLo;
       this.seqnoDoneHi = seqnoDoneHi;
       this.gapSeqno = gapSeqno;
       this.gapRet = gapRet;
       this.gapDone = gapDone;
       this.applySeqno = applySeqno;
       this.applyDone = applyDone;
       this.purgeDone = purgeDone;
       this.hasChild = hasChild;
       this.error1 = error1;
       this.status = status;
       this.createDate = createDate;
       this.ts1 = ts1;
       this.ts2 = ts2;
       this.gapNextScn = gapNextScn;
       this.gapNextTime = gapNextTime;
       this.curscnTime = curscnTime;
       this.resetlogsScn = resetlogsScn;
       this.presetlogsScn = presetlogsScn;
       this.gapRet2 = gapRet2;
       this.curlog = curlog;
       this.endian = endian;
       this.enqidx = enqidx;
       this.spare4 = spare4;
       this.spare5 = spare5;
       this.spare6 = spare6;
       this.spare7 = spare7;
       this.ts3 = ts3;
       this.curblkno = curblkno;
       this.spare8 = spare8;
       this.spare9 = spare9;
       this.spare10 = spare10;
       this.spare11 = spare11;
       this.spare12 = spare12;
    }

	public BigDecimal getDbid() {
		return this.dbid;
	}

	public void setDbid(BigDecimal dbid) {
		this.dbid = dbid;
	}

	public String getGlobalDbname() {
		return this.globalDbname;
	}

	public void setGlobalDbname(String globalDbname) {
		this.globalDbname = globalDbname;
	}

	public String getDbuname() {
		return this.dbuname;
	}

	public void setDbuname(String dbuname) {
		this.dbuname = dbuname;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public BigDecimal getThread#()
	{
        return this.thread#;
    }

	public void setThread#(
	BigDecimal thread#)
	{
        this.thread# = thread#;
    }

	public BigDecimal getResetlogsScnBas() {
		return this.resetlogsScnBas;
	}

	public void setResetlogsScnBas(BigDecimal resetlogsScnBas) {
		this.resetlogsScnBas = resetlogsScnBas;
	}

	public BigDecimal getResetlogsScnWrp() {
		return this.resetlogsScnWrp;
	}

	public void setResetlogsScnWrp(BigDecimal resetlogsScnWrp) {
		this.resetlogsScnWrp = resetlogsScnWrp;
	}

	public BigDecimal getResetlogsTime() {
		return this.resetlogsTime;
	}

	public void setResetlogsTime(BigDecimal resetlogsTime) {
		this.resetlogsTime = resetlogsTime;
	}

	public BigDecimal getPresetlogsScnBas() {
		return this.presetlogsScnBas;
	}

	public void setPresetlogsScnBas(BigDecimal presetlogsScnBas) {
		this.presetlogsScnBas = presetlogsScnBas;
	}

	public BigDecimal getPresetlogsScnWrp() {
		return this.presetlogsScnWrp;
	}

	public void setPresetlogsScnWrp(BigDecimal presetlogsScnWrp) {
		this.presetlogsScnWrp = presetlogsScnWrp;
	}

	public BigDecimal getPresetlogsTime() {
		return this.presetlogsTime;
	}

	public void setPresetlogsTime(BigDecimal presetlogsTime) {
		this.presetlogsTime = presetlogsTime;
	}

	public BigDecimal getSeqnoRcvCur() {
		return this.seqnoRcvCur;
	}

	public void setSeqnoRcvCur(BigDecimal seqnoRcvCur) {
		this.seqnoRcvCur = seqnoRcvCur;
	}

	public BigDecimal getSeqnoRcvLo() {
		return this.seqnoRcvLo;
	}

	public void setSeqnoRcvLo(BigDecimal seqnoRcvLo) {
		this.seqnoRcvLo = seqnoRcvLo;
	}

	public BigDecimal getSeqnoRcvHi() {
		return this.seqnoRcvHi;
	}

	public void setSeqnoRcvHi(BigDecimal seqnoRcvHi) {
		this.seqnoRcvHi = seqnoRcvHi;
	}

	public BigDecimal getSeqnoDoneCur() {
		return this.seqnoDoneCur;
	}

	public void setSeqnoDoneCur(BigDecimal seqnoDoneCur) {
		this.seqnoDoneCur = seqnoDoneCur;
	}

	public BigDecimal getSeqnoDoneLo() {
		return this.seqnoDoneLo;
	}

	public void setSeqnoDoneLo(BigDecimal seqnoDoneLo) {
		this.seqnoDoneLo = seqnoDoneLo;
	}

	public BigDecimal getSeqnoDoneHi() {
		return this.seqnoDoneHi;
	}

	public void setSeqnoDoneHi(BigDecimal seqnoDoneHi) {
		this.seqnoDoneHi = seqnoDoneHi;
	}

	public BigDecimal getGapSeqno() {
		return this.gapSeqno;
	}

	public void setGapSeqno(BigDecimal gapSeqno) {
		this.gapSeqno = gapSeqno;
	}

	public BigDecimal getGapRet() {
		return this.gapRet;
	}

	public void setGapRet(BigDecimal gapRet) {
		this.gapRet = gapRet;
	}

	public BigDecimal getGapDone() {
		return this.gapDone;
	}

	public void setGapDone(BigDecimal gapDone) {
		this.gapDone = gapDone;
	}

	public BigDecimal getApplySeqno() {
		return this.applySeqno;
	}

	public void setApplySeqno(BigDecimal applySeqno) {
		this.applySeqno = applySeqno;
	}

	public BigDecimal getApplyDone() {
		return this.applyDone;
	}

	public void setApplyDone(BigDecimal applyDone) {
		this.applyDone = applyDone;
	}

	public BigDecimal getPurgeDone() {
		return this.purgeDone;
	}

	public void setPurgeDone(BigDecimal purgeDone) {
		this.purgeDone = purgeDone;
	}

	public BigDecimal getHasChild() {
		return this.hasChild;
	}

	public void setHasChild(BigDecimal hasChild) {
		this.hasChild = hasChild;
	}

	public BigDecimal getError1() {
		return this.error1;
	}

	public void setError1(BigDecimal error1) {
		this.error1 = error1;
	}

	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public BigDecimal getTs1() {
		return this.ts1;
	}

	public void setTs1(BigDecimal ts1) {
		this.ts1 = ts1;
	}

	public BigDecimal getTs2() {
		return this.ts2;
	}

	public void setTs2(BigDecimal ts2) {
		this.ts2 = ts2;
	}

	public BigDecimal getGapNextScn() {
		return this.gapNextScn;
	}

	public void setGapNextScn(BigDecimal gapNextScn) {
		this.gapNextScn = gapNextScn;
	}

	public BigDecimal getGapNextTime() {
		return this.gapNextTime;
	}

	public void setGapNextTime(BigDecimal gapNextTime) {
		this.gapNextTime = gapNextTime;
	}

	public BigDecimal getCurscnTime() {
		return this.curscnTime;
	}

	public void setCurscnTime(BigDecimal curscnTime) {
		this.curscnTime = curscnTime;
	}

	public BigDecimal getResetlogsScn() {
		return this.resetlogsScn;
	}

	public void setResetlogsScn(BigDecimal resetlogsScn) {
		this.resetlogsScn = resetlogsScn;
	}

	public BigDecimal getPresetlogsScn() {
		return this.presetlogsScn;
	}

	public void setPresetlogsScn(BigDecimal presetlogsScn) {
		this.presetlogsScn = presetlogsScn;
	}

	public BigDecimal getGapRet2() {
		return this.gapRet2;
	}

	public void setGapRet2(BigDecimal gapRet2) {
		this.gapRet2 = gapRet2;
	}

	public BigDecimal getCurlog() {
		return this.curlog;
	}

	public void setCurlog(BigDecimal curlog) {
		this.curlog = curlog;
	}

	public BigDecimal getEndian() {
		return this.endian;
	}

	public void setEndian(BigDecimal endian) {
		this.endian = endian;
	}

	public BigDecimal getEnqidx() {
		return this.enqidx;
	}

	public void setEnqidx(BigDecimal enqidx) {
		this.enqidx = enqidx;
	}

	public BigDecimal getSpare4() {
		return this.spare4;
	}

	public void setSpare4(BigDecimal spare4) {
		this.spare4 = spare4;
	}

	public Date getSpare5() {
		return this.spare5;
	}

	public void setSpare5(Date spare5) {
		this.spare5 = spare5;
	}

	public String getSpare6() {
		return this.spare6;
	}

	public void setSpare6(String spare6) {
		this.spare6 = spare6;
	}

	public String getSpare7() {
		return this.spare7;
	}

	public void setSpare7(String spare7) {
		this.spare7 = spare7;
	}

	public BigDecimal getTs3() {
		return this.ts3;
	}

	public void setTs3(BigDecimal ts3) {
		this.ts3 = ts3;
	}

	public BigDecimal getCurblkno() {
		return this.curblkno;
	}

	public void setCurblkno(BigDecimal curblkno) {
		this.curblkno = curblkno;
	}

	public BigDecimal getSpare8() {
		return this.spare8;
	}

	public void setSpare8(BigDecimal spare8) {
		this.spare8 = spare8;
	}

	public BigDecimal getSpare9() {
		return this.spare9;
	}

	public void setSpare9(BigDecimal spare9) {
		this.spare9 = spare9;
	}

	public BigDecimal getSpare10() {
		return this.spare10;
	}

	public void setSpare10(BigDecimal spare10) {
		this.spare10 = spare10;
	}

	public BigDecimal getSpare11() {
		return this.spare11;
	}

	public void setSpare11(BigDecimal spare11) {
		this.spare11 = spare11;
	}

	public BigDecimal getSpare12() {
		return this.spare12;
	}

	public void setSpare12(BigDecimal spare12) {
		this.spare12 = spare12;
	}

	public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RedoDbId) ) return false;
		 RedoDbId castOther = ( RedoDbId ) other; 
         
		 return ( (this.getDbid()==castOther.getDbid()) || ( this.getDbid()!=null && castOther.getDbid()!=null && this.getDbid().equals(castOther.getDbid()) ) )
 && ( (this.getGlobalDbname()==castOther.getGlobalDbname()) || ( this.getGlobalDbname()!=null && castOther.getGlobalDbname()!=null && this.getGlobalDbname().equals(castOther.getGlobalDbname()) ) )
 && ( (this.getDbuname()==castOther.getDbuname()) || ( this.getDbuname()!=null && castOther.getDbuname()!=null && this.getDbuname().equals(castOther.getDbuname()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getThread#()==castOther.getThread#()) || ( this.getThread#()!=null && castOther.getThread#()!=null && this.getThread#().equals(castOther.getThread#()) ) )
 && ( (this.getResetlogsScnBas()==castOther.getResetlogsScnBas()) || ( this.getResetlogsScnBas()!=null && castOther.getResetlogsScnBas()!=null && this.getResetlogsScnBas().equals(castOther.getResetlogsScnBas()) ) )
 && ( (this.getResetlogsScnWrp()==castOther.getResetlogsScnWrp()) || ( this.getResetlogsScnWrp()!=null && castOther.getResetlogsScnWrp()!=null && this.getResetlogsScnWrp().equals(castOther.getResetlogsScnWrp()) ) )
 && ( (this.getResetlogsTime()==castOther.getResetlogsTime()) || ( this.getResetlogsTime()!=null && castOther.getResetlogsTime()!=null && this.getResetlogsTime().equals(castOther.getResetlogsTime()) ) )
 && ( (this.getPresetlogsScnBas()==castOther.getPresetlogsScnBas()) || ( this.getPresetlogsScnBas()!=null && castOther.getPresetlogsScnBas()!=null && this.getPresetlogsScnBas().equals(castOther.getPresetlogsScnBas()) ) )
 && ( (this.getPresetlogsScnWrp()==castOther.getPresetlogsScnWrp()) || ( this.getPresetlogsScnWrp()!=null && castOther.getPresetlogsScnWrp()!=null && this.getPresetlogsScnWrp().equals(castOther.getPresetlogsScnWrp()) ) )
 && ( (this.getPresetlogsTime()==castOther.getPresetlogsTime()) || ( this.getPresetlogsTime()!=null && castOther.getPresetlogsTime()!=null && this.getPresetlogsTime().equals(castOther.getPresetlogsTime()) ) )
 && ( (this.getSeqnoRcvCur()==castOther.getSeqnoRcvCur()) || ( this.getSeqnoRcvCur()!=null && castOther.getSeqnoRcvCur()!=null && this.getSeqnoRcvCur().equals(castOther.getSeqnoRcvCur()) ) )
 && ( (this.getSeqnoRcvLo()==castOther.getSeqnoRcvLo()) || ( this.getSeqnoRcvLo()!=null && castOther.getSeqnoRcvLo()!=null && this.getSeqnoRcvLo().equals(castOther.getSeqnoRcvLo()) ) )
 && ( (this.getSeqnoRcvHi()==castOther.getSeqnoRcvHi()) || ( this.getSeqnoRcvHi()!=null && castOther.getSeqnoRcvHi()!=null && this.getSeqnoRcvHi().equals(castOther.getSeqnoRcvHi()) ) )
 && ( (this.getSeqnoDoneCur()==castOther.getSeqnoDoneCur()) || ( this.getSeqnoDoneCur()!=null && castOther.getSeqnoDoneCur()!=null && this.getSeqnoDoneCur().equals(castOther.getSeqnoDoneCur()) ) )
 && ( (this.getSeqnoDoneLo()==castOther.getSeqnoDoneLo()) || ( this.getSeqnoDoneLo()!=null && castOther.getSeqnoDoneLo()!=null && this.getSeqnoDoneLo().equals(castOther.getSeqnoDoneLo()) ) )
 && ( (this.getSeqnoDoneHi()==castOther.getSeqnoDoneHi()) || ( this.getSeqnoDoneHi()!=null && castOther.getSeqnoDoneHi()!=null && this.getSeqnoDoneHi().equals(castOther.getSeqnoDoneHi()) ) )
 && ( (this.getGapSeqno()==castOther.getGapSeqno()) || ( this.getGapSeqno()!=null && castOther.getGapSeqno()!=null && this.getGapSeqno().equals(castOther.getGapSeqno()) ) )
 && ( (this.getGapRet()==castOther.getGapRet()) || ( this.getGapRet()!=null && castOther.getGapRet()!=null && this.getGapRet().equals(castOther.getGapRet()) ) )
 && ( (this.getGapDone()==castOther.getGapDone()) || ( this.getGapDone()!=null && castOther.getGapDone()!=null && this.getGapDone().equals(castOther.getGapDone()) ) )
 && ( (this.getApplySeqno()==castOther.getApplySeqno()) || ( this.getApplySeqno()!=null && castOther.getApplySeqno()!=null && this.getApplySeqno().equals(castOther.getApplySeqno()) ) )
 && ( (this.getApplyDone()==castOther.getApplyDone()) || ( this.getApplyDone()!=null && castOther.getApplyDone()!=null && this.getApplyDone().equals(castOther.getApplyDone()) ) )
 && ( (this.getPurgeDone()==castOther.getPurgeDone()) || ( this.getPurgeDone()!=null && castOther.getPurgeDone()!=null && this.getPurgeDone().equals(castOther.getPurgeDone()) ) )
 && ( (this.getHasChild()==castOther.getHasChild()) || ( this.getHasChild()!=null && castOther.getHasChild()!=null && this.getHasChild().equals(castOther.getHasChild()) ) )
 && ( (this.getError1()==castOther.getError1()) || ( this.getError1()!=null && castOther.getError1()!=null && this.getError1().equals(castOther.getError1()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getCreateDate()==castOther.getCreateDate()) || ( this.getCreateDate()!=null && castOther.getCreateDate()!=null && this.getCreateDate().equals(castOther.getCreateDate()) ) )
 && ( (this.getTs1()==castOther.getTs1()) || ( this.getTs1()!=null && castOther.getTs1()!=null && this.getTs1().equals(castOther.getTs1()) ) )
 && ( (this.getTs2()==castOther.getTs2()) || ( this.getTs2()!=null && castOther.getTs2()!=null && this.getTs2().equals(castOther.getTs2()) ) )
 && ( (this.getGapNextScn()==castOther.getGapNextScn()) || ( this.getGapNextScn()!=null && castOther.getGapNextScn()!=null && this.getGapNextScn().equals(castOther.getGapNextScn()) ) )
 && ( (this.getGapNextTime()==castOther.getGapNextTime()) || ( this.getGapNextTime()!=null && castOther.getGapNextTime()!=null && this.getGapNextTime().equals(castOther.getGapNextTime()) ) )
 && ( (this.getCurscnTime()==castOther.getCurscnTime()) || ( this.getCurscnTime()!=null && castOther.getCurscnTime()!=null && this.getCurscnTime().equals(castOther.getCurscnTime()) ) )
 && ( (this.getResetlogsScn()==castOther.getResetlogsScn()) || ( this.getResetlogsScn()!=null && castOther.getResetlogsScn()!=null && this.getResetlogsScn().equals(castOther.getResetlogsScn()) ) )
 && ( (this.getPresetlogsScn()==castOther.getPresetlogsScn()) || ( this.getPresetlogsScn()!=null && castOther.getPresetlogsScn()!=null && this.getPresetlogsScn().equals(castOther.getPresetlogsScn()) ) )
 && ( (this.getGapRet2()==castOther.getGapRet2()) || ( this.getGapRet2()!=null && castOther.getGapRet2()!=null && this.getGapRet2().equals(castOther.getGapRet2()) ) )
 && ( (this.getCurlog()==castOther.getCurlog()) || ( this.getCurlog()!=null && castOther.getCurlog()!=null && this.getCurlog().equals(castOther.getCurlog()) ) )
 && ( (this.getEndian()==castOther.getEndian()) || ( this.getEndian()!=null && castOther.getEndian()!=null && this.getEndian().equals(castOther.getEndian()) ) )
 && ( (this.getEnqidx()==castOther.getEnqidx()) || ( this.getEnqidx()!=null && castOther.getEnqidx()!=null && this.getEnqidx().equals(castOther.getEnqidx()) ) )
 && ( (this.getSpare4()==castOther.getSpare4()) || ( this.getSpare4()!=null && castOther.getSpare4()!=null && this.getSpare4().equals(castOther.getSpare4()) ) )
 && ( (this.getSpare5()==castOther.getSpare5()) || ( this.getSpare5()!=null && castOther.getSpare5()!=null && this.getSpare5().equals(castOther.getSpare5()) ) )
 && ( (this.getSpare6()==castOther.getSpare6()) || ( this.getSpare6()!=null && castOther.getSpare6()!=null && this.getSpare6().equals(castOther.getSpare6()) ) )
 && ( (this.getSpare7()==castOther.getSpare7()) || ( this.getSpare7()!=null && castOther.getSpare7()!=null && this.getSpare7().equals(castOther.getSpare7()) ) )
 && ( (this.getTs3()==castOther.getTs3()) || ( this.getTs3()!=null && castOther.getTs3()!=null && this.getTs3().equals(castOther.getTs3()) ) )
 && ( (this.getCurblkno()==castOther.getCurblkno()) || ( this.getCurblkno()!=null && castOther.getCurblkno()!=null && this.getCurblkno().equals(castOther.getCurblkno()) ) )
 && ( (this.getSpare8()==castOther.getSpare8()) || ( this.getSpare8()!=null && castOther.getSpare8()!=null && this.getSpare8().equals(castOther.getSpare8()) ) )
 && ( (this.getSpare9()==castOther.getSpare9()) || ( this.getSpare9()!=null && castOther.getSpare9()!=null && this.getSpare9().equals(castOther.getSpare9()) ) )
 && ( (this.getSpare10()==castOther.getSpare10()) || ( this.getSpare10()!=null && castOther.getSpare10()!=null && this.getSpare10().equals(castOther.getSpare10()) ) )
 && ( (this.getSpare11()==castOther.getSpare11()) || ( this.getSpare11()!=null && castOther.getSpare11()!=null && this.getSpare11().equals(castOther.getSpare11()) ) )
 && ( (this.getSpare12()==castOther.getSpare12()) || ( this.getSpare12()!=null && castOther.getSpare12()!=null && this.getSpare12().equals(castOther.getSpare12()) ) );
   }

	public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDbid() == null ? 0 : this.getDbid().hashCode() );
         result = 37 * result + ( getGlobalDbname() == null ? 0 : this.getGlobalDbname().hashCode() );
         result = 37 * result + ( getDbuname() == null ? 0 : this.getDbuname().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getThread#() == null ? 0 : this.getThread#().hashCode() );
         result = 37 * result + ( getResetlogsScnBas() == null ? 0 : this.getResetlogsScnBas().hashCode() );
         result = 37 * result + ( getResetlogsScnWrp() == null ? 0 : this.getResetlogsScnWrp().hashCode() );
         result = 37 * result + ( getResetlogsTime() == null ? 0 : this.getResetlogsTime().hashCode() );
         result = 37 * result + ( getPresetlogsScnBas() == null ? 0 : this.getPresetlogsScnBas().hashCode() );
         result = 37 * result + ( getPresetlogsScnWrp() == null ? 0 : this.getPresetlogsScnWrp().hashCode() );
         result = 37 * result + ( getPresetlogsTime() == null ? 0 : this.getPresetlogsTime().hashCode() );
         result = 37 * result + ( getSeqnoRcvCur() == null ? 0 : this.getSeqnoRcvCur().hashCode() );
         result = 37 * result + ( getSeqnoRcvLo() == null ? 0 : this.getSeqnoRcvLo().hashCode() );
         result = 37 * result + ( getSeqnoRcvHi() == null ? 0 : this.getSeqnoRcvHi().hashCode() );
         result = 37 * result + ( getSeqnoDoneCur() == null ? 0 : this.getSeqnoDoneCur().hashCode() );
         result = 37 * result + ( getSeqnoDoneLo() == null ? 0 : this.getSeqnoDoneLo().hashCode() );
         result = 37 * result + ( getSeqnoDoneHi() == null ? 0 : this.getSeqnoDoneHi().hashCode() );
         result = 37 * result + ( getGapSeqno() == null ? 0 : this.getGapSeqno().hashCode() );
         result = 37 * result + ( getGapRet() == null ? 0 : this.getGapRet().hashCode() );
         result = 37 * result + ( getGapDone() == null ? 0 : this.getGapDone().hashCode() );
         result = 37 * result + ( getApplySeqno() == null ? 0 : this.getApplySeqno().hashCode() );
         result = 37 * result + ( getApplyDone() == null ? 0 : this.getApplyDone().hashCode() );
         result = 37 * result + ( getPurgeDone() == null ? 0 : this.getPurgeDone().hashCode() );
         result = 37 * result + ( getHasChild() == null ? 0 : this.getHasChild().hashCode() );
         result = 37 * result + ( getError1() == null ? 0 : this.getError1().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getCreateDate() == null ? 0 : this.getCreateDate().hashCode() );
         result = 37 * result + ( getTs1() == null ? 0 : this.getTs1().hashCode() );
         result = 37 * result + ( getTs2() == null ? 0 : this.getTs2().hashCode() );
         result = 37 * result + ( getGapNextScn() == null ? 0 : this.getGapNextScn().hashCode() );
         result = 37 * result + ( getGapNextTime() == null ? 0 : this.getGapNextTime().hashCode() );
         result = 37 * result + ( getCurscnTime() == null ? 0 : this.getCurscnTime().hashCode() );
         result = 37 * result + ( getResetlogsScn() == null ? 0 : this.getResetlogsScn().hashCode() );
         result = 37 * result + ( getPresetlogsScn() == null ? 0 : this.getPresetlogsScn().hashCode() );
         result = 37 * result + ( getGapRet2() == null ? 0 : this.getGapRet2().hashCode() );
         result = 37 * result + ( getCurlog() == null ? 0 : this.getCurlog().hashCode() );
         result = 37 * result + ( getEndian() == null ? 0 : this.getEndian().hashCode() );
         result = 37 * result + ( getEnqidx() == null ? 0 : this.getEnqidx().hashCode() );
         result = 37 * result + ( getSpare4() == null ? 0 : this.getSpare4().hashCode() );
         result = 37 * result + ( getSpare5() == null ? 0 : this.getSpare5().hashCode() );
         result = 37 * result + ( getSpare6() == null ? 0 : this.getSpare6().hashCode() );
         result = 37 * result + ( getSpare7() == null ? 0 : this.getSpare7().hashCode() );
         result = 37 * result + ( getTs3() == null ? 0 : this.getTs3().hashCode() );
         result = 37 * result + ( getCurblkno() == null ? 0 : this.getCurblkno().hashCode() );
         result = 37 * result + ( getSpare8() == null ? 0 : this.getSpare8().hashCode() );
         result = 37 * result + ( getSpare9() == null ? 0 : this.getSpare9().hashCode() );
         result = 37 * result + ( getSpare10() == null ? 0 : this.getSpare10().hashCode() );
         result = 37 * result + ( getSpare11() == null ? 0 : this.getSpare11().hashCode() );
         result = 37 * result + ( getSpare12() == null ? 0 : this.getSpare12().hashCode() );
         return result;
   }

}
