package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Rolling.statisticsId;

/**
 * Rolling.statistics generated by hbm2java
 */
public class Rolling.statistics  implements java.io.Serializable {


     private Rolling.statisticsId id;

    public Rolling.statistics() {
    }

    public Rolling.statistics(Rolling.statisticsId id) {
       this.id = id;
    }
   
    public Rolling.statisticsId getId() {
        return this.id;
    }
    
    public void setId(Rolling.statisticsId id) {
        this.id = id;
    }




}


