package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Rolling.databasesId generated by hbm2java
 */
public class Rolling.databasesId  implements java.io.Serializable {


     private BigDecimal rdbid;
     private BigDecimal attributes;
     private BigDecimal attributes2;
     private String dbun;
     private BigDecimal dbid;
     private BigDecimal prodRscn;
     private BigDecimal prodRid;
     private BigDecimal prodScn;
     private BigDecimal consRscn;
     private BigDecimal consRid;
     private BigDecimal consScn;
     private BigDecimal engineStatus;
     private String version;
     private BigDecimal redoSource;
     private Serializable updateTime;
     private BigDecimal revision;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private String spare3;

    public Rolling.databasesId() {
    }

    public Rolling.databasesId(BigDecimal rdbid, BigDecimal attributes, BigDecimal attributes2, String dbun, BigDecimal dbid, BigDecimal prodRscn, BigDecimal prodRid, BigDecimal prodScn, BigDecimal consRscn, BigDecimal consRid, BigDecimal consScn, BigDecimal engineStatus, String version, BigDecimal redoSource, Serializable updateTime, BigDecimal revision, BigDecimal spare1, BigDecimal spare2, String spare3) {
       this.rdbid = rdbid;
       this.attributes = attributes;
       this.attributes2 = attributes2;
       this.dbun = dbun;
       this.dbid = dbid;
       this.prodRscn = prodRscn;
       this.prodRid = prodRid;
       this.prodScn = prodScn;
       this.consRscn = consRscn;
       this.consRid = consRid;
       this.consScn = consScn;
       this.engineStatus = engineStatus;
       this.version = version;
       this.redoSource = redoSource;
       this.updateTime = updateTime;
       this.revision = revision;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.spare3 = spare3;
    }
   
    public BigDecimal getRdbid() {
        return this.rdbid;
    }
    
    public void setRdbid(BigDecimal rdbid) {
        this.rdbid = rdbid;
    }
    public BigDecimal getAttributes() {
        return this.attributes;
    }
    
    public void setAttributes(BigDecimal attributes) {
        this.attributes = attributes;
    }
    public BigDecimal getAttributes2() {
        return this.attributes2;
    }
    
    public void setAttributes2(BigDecimal attributes2) {
        this.attributes2 = attributes2;
    }
    public String getDbun() {
        return this.dbun;
    }
    
    public void setDbun(String dbun) {
        this.dbun = dbun;
    }
    public BigDecimal getDbid() {
        return this.dbid;
    }
    
    public void setDbid(BigDecimal dbid) {
        this.dbid = dbid;
    }
    public BigDecimal getProdRscn() {
        return this.prodRscn;
    }
    
    public void setProdRscn(BigDecimal prodRscn) {
        this.prodRscn = prodRscn;
    }
    public BigDecimal getProdRid() {
        return this.prodRid;
    }
    
    public void setProdRid(BigDecimal prodRid) {
        this.prodRid = prodRid;
    }
    public BigDecimal getProdScn() {
        return this.prodScn;
    }
    
    public void setProdScn(BigDecimal prodScn) {
        this.prodScn = prodScn;
    }
    public BigDecimal getConsRscn() {
        return this.consRscn;
    }
    
    public void setConsRscn(BigDecimal consRscn) {
        this.consRscn = consRscn;
    }
    public BigDecimal getConsRid() {
        return this.consRid;
    }
    
    public void setConsRid(BigDecimal consRid) {
        this.consRid = consRid;
    }
    public BigDecimal getConsScn() {
        return this.consScn;
    }
    
    public void setConsScn(BigDecimal consScn) {
        this.consScn = consScn;
    }
    public BigDecimal getEngineStatus() {
        return this.engineStatus;
    }
    
    public void setEngineStatus(BigDecimal engineStatus) {
        this.engineStatus = engineStatus;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public BigDecimal getRedoSource() {
        return this.redoSource;
    }
    
    public void setRedoSource(BigDecimal redoSource) {
        this.redoSource = redoSource;
    }
    public Serializable getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Serializable updateTime) {
        this.updateTime = updateTime;
    }
    public BigDecimal getRevision() {
        return this.revision;
    }
    
    public void setRevision(BigDecimal revision) {
        this.revision = revision;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public String getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(String spare3) {
        this.spare3 = spare3;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Rolling.databasesId) ) return false;
		 Rolling.databasesId castOther = ( Rolling.databasesId ) other; 
         
		 return ( (this.getRdbid()==castOther.getRdbid()) || ( this.getRdbid()!=null && castOther.getRdbid()!=null && this.getRdbid().equals(castOther.getRdbid()) ) )
 && ( (this.getAttributes()==castOther.getAttributes()) || ( this.getAttributes()!=null && castOther.getAttributes()!=null && this.getAttributes().equals(castOther.getAttributes()) ) )
 && ( (this.getAttributes2()==castOther.getAttributes2()) || ( this.getAttributes2()!=null && castOther.getAttributes2()!=null && this.getAttributes2().equals(castOther.getAttributes2()) ) )
 && ( (this.getDbun()==castOther.getDbun()) || ( this.getDbun()!=null && castOther.getDbun()!=null && this.getDbun().equals(castOther.getDbun()) ) )
 && ( (this.getDbid()==castOther.getDbid()) || ( this.getDbid()!=null && castOther.getDbid()!=null && this.getDbid().equals(castOther.getDbid()) ) )
 && ( (this.getProdRscn()==castOther.getProdRscn()) || ( this.getProdRscn()!=null && castOther.getProdRscn()!=null && this.getProdRscn().equals(castOther.getProdRscn()) ) )
 && ( (this.getProdRid()==castOther.getProdRid()) || ( this.getProdRid()!=null && castOther.getProdRid()!=null && this.getProdRid().equals(castOther.getProdRid()) ) )
 && ( (this.getProdScn()==castOther.getProdScn()) || ( this.getProdScn()!=null && castOther.getProdScn()!=null && this.getProdScn().equals(castOther.getProdScn()) ) )
 && ( (this.getConsRscn()==castOther.getConsRscn()) || ( this.getConsRscn()!=null && castOther.getConsRscn()!=null && this.getConsRscn().equals(castOther.getConsRscn()) ) )
 && ( (this.getConsRid()==castOther.getConsRid()) || ( this.getConsRid()!=null && castOther.getConsRid()!=null && this.getConsRid().equals(castOther.getConsRid()) ) )
 && ( (this.getConsScn()==castOther.getConsScn()) || ( this.getConsScn()!=null && castOther.getConsScn()!=null && this.getConsScn().equals(castOther.getConsScn()) ) )
 && ( (this.getEngineStatus()==castOther.getEngineStatus()) || ( this.getEngineStatus()!=null && castOther.getEngineStatus()!=null && this.getEngineStatus().equals(castOther.getEngineStatus()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getRedoSource()==castOther.getRedoSource()) || ( this.getRedoSource()!=null && castOther.getRedoSource()!=null && this.getRedoSource().equals(castOther.getRedoSource()) ) )
 && ( (this.getUpdateTime()==castOther.getUpdateTime()) || ( this.getUpdateTime()!=null && castOther.getUpdateTime()!=null && this.getUpdateTime().equals(castOther.getUpdateTime()) ) )
 && ( (this.getRevision()==castOther.getRevision()) || ( this.getRevision()!=null && castOther.getRevision()!=null && this.getRevision().equals(castOther.getRevision()) ) )
 && ( (this.getSpare1()==castOther.getSpare1()) || ( this.getSpare1()!=null && castOther.getSpare1()!=null && this.getSpare1().equals(castOther.getSpare1()) ) )
 && ( (this.getSpare2()==castOther.getSpare2()) || ( this.getSpare2()!=null && castOther.getSpare2()!=null && this.getSpare2().equals(castOther.getSpare2()) ) )
 && ( (this.getSpare3()==castOther.getSpare3()) || ( this.getSpare3()!=null && castOther.getSpare3()!=null && this.getSpare3().equals(castOther.getSpare3()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRdbid() == null ? 0 : this.getRdbid().hashCode() );
         result = 37 * result + ( getAttributes() == null ? 0 : this.getAttributes().hashCode() );
         result = 37 * result + ( getAttributes2() == null ? 0 : this.getAttributes2().hashCode() );
         result = 37 * result + ( getDbun() == null ? 0 : this.getDbun().hashCode() );
         result = 37 * result + ( getDbid() == null ? 0 : this.getDbid().hashCode() );
         result = 37 * result + ( getProdRscn() == null ? 0 : this.getProdRscn().hashCode() );
         result = 37 * result + ( getProdRid() == null ? 0 : this.getProdRid().hashCode() );
         result = 37 * result + ( getProdScn() == null ? 0 : this.getProdScn().hashCode() );
         result = 37 * result + ( getConsRscn() == null ? 0 : this.getConsRscn().hashCode() );
         result = 37 * result + ( getConsRid() == null ? 0 : this.getConsRid().hashCode() );
         result = 37 * result + ( getConsScn() == null ? 0 : this.getConsScn().hashCode() );
         result = 37 * result + ( getEngineStatus() == null ? 0 : this.getEngineStatus().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getRedoSource() == null ? 0 : this.getRedoSource().hashCode() );
         result = 37 * result + ( getUpdateTime() == null ? 0 : this.getUpdateTime().hashCode() );
         result = 37 * result + ( getRevision() == null ? 0 : this.getRevision().hashCode() );
         result = 37 * result + ( getSpare1() == null ? 0 : this.getSpare1().hashCode() );
         result = 37 * result + ( getSpare2() == null ? 0 : this.getSpare2().hashCode() );
         result = 37 * result + ( getSpare3() == null ? 0 : this.getSpare3().hashCode() );
         return result;
   }   


}


