package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Rolling.parametersId;

/**
 * Rolling.parameters generated by hbm2java
 */
public class Rolling.parameters  implements java.io.Serializable {


     private Rolling.parametersId id;

    public Rolling.parameters() {
    }

    public Rolling.parameters(Rolling.parametersId id) {
       this.id = id;
    }
   
    public Rolling.parametersId getId() {
        return this.id;
    }
    
    public void setId(Rolling.parametersId id) {
        this.id = id;
    }




}


