package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Rolling.statusId;

/**
 * Rolling.status generated by hbm2java
 */
public class Rolling.status  implements java.io.Serializable {


     private Rolling.statusId id;

    public Rolling.status() {
    }

    public Rolling.status(Rolling.statusId id) {
       this.id = id;
    }
   
    public Rolling.statusId getId() {
        return this.id;
    }
    
    public void setId(Rolling.statusId id) {
        this.id = id;
    }




}


