package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Rolling.eventsId;

/**
 * Rolling.events generated by hbm2java
 */
public class Rolling.events  implements java.io.Serializable {


     private Rolling.eventsId id;

    public Rolling.events() {
    }

    public Rolling.events(Rolling.eventsId id) {
       this.id = id;
    }
   
    public Rolling.eventsId getId() {
        return this.id;
    }
    
    public void setId(Rolling.eventsId id) {
        this.id = id;
    }




}


