package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Rolling.directivesId generated by hbm2java
 */
public class Rolling.directivesId  implements java.io.Serializable {


     private BigDecimal directid;
     private BigDecimal phase;
     private BigDecimal taskid;
     private String feature;
     private String description;
     private BigDecimal target;
     private String flags;
     private BigDecimal opcode;
     private String p1;
     private String p2;
     private String p3;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private String spare3;

    public Rolling.directivesId() {
    }

    public Rolling.directivesId(BigDecimal directid, BigDecimal phase, BigDecimal taskid, String feature, String description, BigDecimal target, String flags, BigDecimal opcode, String p1, String p2, String p3, BigDecimal spare1, BigDecimal spare2, String spare3) {
       this.directid = directid;
       this.phase = phase;
       this.taskid = taskid;
       this.feature = feature;
       this.description = description;
       this.target = target;
       this.flags = flags;
       this.opcode = opcode;
       this.p1 = p1;
       this.p2 = p2;
       this.p3 = p3;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.spare3 = spare3;
    }
   
    public BigDecimal getDirectid() {
        return this.directid;
    }
    
    public void setDirectid(BigDecimal directid) {
        this.directid = directid;
    }
    public BigDecimal getPhase() {
        return this.phase;
    }
    
    public void setPhase(BigDecimal phase) {
        this.phase = phase;
    }
    public BigDecimal getTaskid() {
        return this.taskid;
    }
    
    public void setTaskid(BigDecimal taskid) {
        this.taskid = taskid;
    }
    public String getFeature() {
        return this.feature;
    }
    
    public void setFeature(String feature) {
        this.feature = feature;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getTarget() {
        return this.target;
    }
    
    public void setTarget(BigDecimal target) {
        this.target = target;
    }
    public String getFlags() {
        return this.flags;
    }
    
    public void setFlags(String flags) {
        this.flags = flags;
    }
    public BigDecimal getOpcode() {
        return this.opcode;
    }
    
    public void setOpcode(BigDecimal opcode) {
        this.opcode = opcode;
    }
    public String getP1() {
        return this.p1;
    }
    
    public void setP1(String p1) {
        this.p1 = p1;
    }
    public String getP2() {
        return this.p2;
    }
    
    public void setP2(String p2) {
        this.p2 = p2;
    }
    public String getP3() {
        return this.p3;
    }
    
    public void setP3(String p3) {
        this.p3 = p3;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public String getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(String spare3) {
        this.spare3 = spare3;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Rolling.directivesId) ) return false;
		 Rolling.directivesId castOther = ( Rolling.directivesId ) other; 
         
		 return ( (this.getDirectid()==castOther.getDirectid()) || ( this.getDirectid()!=null && castOther.getDirectid()!=null && this.getDirectid().equals(castOther.getDirectid()) ) )
 && ( (this.getPhase()==castOther.getPhase()) || ( this.getPhase()!=null && castOther.getPhase()!=null && this.getPhase().equals(castOther.getPhase()) ) )
 && ( (this.getTaskid()==castOther.getTaskid()) || ( this.getTaskid()!=null && castOther.getTaskid()!=null && this.getTaskid().equals(castOther.getTaskid()) ) )
 && ( (this.getFeature()==castOther.getFeature()) || ( this.getFeature()!=null && castOther.getFeature()!=null && this.getFeature().equals(castOther.getFeature()) ) )
 && ( (this.getDescription()==castOther.getDescription()) || ( this.getDescription()!=null && castOther.getDescription()!=null && this.getDescription().equals(castOther.getDescription()) ) )
 && ( (this.getTarget()==castOther.getTarget()) || ( this.getTarget()!=null && castOther.getTarget()!=null && this.getTarget().equals(castOther.getTarget()) ) )
 && ( (this.getFlags()==castOther.getFlags()) || ( this.getFlags()!=null && castOther.getFlags()!=null && this.getFlags().equals(castOther.getFlags()) ) )
 && ( (this.getOpcode()==castOther.getOpcode()) || ( this.getOpcode()!=null && castOther.getOpcode()!=null && this.getOpcode().equals(castOther.getOpcode()) ) )
 && ( (this.getP1()==castOther.getP1()) || ( this.getP1()!=null && castOther.getP1()!=null && this.getP1().equals(castOther.getP1()) ) )
 && ( (this.getP2()==castOther.getP2()) || ( this.getP2()!=null && castOther.getP2()!=null && this.getP2().equals(castOther.getP2()) ) )
 && ( (this.getP3()==castOther.getP3()) || ( this.getP3()!=null && castOther.getP3()!=null && this.getP3().equals(castOther.getP3()) ) )
 && ( (this.getSpare1()==castOther.getSpare1()) || ( this.getSpare1()!=null && castOther.getSpare1()!=null && this.getSpare1().equals(castOther.getSpare1()) ) )
 && ( (this.getSpare2()==castOther.getSpare2()) || ( this.getSpare2()!=null && castOther.getSpare2()!=null && this.getSpare2().equals(castOther.getSpare2()) ) )
 && ( (this.getSpare3()==castOther.getSpare3()) || ( this.getSpare3()!=null && castOther.getSpare3()!=null && this.getSpare3().equals(castOther.getSpare3()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDirectid() == null ? 0 : this.getDirectid().hashCode() );
         result = 37 * result + ( getPhase() == null ? 0 : this.getPhase().hashCode() );
         result = 37 * result + ( getTaskid() == null ? 0 : this.getTaskid().hashCode() );
         result = 37 * result + ( getFeature() == null ? 0 : this.getFeature().hashCode() );
         result = 37 * result + ( getDescription() == null ? 0 : this.getDescription().hashCode() );
         result = 37 * result + ( getTarget() == null ? 0 : this.getTarget().hashCode() );
         result = 37 * result + ( getFlags() == null ? 0 : this.getFlags().hashCode() );
         result = 37 * result + ( getOpcode() == null ? 0 : this.getOpcode().hashCode() );
         result = 37 * result + ( getP1() == null ? 0 : this.getP1().hashCode() );
         result = 37 * result + ( getP2() == null ? 0 : this.getP2().hashCode() );
         result = 37 * result + ( getP3() == null ? 0 : this.getP3().hashCode() );
         result = 37 * result + ( getSpare1() == null ? 0 : this.getSpare1().hashCode() );
         result = 37 * result + ( getSpare2() == null ? 0 : this.getSpare2().hashCode() );
         result = 37 * result + ( getSpare3() == null ? 0 : this.getSpare3().hashCode() );
         return result;
   }   


}


