package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Rolling.statisticsId generated by hbm2java
 */
public class Rolling.statisticsId  implements java.io.Serializable {


     private BigDecimal statid;
     private BigDecimal rdbid;
     private BigDecimal attributes;
     private BigDecimal type;
     private String name;
     private String valuestr;
     private BigDecimal valuenum;
     private Serializable valuets;
     private Serializable valueint;
     private Serializable updateTime;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private String spare3;

    public Rolling.statisticsId() {
    }

    public Rolling.statisticsId(BigDecimal statid, BigDecimal rdbid, BigDecimal attributes, BigDecimal type, String name, String valuestr, BigDecimal valuenum, Serializable valuets, Serializable valueint, Serializable updateTime, BigDecimal spare1, BigDecimal spare2, String spare3) {
       this.statid = statid;
       this.rdbid = rdbid;
       this.attributes = attributes;
       this.type = type;
       this.name = name;
       this.valuestr = valuestr;
       this.valuenum = valuenum;
       this.valuets = valuets;
       this.valueint = valueint;
       this.updateTime = updateTime;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.spare3 = spare3;
    }
   
    public BigDecimal getStatid() {
        return this.statid;
    }
    
    public void setStatid(BigDecimal statid) {
        this.statid = statid;
    }
    public BigDecimal getRdbid() {
        return this.rdbid;
    }
    
    public void setRdbid(BigDecimal rdbid) {
        this.rdbid = rdbid;
    }
    public BigDecimal getAttributes() {
        return this.attributes;
    }
    
    public void setAttributes(BigDecimal attributes) {
        this.attributes = attributes;
    }
    public BigDecimal getType() {
        return this.type;
    }
    
    public void setType(BigDecimal type) {
        this.type = type;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getValuestr() {
        return this.valuestr;
    }
    
    public void setValuestr(String valuestr) {
        this.valuestr = valuestr;
    }
    public BigDecimal getValuenum() {
        return this.valuenum;
    }
    
    public void setValuenum(BigDecimal valuenum) {
        this.valuenum = valuenum;
    }
    public Serializable getValuets() {
        return this.valuets;
    }
    
    public void setValuets(Serializable valuets) {
        this.valuets = valuets;
    }
    public Serializable getValueint() {
        return this.valueint;
    }
    
    public void setValueint(Serializable valueint) {
        this.valueint = valueint;
    }
    public Serializable getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Serializable updateTime) {
        this.updateTime = updateTime;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public String getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(String spare3) {
        this.spare3 = spare3;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Rolling.statisticsId) ) return false;
		 Rolling.statisticsId castOther = ( Rolling.statisticsId ) other; 
         
		 return ( (this.getStatid()==castOther.getStatid()) || ( this.getStatid()!=null && castOther.getStatid()!=null && this.getStatid().equals(castOther.getStatid()) ) )
 && ( (this.getRdbid()==castOther.getRdbid()) || ( this.getRdbid()!=null && castOther.getRdbid()!=null && this.getRdbid().equals(castOther.getRdbid()) ) )
 && ( (this.getAttributes()==castOther.getAttributes()) || ( this.getAttributes()!=null && castOther.getAttributes()!=null && this.getAttributes().equals(castOther.getAttributes()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getValuestr()==castOther.getValuestr()) || ( this.getValuestr()!=null && castOther.getValuestr()!=null && this.getValuestr().equals(castOther.getValuestr()) ) )
 && ( (this.getValuenum()==castOther.getValuenum()) || ( this.getValuenum()!=null && castOther.getValuenum()!=null && this.getValuenum().equals(castOther.getValuenum()) ) )
 && ( (this.getValuets()==castOther.getValuets()) || ( this.getValuets()!=null && castOther.getValuets()!=null && this.getValuets().equals(castOther.getValuets()) ) )
 && ( (this.getValueint()==castOther.getValueint()) || ( this.getValueint()!=null && castOther.getValueint()!=null && this.getValueint().equals(castOther.getValueint()) ) )
 && ( (this.getUpdateTime()==castOther.getUpdateTime()) || ( this.getUpdateTime()!=null && castOther.getUpdateTime()!=null && this.getUpdateTime().equals(castOther.getUpdateTime()) ) )
 && ( (this.getSpare1()==castOther.getSpare1()) || ( this.getSpare1()!=null && castOther.getSpare1()!=null && this.getSpare1().equals(castOther.getSpare1()) ) )
 && ( (this.getSpare2()==castOther.getSpare2()) || ( this.getSpare2()!=null && castOther.getSpare2()!=null && this.getSpare2().equals(castOther.getSpare2()) ) )
 && ( (this.getSpare3()==castOther.getSpare3()) || ( this.getSpare3()!=null && castOther.getSpare3()!=null && this.getSpare3().equals(castOther.getSpare3()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getStatid() == null ? 0 : this.getStatid().hashCode() );
         result = 37 * result + ( getRdbid() == null ? 0 : this.getRdbid().hashCode() );
         result = 37 * result + ( getAttributes() == null ? 0 : this.getAttributes().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getValuestr() == null ? 0 : this.getValuestr().hashCode() );
         result = 37 * result + ( getValuenum() == null ? 0 : this.getValuenum().hashCode() );
         result = 37 * result + ( getValuets() == null ? 0 : this.getValuets().hashCode() );
         result = 37 * result + ( getValueint() == null ? 0 : this.getValueint().hashCode() );
         result = 37 * result + ( getUpdateTime() == null ? 0 : this.getUpdateTime().hashCode() );
         result = 37 * result + ( getSpare1() == null ? 0 : this.getSpare1().hashCode() );
         result = 37 * result + ( getSpare2() == null ? 0 : this.getSpare2().hashCode() );
         result = 37 * result + ( getSpare3() == null ? 0 : this.getSpare3().hashCode() );
         return result;
   }   


}


