package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1

/**
 * SchedulerProgramArgs generated by hbm2java
 */
public class SchedulerProgramArgs implements java.io.Serializable {

	private SchedulerProgramArgsId id;

	public SchedulerProgramArgs() {
	}

	public SchedulerProgramArgs(SchedulerProgramArgsId id) {
		this.id = id;
	}

	public SchedulerProgramArgsId getId() {
		return this.id;
	}

	public void setId(SchedulerProgramArgsId id) {
		this.id = id;
	}

}
