package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * SchedulerJobArgsId generated by hbm2java
 */
public class SchedulerJobArgsId implements java.io.Serializable {

	private String owner;
	private String jobName;
	private String argumentName;
	private BigDecimal argumentPosition;
	private String argumentType;
	private String value;
	private Serializable anydataValue;
	private String outArgument;

	public SchedulerJobArgsId() {
	}

	public SchedulerJobArgsId(String owner, String jobName, String argumentName, BigDecimal argumentPosition,
			String argumentType, String value, Serializable anydataValue, String outArgument) {
		this.owner = owner;
		this.jobName = jobName;
		this.argumentName = argumentName;
		this.argumentPosition = argumentPosition;
		this.argumentType = argumentType;
		this.value = value;
		this.anydataValue = anydataValue;
		this.outArgument = outArgument;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	public String getArgumentName() {
		return this.argumentName;
	}

	public void setArgumentName(String argumentName) {
		this.argumentName = argumentName;
	}

	public BigDecimal getArgumentPosition() {
		return this.argumentPosition;
	}

	public void setArgumentPosition(BigDecimal argumentPosition) {
		this.argumentPosition = argumentPosition;
	}

	public String getArgumentType() {
		return this.argumentType;
	}

	public void setArgumentType(String argumentType) {
		this.argumentType = argumentType;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Serializable getAnydataValue() {
		return this.anydataValue;
	}

	public void setAnydataValue(Serializable anydataValue) {
		this.anydataValue = anydataValue;
	}

	public String getOutArgument() {
		return this.outArgument;
	}

	public void setOutArgument(String outArgument) {
		this.outArgument = outArgument;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SchedulerJobArgsId))
			return false;
		SchedulerJobArgsId castOther = (SchedulerJobArgsId) other;

		return ((this.getOwner() == castOther.getOwner()) || (this.getOwner() != null && castOther.getOwner() != null
				&& this.getOwner().equals(castOther.getOwner())))
				&& ((this.getJobName() == castOther.getJobName()) || (this.getJobName() != null
						&& castOther.getJobName() != null && this.getJobName().equals(castOther.getJobName())))
				&& ((this.getArgumentName() == castOther.getArgumentName())
						|| (this.getArgumentName() != null && castOther.getArgumentName() != null
								&& this.getArgumentName().equals(castOther.getArgumentName())))
				&& ((this.getArgumentPosition() == castOther.getArgumentPosition())
						|| (this.getArgumentPosition() != null && castOther.getArgumentPosition() != null
								&& this.getArgumentPosition().equals(castOther.getArgumentPosition())))
				&& ((this.getArgumentType() == castOther.getArgumentType())
						|| (this.getArgumentType() != null && castOther.getArgumentType() != null
								&& this.getArgumentType().equals(castOther.getArgumentType())))
				&& ((this.getValue() == castOther.getValue()) || (this.getValue() != null
						&& castOther.getValue() != null && this.getValue().equals(castOther.getValue())))
				&& ((this.getAnydataValue() == castOther.getAnydataValue())
						|| (this.getAnydataValue() != null && castOther.getAnydataValue() != null
								&& this.getAnydataValue().equals(castOther.getAnydataValue())))
				&& ((this.getOutArgument() == castOther.getOutArgument())
						|| (this.getOutArgument() != null && castOther.getOutArgument() != null
								&& this.getOutArgument().equals(castOther.getOutArgument())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOwner() == null ? 0 : this.getOwner().hashCode());
		result = 37 * result + (getJobName() == null ? 0 : this.getJobName().hashCode());
		result = 37 * result + (getArgumentName() == null ? 0 : this.getArgumentName().hashCode());
		result = 37 * result + (getArgumentPosition() == null ? 0 : this.getArgumentPosition().hashCode());
		result = 37 * result + (getArgumentType() == null ? 0 : this.getArgumentType().hashCode());
		result = 37 * result + (getValue() == null ? 0 : this.getValue().hashCode());
		result = 37 * result + (getAnydataValue() == null ? 0 : this.getAnydataValue().hashCode());
		result = 37 * result + (getOutArgument() == null ? 0 : this.getOutArgument().hashCode());
		return result;
	}

}
