package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LogmnrRestartCkpt.Id generated by hbm2java
 */
public class LogmnrRestartCkpt.Id  implements java.io.Serializable {


     private BigDecimal session#;
     private BigDecimal ckptScn;
     private BigDecimal xidusn;
     private BigDecimal xidslt;
     private BigDecimal xidsqn;
     private BigDecimal pdbid;
     private BigDecimal sessionNum;
     private BigDecimal serialNum;

    public LogmnrRestartCkpt.Id() {
    }

    public LogmnrRestartCkpt.Id(BigDecimal session#, BigDecimal ckptScn, BigDecimal xidusn, BigDecimal xidslt, BigDecimal xidsqn, BigDecimal pdbid, BigDecimal sessionNum, BigDecimal serialNum) {
       this.session# = session#;
       this.ckptScn = ckptScn;
       this.xidusn = xidusn;
       this.xidslt = xidslt;
       this.xidsqn = xidsqn;
       this.pdbid = pdbid;
       this.sessionNum = sessionNum;
       this.serialNum = serialNum;
    }
   
    public BigDecimal getSession#() {
        return this.session#;
    }
    
    public void setSession#(BigDecimal session#) {
        this.session# = session#;
    }
    public BigDecimal getCkptScn() {
        return this.ckptScn;
    }
    
    public void setCkptScn(BigDecimal ckptScn) {
        this.ckptScn = ckptScn;
    }
    public BigDecimal getXidusn() {
        return this.xidusn;
    }
    
    public void setXidusn(BigDecimal xidusn) {
        this.xidusn = xidusn;
    }
    public BigDecimal getXidslt() {
        return this.xidslt;
    }
    
    public void setXidslt(BigDecimal xidslt) {
        this.xidslt = xidslt;
    }
    public BigDecimal getXidsqn() {
        return this.xidsqn;
    }
    
    public void setXidsqn(BigDecimal xidsqn) {
        this.xidsqn = xidsqn;
    }
    public BigDecimal getPdbid() {
        return this.pdbid;
    }
    
    public void setPdbid(BigDecimal pdbid) {
        this.pdbid = pdbid;
    }
    public BigDecimal getSessionNum() {
        return this.sessionNum;
    }
    
    public void setSessionNum(BigDecimal sessionNum) {
        this.sessionNum = sessionNum;
    }
    public BigDecimal getSerialNum() {
        return this.serialNum;
    }
    
    public void setSerialNum(BigDecimal serialNum) {
        this.serialNum = serialNum;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrRestartCkpt.Id) ) return false;
		 LogmnrRestartCkpt.Id castOther = ( LogmnrRestartCkpt.Id ) other; 
         
		 return ( (this.getSession#()==castOther.getSession#()) || ( this.getSession#()!=null && castOther.getSession#()!=null && this.getSession#().equals(castOther.getSession#()) ) )
 && ( (this.getCkptScn()==castOther.getCkptScn()) || ( this.getCkptScn()!=null && castOther.getCkptScn()!=null && this.getCkptScn().equals(castOther.getCkptScn()) ) )
 && ( (this.getXidusn()==castOther.getXidusn()) || ( this.getXidusn()!=null && castOther.getXidusn()!=null && this.getXidusn().equals(castOther.getXidusn()) ) )
 && ( (this.getXidslt()==castOther.getXidslt()) || ( this.getXidslt()!=null && castOther.getXidslt()!=null && this.getXidslt().equals(castOther.getXidslt()) ) )
 && ( (this.getXidsqn()==castOther.getXidsqn()) || ( this.getXidsqn()!=null && castOther.getXidsqn()!=null && this.getXidsqn().equals(castOther.getXidsqn()) ) )
 && ( (this.getPdbid()==castOther.getPdbid()) || ( this.getPdbid()!=null && castOther.getPdbid()!=null && this.getPdbid().equals(castOther.getPdbid()) ) )
 && ( (this.getSessionNum()==castOther.getSessionNum()) || ( this.getSessionNum()!=null && castOther.getSessionNum()!=null && this.getSessionNum().equals(castOther.getSessionNum()) ) )
 && ( (this.getSerialNum()==castOther.getSerialNum()) || ( this.getSerialNum()!=null && castOther.getSerialNum()!=null && this.getSerialNum().equals(castOther.getSerialNum()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSession#() == null ? 0 : this.getSession#().hashCode() );
         result = 37 * result + ( getCkptScn() == null ? 0 : this.getCkptScn().hashCode() );
         result = 37 * result + ( getXidusn() == null ? 0 : this.getXidusn().hashCode() );
         result = 37 * result + ( getXidslt() == null ? 0 : this.getXidslt().hashCode() );
         result = 37 * result + ( getXidsqn() == null ? 0 : this.getXidsqn().hashCode() );
         result = 37 * result + ( getPdbid() == null ? 0 : this.getPdbid().hashCode() );
         result = 37 * result + ( getSessionNum() == null ? 0 : this.getSessionNum().hashCode() );
         result = 37 * result + ( getSerialNum() == null ? 0 : this.getSerialNum().hashCode() );
         return result;
   }   


}


