package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrRestartCkpt.Id;
import java.math.BigDecimal;
import java.sql.Blob;

/**
 * LogmnrRestartCkpt. generated by hbm2java
 */
public class LogmnrRestartCkpt.  implements java.io.Serializable {


     private LogmnrRestartCkpt.Id id;
     private BigDecimal valid;
     private Blob ckptInfo;
     private BigDecimal flag;
     private BigDecimal offset;
     private Blob clientData;
     private BigDecimal spare1;
     private BigDecimal spare2;

    public LogmnrRestartCkpt.() {
    }

	
    public LogmnrRestartCkpt.(LogmnrRestartCkpt.Id id) {
        this.id = id;
    }
    public LogmnrRestartCkpt.(LogmnrRestartCkpt.Id id, BigDecimal valid, Blob ckptInfo, BigDecimal flag, BigDecimal offset, Blob clientData, BigDecimal spare1, BigDecimal spare2) {
       this.id = id;
       this.valid = valid;
       this.ckptInfo = ckptInfo;
       this.flag = flag;
       this.offset = offset;
       this.clientData = clientData;
       this.spare1 = spare1;
       this.spare2 = spare2;
    }
   
    public LogmnrRestartCkpt.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrRestartCkpt.Id id) {
        this.id = id;
    }
    public BigDecimal getValid() {
        return this.valid;
    }
    
    public void setValid(BigDecimal valid) {
        this.valid = valid;
    }
    public Blob getCkptInfo() {
        return this.ckptInfo;
    }
    
    public void setCkptInfo(Blob ckptInfo) {
        this.ckptInfo = ckptInfo;
    }
    public BigDecimal getFlag() {
        return this.flag;
    }
    
    public void setFlag(BigDecimal flag) {
        this.flag = flag;
    }
    public BigDecimal getOffset() {
        return this.offset;
    }
    
    public void setOffset(BigDecimal offset) {
        this.offset = offset;
    }
    public Blob getClientData() {
        return this.clientData;
    }
    
    public void setClientData(Blob clientData) {
        this.clientData = clientData;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }




}


