package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrtMddl.Id;
import java.io.Serializable;

/**
 * LogmnrtMddl. generated by hbm2java
 */
public class LogmnrtMddl.  implements java.io.Serializable {


     private LogmnrtMddl.Id id;
     private Serializable destRowid;

    public LogmnrtMddl.() {
    }

    public LogmnrtMddl.(LogmnrtMddl.Id id, Serializable destRowid) {
       this.id = id;
       this.destRowid = destRowid;
    }
   
    public LogmnrtMddl.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrtMddl.Id id) {
        this.id = id;
    }
    public Serializable getDestRowid() {
        return this.destRowid;
    }
    
    public void setDestRowid(Serializable destRowid) {
        this.destRowid = destRowid;
    }




}


