package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LogmnrProcessedLog.Id generated by hbm2java
 */
public class LogmnrProcessedLog.Id  implements java.io.Serializable {


     private BigDecimal session#;
     private BigDecimal thread#;

    public LogmnrProcessedLog.Id() {
    }

    public LogmnrProcessedLog.Id(BigDecimal session#, BigDecimal thread#) {
       this.session# = session#;
       this.thread# = thread#;
    }
   
    public BigDecimal getSession#() {
        return this.session#;
    }
    
    public void setSession#(BigDecimal session#) {
        this.session# = session#;
    }
    public BigDecimal getThread#() {
        return this.thread#;
    }
    
    public void setThread#(BigDecimal thread#) {
        this.thread# = thread#;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrProcessedLog.Id) ) return false;
		 LogmnrProcessedLog.Id castOther = ( LogmnrProcessedLog.Id ) other; 
         
		 return ( (this.getSession#()==castOther.getSession#()) || ( this.getSession#()!=null && castOther.getSession#()!=null && this.getSession#().equals(castOther.getSession#()) ) )
 && ( (this.getThread#()==castOther.getThread#()) || ( this.getThread#()!=null && castOther.getThread#()!=null && this.getThread#().equals(castOther.getThread#()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSession#() == null ? 0 : this.getSession#().hashCode() );
         result = 37 * result + ( getThread#() == null ? 0 : this.getThread#().hashCode() );
         return result;
   }   


}


