package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrSessionEvolve.Id;
import java.math.BigDecimal;
import java.util.Date;

/**
 * LogmnrSessionEvolve. generated by hbm2java
 */
public class LogmnrSessionEvolve.  implements java.io.Serializable {


     private LogmnrSessionEvolve.Id id;
     private BigDecimal branchLevel;
     private BigDecimal prevResetScn;
     private BigDecimal prevResetTimestamp;
     private BigDecimal status;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private BigDecimal spare3;
     private Date spare4;

    public LogmnrSessionEvolve.() {
    }

	
    public LogmnrSessionEvolve.(LogmnrSessionEvolve.Id id) {
        this.id = id;
    }
    public LogmnrSessionEvolve.(LogmnrSessionEvolve.Id id, BigDecimal branchLevel, BigDecimal prevResetScn, BigDecimal prevResetTimestamp, BigDecimal status, BigDecimal spare1, BigDecimal spare2, BigDecimal spare3, Date spare4) {
       this.id = id;
       this.branchLevel = branchLevel;
       this.prevResetScn = prevResetScn;
       this.prevResetTimestamp = prevResetTimestamp;
       this.status = status;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.spare3 = spare3;
       this.spare4 = spare4;
    }
   
    public LogmnrSessionEvolve.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrSessionEvolve.Id id) {
        this.id = id;
    }
    public BigDecimal getBranchLevel() {
        return this.branchLevel;
    }
    
    public void setBranchLevel(BigDecimal branchLevel) {
        this.branchLevel = branchLevel;
    }
    public BigDecimal getPrevResetScn() {
        return this.prevResetScn;
    }
    
    public void setPrevResetScn(BigDecimal prevResetScn) {
        this.prevResetScn = prevResetScn;
    }
    public BigDecimal getPrevResetTimestamp() {
        return this.prevResetTimestamp;
    }
    
    public void setPrevResetTimestamp(BigDecimal prevResetTimestamp) {
        this.prevResetTimestamp = prevResetTimestamp;
    }
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public BigDecimal getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(BigDecimal spare3) {
        this.spare3 = spare3;
    }
    public Date getSpare4() {
        return this.spare4;
    }
    
    public void setSpare4(Date spare4) {
        this.spare4 = spare4;
    }




}


