package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LogmnrTs.Id generated by hbm2java
 */
public class LogmnrTs.Id  implements java.io.Serializable {


     private BigDecimal logmnrUid;
     private BigDecimal ts#;

    public LogmnrTs.Id() {
    }

    public LogmnrTs.Id(BigDecimal logmnrUid, BigDecimal ts#) {
       this.logmnrUid = logmnrUid;
       this.ts# = ts#;
    }
   
    public BigDecimal getLogmnrUid() {
        return this.logmnrUid;
    }
    
    public void setLogmnrUid(BigDecimal logmnrUid) {
        this.logmnrUid = logmnrUid;
    }
    public BigDecimal getTs#() {
        return this.ts#;
    }
    
    public void setTs#(BigDecimal ts#) {
        this.ts# = ts#;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrTs.Id) ) return false;
		 LogmnrTs.Id castOther = ( LogmnrTs.Id ) other; 
         
		 return ( (this.getLogmnrUid()==castOther.getLogmnrUid()) || ( this.getLogmnrUid()!=null && castOther.getLogmnrUid()!=null && this.getLogmnrUid().equals(castOther.getLogmnrUid()) ) )
 && ( (this.getTs#()==castOther.getTs#()) || ( this.getTs#()!=null && castOther.getTs#()!=null && this.getTs#().equals(castOther.getTs#()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogmnrUid() == null ? 0 : this.getLogmnrUid().hashCode() );
         result = 37 * result + ( getTs#() == null ? 0 : this.getTs#().hashCode() );
         return result;
   }   


}


