package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LogmnrSessionEvolve.Id generated by hbm2java
 */
public class LogmnrSessionEvolve.Id  implements java.io.Serializable {


     private BigDecimal session#;
     private BigDecimal dbId;
     private BigDecimal resetScn;
     private BigDecimal resetTimestamp;

    public LogmnrSessionEvolve.Id() {
    }

    public LogmnrSessionEvolve.Id(BigDecimal session#, BigDecimal dbId, BigDecimal resetScn, BigDecimal resetTimestamp) {
       this.session# = session#;
       this.dbId = dbId;
       this.resetScn = resetScn;
       this.resetTimestamp = resetTimestamp;
    }
   
    public BigDecimal getSession#() {
        return this.session#;
    }
    
    public void setSession#(BigDecimal session#) {
        this.session# = session#;
    }
    public BigDecimal getDbId() {
        return this.dbId;
    }
    
    public void setDbId(BigDecimal dbId) {
        this.dbId = dbId;
    }
    public BigDecimal getResetScn() {
        return this.resetScn;
    }
    
    public void setResetScn(BigDecimal resetScn) {
        this.resetScn = resetScn;
    }
    public BigDecimal getResetTimestamp() {
        return this.resetTimestamp;
    }
    
    public void setResetTimestamp(BigDecimal resetTimestamp) {
        this.resetTimestamp = resetTimestamp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrSessionEvolve.Id) ) return false;
		 LogmnrSessionEvolve.Id castOther = ( LogmnrSessionEvolve.Id ) other; 
         
		 return ( (this.getSession#()==castOther.getSession#()) || ( this.getSession#()!=null && castOther.getSession#()!=null && this.getSession#().equals(castOther.getSession#()) ) )
 && ( (this.getDbId()==castOther.getDbId()) || ( this.getDbId()!=null && castOther.getDbId()!=null && this.getDbId().equals(castOther.getDbId()) ) )
 && ( (this.getResetScn()==castOther.getResetScn()) || ( this.getResetScn()!=null && castOther.getResetScn()!=null && this.getResetScn().equals(castOther.getResetScn()) ) )
 && ( (this.getResetTimestamp()==castOther.getResetTimestamp()) || ( this.getResetTimestamp()!=null && castOther.getResetTimestamp()!=null && this.getResetTimestamp().equals(castOther.getResetTimestamp()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSession#() == null ? 0 : this.getSession#().hashCode() );
         result = 37 * result + ( getDbId() == null ? 0 : this.getDbId().hashCode() );
         result = 37 * result + ( getResetScn() == null ? 0 : this.getResetScn().hashCode() );
         result = 37 * result + ( getResetTimestamp() == null ? 0 : this.getResetTimestamp().hashCode() );
         return result;
   }   


}


