package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LogmnrLobfrag.Id generated by hbm2java
 */
public class LogmnrLobfrag.Id  implements java.io.Serializable {


     private BigDecimal logmnrUid;
     private BigDecimal fragobj#;

    public LogmnrLobfrag.Id() {
    }

    public LogmnrLobfrag.Id(BigDecimal logmnrUid, BigDecimal fragobj#) {
       this.logmnrUid = logmnrUid;
       this.fragobj# = fragobj#;
    }
   
    public BigDecimal getLogmnrUid() {
        return this.logmnrUid;
    }
    
    public void setLogmnrUid(BigDecimal logmnrUid) {
        this.logmnrUid = logmnrUid;
    }
    public BigDecimal getFragobj#() {
        return this.fragobj#;
    }
    
    public void setFragobj#(BigDecimal fragobj#) {
        this.fragobj# = fragobj#;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrLobfrag.Id) ) return false;
		 LogmnrLobfrag.Id castOther = ( LogmnrLobfrag.Id ) other; 
         
		 return ( (this.getLogmnrUid()==castOther.getLogmnrUid()) || ( this.getLogmnrUid()!=null && castOther.getLogmnrUid()!=null && this.getLogmnrUid().equals(castOther.getLogmnrUid()) ) )
 && ( (this.getFragobj#()==castOther.getFragobj#()) || ( this.getFragobj#()!=null && castOther.getFragobj#()!=null && this.getFragobj#().equals(castOther.getFragobj#()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogmnrUid() == null ? 0 : this.getLogmnrUid().hashCode() );
         result = 37 * result + ( getFragobj#() == null ? 0 : this.getFragobj#().hashCode() );
         return result;
   }   


}


