package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Logstdby.parametersId;

/**
 * Logstdby.parameters generated by hbm2java
 */
public class Logstdby.parameters  implements java.io.Serializable {


     private Logstdby.parametersId id;

    public Logstdby.parameters() {
    }

    public Logstdby.parameters(Logstdby.parametersId id) {
       this.id = id;
    }
   
    public Logstdby.parametersId getId() {
        return this.id;
    }
    
    public void setId(Logstdby.parametersId id) {
        this.id = id;
    }




}


