package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Mview.AdvRollupId generated by hbm2java
 */
public class Mview.AdvRollupId  implements java.io.Serializable {


     private BigDecimal runid#;
     private BigDecimal clevelid#;
     private BigDecimal plevelid#;

    public Mview.AdvRollupId() {
    }

    public Mview.AdvRollupId(BigDecimal runid#, BigDecimal clevelid#, BigDecimal plevelid#) {
       this.runid# = runid#;
       this.clevelid# = clevelid#;
       this.plevelid# = plevelid#;
    }
   
    public BigDecimal getRunid#() {
        return this.runid#;
    }
    
    public void setRunid#(BigDecimal runid#) {
        this.runid# = runid#;
    }
    public BigDecimal getClevelid#() {
        return this.clevelid#;
    }
    
    public void setClevelid#(BigDecimal clevelid#) {
        this.clevelid# = clevelid#;
    }
    public BigDecimal getPlevelid#() {
        return this.plevelid#;
    }
    
    public void setPlevelid#(BigDecimal plevelid#) {
        this.plevelid# = plevelid#;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Mview.AdvRollupId) ) return false;
		 Mview.AdvRollupId castOther = ( Mview.AdvRollupId ) other; 
         
		 return ( (this.getRunid#()==castOther.getRunid#()) || ( this.getRunid#()!=null && castOther.getRunid#()!=null && this.getRunid#().equals(castOther.getRunid#()) ) )
 && ( (this.getClevelid#()==castOther.getClevelid#()) || ( this.getClevelid#()!=null && castOther.getClevelid#()!=null && this.getClevelid#().equals(castOther.getClevelid#()) ) )
 && ( (this.getPlevelid#()==castOther.getPlevelid#()) || ( this.getPlevelid#()!=null && castOther.getPlevelid#()!=null && this.getPlevelid#().equals(castOther.getPlevelid#()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRunid#() == null ? 0 : this.getRunid#().hashCode() );
         result = 37 * result + ( getClevelid#() == null ? 0 : this.getClevelid#().hashCode() );
         result = 37 * result + ( getPlevelid#() == null ? 0 : this.getPlevelid#().hashCode() );
         return result;
   }   


}


