package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1

/**
 * MviewFilterinstance generated by hbm2java
 */
public class MviewFilterinstance implements java.io.Serializable {

	private MviewFilterinstanceId id;

	public MviewFilterinstance() {
	}

	public MviewFilterinstance(MviewFilterinstanceId id) {
		this.id = id;
	}

	public MviewFilterinstanceId getId() {
		return this.id;
	}

	public void setId(MviewFilterinstanceId id) {
		this.id = id;
	}

}
