package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Mview.AdvFilterinstanceId;
import com.abctreinamentos.Mview.AdvLog;

/**
 * Mview.AdvFilterinstance generated by hbm2java
 */
public class Mview.AdvFilterinstance  implements java.io.Serializable {


     private Mview.AdvFilterinstanceId id;
     private Mview.AdvLog mview$AdvLog;

    public Mview.AdvFilterinstance() {
    }

    public Mview.AdvFilterinstance(Mview.AdvFilterinstanceId id, Mview.AdvLog mview$AdvLog) {
       this.id = id;
       this.mview$AdvLog = mview$AdvLog;
    }
   
    public Mview.AdvFilterinstanceId getId() {
        return this.id;
    }
    
    public void setId(Mview.AdvFilterinstanceId id) {
        this.id = id;
    }
    public Mview.AdvLog getMview$AdvLog() {
        return this.mview$AdvLog;
    }
    
    public void setMview$AdvLog(Mview.AdvLog mview$AdvLog) {
        this.mview$AdvLog = mview$AdvLog;
    }




}


