package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Mview.AdvLevelId;
import com.abctreinamentos.Mview.AdvLog;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Mview.AdvLevel generated by hbm2java
 */
public class Mview.AdvLevel  implements java.io.Serializable {


     private Mview.AdvLevelId id;
     private Mview.AdvLog mview$AdvLog;
     private BigDecimal dimobj#;
     private BigDecimal flags;
     private BigDecimal tblobj#;
     private byte[] columnlist;
     private String levelname;
     private Set mview$AdvRollupsForMview$AdvRollupPfk = new HashSet(0);
     private Set mview$AdvRollupsForMview$AdvRollupCfk = new HashSet(0);

    public Mview.AdvLevel() {
    }

	
    public Mview.AdvLevel(Mview.AdvLevelId id, Mview.AdvLog mview$AdvLog, BigDecimal flags, BigDecimal tblobj#, byte[] columnlist) {
        this.id = id;
        this.mview$AdvLog = mview$AdvLog;
        this.flags = flags;
        this.tblobj# = tblobj#;
        this.columnlist = columnlist;
    }
    public Mview.AdvLevel(Mview.AdvLevelId id, Mview.AdvLog mview$AdvLog, BigDecimal dimobj#, BigDecimal flags, BigDecimal tblobj#, byte[] columnlist, String levelname, Set mview$AdvRollupsForMview$AdvRollupPfk, Set mview$AdvRollupsForMview$AdvRollupCfk) {
       this.id = id;
       this.mview$AdvLog = mview$AdvLog;
       this.dimobj# = dimobj#;
       this.flags = flags;
       this.tblobj# = tblobj#;
       this.columnlist = columnlist;
       this.levelname = levelname;
       this.mview$AdvRollupsForMview$AdvRollupPfk = mview$AdvRollupsForMview$AdvRollupPfk;
       this.mview$AdvRollupsForMview$AdvRollupCfk = mview$AdvRollupsForMview$AdvRollupCfk;
    }
   
    public Mview.AdvLevelId getId() {
        return this.id;
    }
    
    public void setId(Mview.AdvLevelId id) {
        this.id = id;
    }
    public Mview.AdvLog getMview$AdvLog() {
        return this.mview$AdvLog;
    }
    
    public void setMview$AdvLog(Mview.AdvLog mview$AdvLog) {
        this.mview$AdvLog = mview$AdvLog;
    }
    public BigDecimal getDimobj#() {
        return this.dimobj#;
    }
    
    public void setDimobj#(BigDecimal dimobj#) {
        this.dimobj# = dimobj#;
    }
    public BigDecimal getFlags() {
        return this.flags;
    }
    
    public void setFlags(BigDecimal flags) {
        this.flags = flags;
    }
    public BigDecimal getTblobj#() {
        return this.tblobj#;
    }
    
    public void setTblobj#(BigDecimal tblobj#) {
        this.tblobj# = tblobj#;
    }
    public byte[] getColumnlist() {
        return this.columnlist;
    }
    
    public void setColumnlist(byte[] columnlist) {
        this.columnlist = columnlist;
    }
    public String getLevelname() {
        return this.levelname;
    }
    
    public void setLevelname(String levelname) {
        this.levelname = levelname;
    }
    public Set getMview$AdvRollupsForMview$AdvRollupPfk() {
        return this.mview$AdvRollupsForMview$AdvRollupPfk;
    }
    
    public void setMview$AdvRollupsForMview$AdvRollupPfk(Set mview$AdvRollupsForMview$AdvRollupPfk) {
        this.mview$AdvRollupsForMview$AdvRollupPfk = mview$AdvRollupsForMview$AdvRollupPfk;
    }
    public Set getMview$AdvRollupsForMview$AdvRollupCfk() {
        return this.mview$AdvRollupsForMview$AdvRollupCfk;
    }
    
    public void setMview$AdvRollupsForMview$AdvRollupCfk(Set mview$AdvRollupsForMview$AdvRollupCfk) {
        this.mview$AdvRollupsForMview$AdvRollupCfk = mview$AdvRollupsForMview$AdvRollupCfk;
    }




}


