package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Rolling.directivesId;

/**
 * Rolling.directives generated by hbm2java
 */
public class Rolling.directives  implements java.io.Serializable {


     private Rolling.directivesId id;

    public Rolling.directives() {
    }

    public Rolling.directives(Rolling.directivesId id) {
       this.id = id;
    }
   
    public Rolling.directivesId getId() {
        return this.id;
    }
    
    public void setId(Rolling.directivesId id) {
        this.id = id;
    }




}


