package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Rolling.databasesId;

/**
 * Rolling.databases generated by hbm2java
 */
public class Rolling.databases  implements java.io.Serializable {


     private Rolling.databasesId id;

    public Rolling.databases() {
    }

    public Rolling.databases(Rolling.databasesId id) {
       this.id = id;
    }
   
    public Rolling.databasesId getId() {
        return this.id;
    }
    
    public void setId(Rolling.databasesId id) {
        this.id = id;
    }




}


