package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1

/**
 * SchedulerProgramArgsTbl generated by hbm2java
 */
public class SchedulerProgramArgsTbl implements java.io.Serializable {

	private SchedulerProgramArgsTblId id;

	public SchedulerProgramArgsTbl() {
	}

	public SchedulerProgramArgsTbl(SchedulerProgramArgsTblId id) {
		this.id = id;
	}

	public SchedulerProgramArgsTblId getId() {
		return this.id;
	}

	public void setId(SchedulerProgramArgsTblId id) {
		this.id = id;
	}

}
