package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1



/**
 * Aq.InternetAgentPrivsId generated by hbm2java
 */
public class Aq.InternetAgentPrivsId  implements java.io.Serializable {


     private String agentName;
     private String dbUsername;

    public Aq.InternetAgentPrivsId() {
    }

    public Aq.InternetAgentPrivsId(String agentName, String dbUsername) {
       this.agentName = agentName;
       this.dbUsername = dbUsername;
    }
   
    public String getAgentName() {
        return this.agentName;
    }
    
    public void setAgentName(String agentName) {
        this.agentName = agentName;
    }
    public String getDbUsername() {
        return this.dbUsername;
    }
    
    public void setDbUsername(String dbUsername) {
        this.dbUsername = dbUsername;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Aq.InternetAgentPrivsId) ) return false;
		 Aq.InternetAgentPrivsId castOther = ( Aq.InternetAgentPrivsId ) other; 
         
		 return ( (this.getAgentName()==castOther.getAgentName()) || ( this.getAgentName()!=null && castOther.getAgentName()!=null && this.getAgentName().equals(castOther.getAgentName()) ) )
 && ( (this.getDbUsername()==castOther.getDbUsername()) || ( this.getDbUsername()!=null && castOther.getDbUsername()!=null && this.getDbUsername().equals(castOther.getDbUsername()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAgentName() == null ? 0 : this.getAgentName().hashCode() );
         result = 37 * result + ( getDbUsername() == null ? 0 : this.getDbUsername().hashCode() );
         return result;
   }   


}


