package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Aq.QueueTables generated by hbm2java
 */
public class Aq.QueueTables  implements java.io.Serializable {


     private BigDecimal objno;
     private String schema;
     private String name;
     private BigDecimal udataType;
     private BigDecimal flags;
     private BigDecimal sortCols;
     private String timezone;
     private String tableComment;

    public Aq.QueueTables() {
    }

	
    public Aq.QueueTables(BigDecimal objno, String schema, String name, BigDecimal udataType, BigDecimal flags, BigDecimal sortCols) {
        this.objno = objno;
        this.schema = schema;
        this.name = name;
        this.udataType = udataType;
        this.flags = flags;
        this.sortCols = sortCols;
    }
    public Aq.QueueTables(BigDecimal objno, String schema, String name, BigDecimal udataType, BigDecimal flags, BigDecimal sortCols, String timezone, String tableComment) {
       this.objno = objno;
       this.schema = schema;
       this.name = name;
       this.udataType = udataType;
       this.flags = flags;
       this.sortCols = sortCols;
       this.timezone = timezone;
       this.tableComment = tableComment;
    }
   
    public BigDecimal getObjno() {
        return this.objno;
    }
    
    public void setObjno(BigDecimal objno) {
        this.objno = objno;
    }
    public String getSchema() {
        return this.schema;
    }
    
    public void setSchema(String schema) {
        this.schema = schema;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getUdataType() {
        return this.udataType;
    }
    
    public void setUdataType(BigDecimal udataType) {
        this.udataType = udataType;
    }
    public BigDecimal getFlags() {
        return this.flags;
    }
    
    public void setFlags(BigDecimal flags) {
        this.flags = flags;
    }
    public BigDecimal getSortCols() {
        return this.sortCols;
    }
    
    public void setSortCols(BigDecimal sortCols) {
        this.sortCols = sortCols;
    }
    public String getTimezone() {
        return this.timezone;
    }
    
    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }
    public String getTableComment() {
        return this.tableComment;
    }
    
    public void setTableComment(String tableComment) {
        this.tableComment = tableComment;
    }




}


