package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrSeed.Id;
import java.math.BigDecimal;

/**
 * LogmnrSeed. generated by hbm2java
 */
public class LogmnrSeed.  implements java.io.Serializable {


     private LogmnrSeed.Id id;
     private BigDecimal seedVersion;
     private BigDecimal gatherVersion;
     private String schemaname;
     private BigDecimal objv#;
     private String tableName;
     private String colName;
     private BigDecimal col#;
     private BigDecimal segcol#;
     private BigDecimal type#;
     private BigDecimal length;
     private BigDecimal precision#;
     private BigDecimal scale;
     private BigDecimal null$;
     private BigDecimal logmnrFlags;

    public LogmnrSeed.() {
    }

	
    public LogmnrSeed.(LogmnrSeed.Id id, BigDecimal null$) {
        this.id = id;
        this.null$ = null$;
    }
    public LogmnrSeed.(LogmnrSeed.Id id, BigDecimal seedVersion, BigDecimal gatherVersion, String schemaname, BigDecimal objv#, String tableName, String colName, BigDecimal col#, BigDecimal segcol#, BigDecimal type#, BigDecimal length, BigDecimal precision#, BigDecimal scale, BigDecimal null$, BigDecimal logmnrFlags) {
       this.id = id;
       this.seedVersion = seedVersion;
       this.gatherVersion = gatherVersion;
       this.schemaname = schemaname;
       this.objv# = objv#;
       this.tableName = tableName;
       this.colName = colName;
       this.col# = col#;
       this.segcol# = segcol#;
       this.type# = type#;
       this.length = length;
       this.precision# = precision#;
       this.scale = scale;
       this.null$ = null$;
       this.logmnrFlags = logmnrFlags;
    }
   
    public LogmnrSeed.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrSeed.Id id) {
        this.id = id;
    }
    public BigDecimal getSeedVersion() {
        return this.seedVersion;
    }
    
    public void setSeedVersion(BigDecimal seedVersion) {
        this.seedVersion = seedVersion;
    }
    public BigDecimal getGatherVersion() {
        return this.gatherVersion;
    }
    
    public void setGatherVersion(BigDecimal gatherVersion) {
        this.gatherVersion = gatherVersion;
    }
    public String getSchemaname() {
        return this.schemaname;
    }
    
    public void setSchemaname(String schemaname) {
        this.schemaname = schemaname;
    }
    public BigDecimal getObjv#() {
        return this.objv#;
    }
    
    public void setObjv#(BigDecimal objv#) {
        this.objv# = objv#;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getColName() {
        return this.colName;
    }
    
    public void setColName(String colName) {
        this.colName = colName;
    }
    public BigDecimal getCol#() {
        return this.col#;
    }
    
    public void setCol#(BigDecimal col#) {
        this.col# = col#;
    }
    public BigDecimal getSegcol#() {
        return this.segcol#;
    }
    
    public void setSegcol#(BigDecimal segcol#) {
        this.segcol# = segcol#;
    }
    public BigDecimal getType#() {
        return this.type#;
    }
    
    public void setType#(BigDecimal type#) {
        this.type# = type#;
    }
    public BigDecimal getLength() {
        return this.length;
    }
    
    public void setLength(BigDecimal length) {
        this.length = length;
    }
    public BigDecimal getPrecision#() {
        return this.precision#;
    }
    
    public void setPrecision#(BigDecimal precision#) {
        this.precision# = precision#;
    }
    public BigDecimal getScale() {
        return this.scale;
    }
    
    public void setScale(BigDecimal scale) {
        this.scale = scale;
    }
    public BigDecimal getNull$() {
        return this.null$;
    }
    
    public void setNull$(BigDecimal null$) {
        this.null$ = null$;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


