package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * LogmnrtMddl.Id generated by hbm2java
 */
public class LogmnrtMddl.Id  implements java.io.Serializable {


     private BigDecimal sourceObj#;
     private Serializable sourceRowid;

    public LogmnrtMddl.Id() {
    }

    public LogmnrtMddl.Id(BigDecimal sourceObj#, Serializable sourceRowid) {
       this.sourceObj# = sourceObj#;
       this.sourceRowid = sourceRowid;
    }
   
    public BigDecimal getSourceObj#() {
        return this.sourceObj#;
    }
    
    public void setSourceObj#(BigDecimal sourceObj#) {
        this.sourceObj# = sourceObj#;
    }
    public Serializable getSourceRowid() {
        return this.sourceRowid;
    }
    
    public void setSourceRowid(Serializable sourceRowid) {
        this.sourceRowid = sourceRowid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrtMddl.Id) ) return false;
		 LogmnrtMddl.Id castOther = ( LogmnrtMddl.Id ) other; 
         
		 return ( (this.getSourceObj#()==castOther.getSourceObj#()) || ( this.getSourceObj#()!=null && castOther.getSourceObj#()!=null && this.getSourceObj#().equals(castOther.getSourceObj#()) ) )
 && ( (this.getSourceRowid()==castOther.getSourceRowid()) || ( this.getSourceRowid()!=null && castOther.getSourceRowid()!=null && this.getSourceRowid().equals(castOther.getSourceRowid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSourceObj#() == null ? 0 : this.getSourceObj#().hashCode() );
         result = 37 * result + ( getSourceRowid() == null ? 0 : this.getSourceRowid().hashCode() );
         return result;
   }   


}


