package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrPdbInfo.Id;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * LogmnrPdbInfo. generated by hbm2java
 */
public class LogmnrPdbInfo.  implements java.io.Serializable {


     private LogmnrPdbInfo.Id id;
     private String pdbName;
     private BigDecimal pdbId;
     private BigDecimal pdbUid;
     private BigDecimal unplugScn;
     private BigDecimal flags;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private String spare3;
     private Serializable spare4;
     private String pdbGlobalName;

    public LogmnrPdbInfo.() {
    }

	
    public LogmnrPdbInfo.(LogmnrPdbInfo.Id id) {
        this.id = id;
    }
    public LogmnrPdbInfo.(LogmnrPdbInfo.Id id, String pdbName, BigDecimal pdbId, BigDecimal pdbUid, BigDecimal unplugScn, BigDecimal flags, BigDecimal spare1, BigDecimal spare2, String spare3, Serializable spare4, String pdbGlobalName) {
       this.id = id;
       this.pdbName = pdbName;
       this.pdbId = pdbId;
       this.pdbUid = pdbUid;
       this.unplugScn = unplugScn;
       this.flags = flags;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.spare3 = spare3;
       this.spare4 = spare4;
       this.pdbGlobalName = pdbGlobalName;
    }
   
    public LogmnrPdbInfo.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrPdbInfo.Id id) {
        this.id = id;
    }
    public String getPdbName() {
        return this.pdbName;
    }
    
    public void setPdbName(String pdbName) {
        this.pdbName = pdbName;
    }
    public BigDecimal getPdbId() {
        return this.pdbId;
    }
    
    public void setPdbId(BigDecimal pdbId) {
        this.pdbId = pdbId;
    }
    public BigDecimal getPdbUid() {
        return this.pdbUid;
    }
    
    public void setPdbUid(BigDecimal pdbUid) {
        this.pdbUid = pdbUid;
    }
    public BigDecimal getUnplugScn() {
        return this.unplugScn;
    }
    
    public void setUnplugScn(BigDecimal unplugScn) {
        this.unplugScn = unplugScn;
    }
    public BigDecimal getFlags() {
        return this.flags;
    }
    
    public void setFlags(BigDecimal flags) {
        this.flags = flags;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public String getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(String spare3) {
        this.spare3 = spare3;
    }
    public Serializable getSpare4() {
        return this.spare4;
    }
    
    public void setSpare4(Serializable spare4) {
        this.spare4 = spare4;
    }
    public String getPdbGlobalName() {
        return this.pdbGlobalName;
    }
    
    public void setPdbGlobalName(String pdbGlobalName) {
        this.pdbGlobalName = pdbGlobalName;
    }




}


