package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrIdnseq.Id;
import java.math.BigDecimal;

/**
 * LogmnrIdnseq. generated by hbm2java
 */
public class LogmnrIdnseq.  implements java.io.Serializable {


     private LogmnrIdnseq.Id id;
     private BigDecimal seqobj#;
     private BigDecimal startwith;
     private BigDecimal logmnrFlags;

    public LogmnrIdnseq.() {
    }

	
    public LogmnrIdnseq.(LogmnrIdnseq.Id id, BigDecimal seqobj#, BigDecimal startwith) {
        this.id = id;
        this.seqobj# = seqobj#;
        this.startwith = startwith;
    }
    public LogmnrIdnseq.(LogmnrIdnseq.Id id, BigDecimal seqobj#, BigDecimal startwith, BigDecimal logmnrFlags) {
       this.id = id;
       this.seqobj# = seqobj#;
       this.startwith = startwith;
       this.logmnrFlags = logmnrFlags;
    }
   
    public LogmnrIdnseq.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrIdnseq.Id id) {
        this.id = id;
    }
    public BigDecimal getSeqobj#() {
        return this.seqobj#;
    }
    
    public void setSeqobj#(BigDecimal seqobj#) {
        this.seqobj# = seqobj#;
    }
    public BigDecimal getStartwith() {
        return this.startwith;
    }
    
    public void setStartwith(BigDecimal startwith) {
        this.startwith = startwith;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


