package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LogmnrTabsubpart.Id generated by hbm2java
 */
public class LogmnrTabsubpart.Id  implements java.io.Serializable {


     private BigDecimal logmnrUid;
     private BigDecimal obj#;
     private BigDecimal pobj#;

    public LogmnrTabsubpart.Id() {
    }

    public LogmnrTabsubpart.Id(BigDecimal logmnrUid, BigDecimal obj#, BigDecimal pobj#) {
       this.logmnrUid = logmnrUid;
       this.obj# = obj#;
       this.pobj# = pobj#;
    }
   
    public BigDecimal getLogmnrUid() {
        return this.logmnrUid;
    }
    
    public void setLogmnrUid(BigDecimal logmnrUid) {
        this.logmnrUid = logmnrUid;
    }
    public BigDecimal getObj#() {
        return this.obj#;
    }
    
    public void setObj#(BigDecimal obj#) {
        this.obj# = obj#;
    }
    public BigDecimal getPobj#() {
        return this.pobj#;
    }
    
    public void setPobj#(BigDecimal pobj#) {
        this.pobj# = pobj#;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrTabsubpart.Id) ) return false;
		 LogmnrTabsubpart.Id castOther = ( LogmnrTabsubpart.Id ) other; 
         
		 return ( (this.getLogmnrUid()==castOther.getLogmnrUid()) || ( this.getLogmnrUid()!=null && castOther.getLogmnrUid()!=null && this.getLogmnrUid().equals(castOther.getLogmnrUid()) ) )
 && ( (this.getObj#()==castOther.getObj#()) || ( this.getObj#()!=null && castOther.getObj#()!=null && this.getObj#().equals(castOther.getObj#()) ) )
 && ( (this.getPobj#()==castOther.getPobj#()) || ( this.getPobj#()!=null && castOther.getPobj#()!=null && this.getPobj#().equals(castOther.getPobj#()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogmnrUid() == null ? 0 : this.getLogmnrUid().hashCode() );
         result = 37 * result + ( getObj#() == null ? 0 : this.getObj#().hashCode() );
         result = 37 * result + ( getPobj#() == null ? 0 : this.getPobj#().hashCode() );
         return result;
   }   


}


