package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LogmnrPdbInfo.Id generated by hbm2java
 */
public class LogmnrPdbInfo.Id  implements java.io.Serializable {


     private BigDecimal logmnrDid;
     private BigDecimal logmnrMdh;
     private BigDecimal pluginScn;

    public LogmnrPdbInfo.Id() {
    }

    public LogmnrPdbInfo.Id(BigDecimal logmnrDid, BigDecimal logmnrMdh, BigDecimal pluginScn) {
       this.logmnrDid = logmnrDid;
       this.logmnrMdh = logmnrMdh;
       this.pluginScn = pluginScn;
    }
   
    public BigDecimal getLogmnrDid() {
        return this.logmnrDid;
    }
    
    public void setLogmnrDid(BigDecimal logmnrDid) {
        this.logmnrDid = logmnrDid;
    }
    public BigDecimal getLogmnrMdh() {
        return this.logmnrMdh;
    }
    
    public void setLogmnrMdh(BigDecimal logmnrMdh) {
        this.logmnrMdh = logmnrMdh;
    }
    public BigDecimal getPluginScn() {
        return this.pluginScn;
    }
    
    public void setPluginScn(BigDecimal pluginScn) {
        this.pluginScn = pluginScn;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrPdbInfo.Id) ) return false;
		 LogmnrPdbInfo.Id castOther = ( LogmnrPdbInfo.Id ) other; 
         
		 return ( (this.getLogmnrDid()==castOther.getLogmnrDid()) || ( this.getLogmnrDid()!=null && castOther.getLogmnrDid()!=null && this.getLogmnrDid().equals(castOther.getLogmnrDid()) ) )
 && ( (this.getLogmnrMdh()==castOther.getLogmnrMdh()) || ( this.getLogmnrMdh()!=null && castOther.getLogmnrMdh()!=null && this.getLogmnrMdh().equals(castOther.getLogmnrMdh()) ) )
 && ( (this.getPluginScn()==castOther.getPluginScn()) || ( this.getPluginScn()!=null && castOther.getPluginScn()!=null && this.getPluginScn().equals(castOther.getPluginScn()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogmnrDid() == null ? 0 : this.getLogmnrDid().hashCode() );
         result = 37 * result + ( getLogmnrMdh() == null ? 0 : this.getLogmnrMdh().hashCode() );
         result = 37 * result + ( getPluginScn() == null ? 0 : this.getPluginScn().hashCode() );
         return result;
   }   


}


