package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrTs.Id;
import java.math.BigDecimal;

/**
 * LogmnrTs. generated by hbm2java
 */
public class LogmnrTs.  implements java.io.Serializable {


     private LogmnrTs.Id id;
     private String name;
     private BigDecimal owner#;
     private BigDecimal blocksize;
     private BigDecimal logmnrFlags;
     private BigDecimal startScnbas;
     private BigDecimal startScnwrp;

    public LogmnrTs.() {
    }

	
    public LogmnrTs.(LogmnrTs.Id id, BigDecimal blocksize) {
        this.id = id;
        this.blocksize = blocksize;
    }
    public LogmnrTs.(LogmnrTs.Id id, String name, BigDecimal owner#, BigDecimal blocksize, BigDecimal logmnrFlags, BigDecimal startScnbas, BigDecimal startScnwrp) {
       this.id = id;
       this.name = name;
       this.owner# = owner#;
       this.blocksize = blocksize;
       this.logmnrFlags = logmnrFlags;
       this.startScnbas = startScnbas;
       this.startScnwrp = startScnwrp;
    }
   
    public LogmnrTs.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrTs.Id id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getOwner#() {
        return this.owner#;
    }
    
    public void setOwner#(BigDecimal owner#) {
        this.owner# = owner#;
    }
    public BigDecimal getBlocksize() {
        return this.blocksize;
    }
    
    public void setBlocksize(BigDecimal blocksize) {
        this.blocksize = blocksize;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }
    public BigDecimal getStartScnbas() {
        return this.startScnbas;
    }
    
    public void setStartScnbas(BigDecimal startScnbas) {
        this.startScnbas = startScnbas;
    }
    public BigDecimal getStartScnwrp() {
        return this.startScnwrp;
    }
    
    public void setStartScnwrp(BigDecimal startScnwrp) {
        this.startScnwrp = startScnwrp;
    }




}


