package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * LogmnrUid. generated by hbm2java
 */
public class LogmnrUid.  implements java.io.Serializable {


     private BigDecimal logmnrUid;
     private BigDecimal logmnrDid;
     private BigDecimal logmnrMdh;
     private String pdbName;
     private BigDecimal pdbId;
     private BigDecimal pdbUid;
     private BigDecimal startScn;
     private BigDecimal endScn;
     private BigDecimal flags;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private String spare3;
     private Serializable spare4;

    public LogmnrUid.() {
    }

	
    public LogmnrUid.(BigDecimal logmnrUid) {
        this.logmnrUid = logmnrUid;
    }
    public LogmnrUid.(BigDecimal logmnrUid, BigDecimal logmnrDid, BigDecimal logmnrMdh, String pdbName, BigDecimal pdbId, BigDecimal pdbUid, BigDecimal startScn, BigDecimal endScn, BigDecimal flags, BigDecimal spare1, BigDecimal spare2, String spare3, Serializable spare4) {
       this.logmnrUid = logmnrUid;
       this.logmnrDid = logmnrDid;
       this.logmnrMdh = logmnrMdh;
       this.pdbName = pdbName;
       this.pdbId = pdbId;
       this.pdbUid = pdbUid;
       this.startScn = startScn;
       this.endScn = endScn;
       this.flags = flags;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.spare3 = spare3;
       this.spare4 = spare4;
    }
   
    public BigDecimal getLogmnrUid() {
        return this.logmnrUid;
    }
    
    public void setLogmnrUid(BigDecimal logmnrUid) {
        this.logmnrUid = logmnrUid;
    }
    public BigDecimal getLogmnrDid() {
        return this.logmnrDid;
    }
    
    public void setLogmnrDid(BigDecimal logmnrDid) {
        this.logmnrDid = logmnrDid;
    }
    public BigDecimal getLogmnrMdh() {
        return this.logmnrMdh;
    }
    
    public void setLogmnrMdh(BigDecimal logmnrMdh) {
        this.logmnrMdh = logmnrMdh;
    }
    public String getPdbName() {
        return this.pdbName;
    }
    
    public void setPdbName(String pdbName) {
        this.pdbName = pdbName;
    }
    public BigDecimal getPdbId() {
        return this.pdbId;
    }
    
    public void setPdbId(BigDecimal pdbId) {
        this.pdbId = pdbId;
    }
    public BigDecimal getPdbUid() {
        return this.pdbUid;
    }
    
    public void setPdbUid(BigDecimal pdbUid) {
        this.pdbUid = pdbUid;
    }
    public BigDecimal getStartScn() {
        return this.startScn;
    }
    
    public void setStartScn(BigDecimal startScn) {
        this.startScn = startScn;
    }
    public BigDecimal getEndScn() {
        return this.endScn;
    }
    
    public void setEndScn(BigDecimal endScn) {
        this.endScn = endScn;
    }
    public BigDecimal getFlags() {
        return this.flags;
    }
    
    public void setFlags(BigDecimal flags) {
        this.flags = flags;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public String getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(String spare3) {
        this.spare3 = spare3;
    }
    public Serializable getSpare4() {
        return this.spare4;
    }
    
    public void setSpare4(Serializable spare4) {
        this.spare4 = spare4;
    }




}


