package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrUser.Id;
import java.math.BigDecimal;

/**
 * LogmnrUser. generated by hbm2java
 */
public class LogmnrUser.  implements java.io.Serializable {


     private LogmnrUser.Id id;
     private String name;
     private BigDecimal logmnrFlags;

    public LogmnrUser.() {
    }

	
    public LogmnrUser.(LogmnrUser.Id id, String name) {
        this.id = id;
        this.name = name;
    }
    public LogmnrUser.(LogmnrUser.Id id, String name, BigDecimal logmnrFlags) {
       this.id = id;
       this.name = name;
       this.logmnrFlags = logmnrFlags;
    }
   
    public LogmnrUser.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrUser.Id id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


