package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrAttrcol.Id;
import java.math.BigDecimal;

/**
 * LogmnrAttrcol. generated by hbm2java
 */
public class LogmnrAttrcol.  implements java.io.Serializable {


     private LogmnrAttrcol.Id id;
     private String name;
     private BigDecimal logmnrFlags;

    public LogmnrAttrcol.() {
    }

	
    public LogmnrAttrcol.(LogmnrAttrcol.Id id) {
        this.id = id;
    }
    public LogmnrAttrcol.(LogmnrAttrcol.Id id, String name, BigDecimal logmnrFlags) {
       this.id = id;
       this.name = name;
       this.logmnrFlags = logmnrFlags;
    }
   
    public LogmnrAttrcol.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrAttrcol.Id id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


