package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LogmnrLog.Id generated by hbm2java
 */
public class LogmnrLog.Id  implements java.io.Serializable {


     private BigDecimal session#;
     private BigDecimal thread#;
     private BigDecimal sequence#;
     private BigDecimal firstChange#;
     private BigDecimal dbId;
     private BigDecimal resetlogsChange#;
     private BigDecimal resetTimestamp;

    public LogmnrLog.Id() {
    }

    public LogmnrLog.Id(BigDecimal session#, BigDecimal thread#, BigDecimal sequence#, BigDecimal firstChange#, BigDecimal dbId, BigDecimal resetlogsChange#, BigDecimal resetTimestamp) {
       this.session# = session#;
       this.thread# = thread#;
       this.sequence# = sequence#;
       this.firstChange# = firstChange#;
       this.dbId = dbId;
       this.resetlogsChange# = resetlogsChange#;
       this.resetTimestamp = resetTimestamp;
    }
   
    public BigDecimal getSession#() {
        return this.session#;
    }
    
    public void setSession#(BigDecimal session#) {
        this.session# = session#;
    }
    public BigDecimal getThread#() {
        return this.thread#;
    }
    
    public void setThread#(BigDecimal thread#) {
        this.thread# = thread#;
    }
    public BigDecimal getSequence#() {
        return this.sequence#;
    }
    
    public void setSequence#(BigDecimal sequence#) {
        this.sequence# = sequence#;
    }
    public BigDecimal getFirstChange#() {
        return this.firstChange#;
    }
    
    public void setFirstChange#(BigDecimal firstChange#) {
        this.firstChange# = firstChange#;
    }
    public BigDecimal getDbId() {
        return this.dbId;
    }
    
    public void setDbId(BigDecimal dbId) {
        this.dbId = dbId;
    }
    public BigDecimal getResetlogsChange#() {
        return this.resetlogsChange#;
    }
    
    public void setResetlogsChange#(BigDecimal resetlogsChange#) {
        this.resetlogsChange# = resetlogsChange#;
    }
    public BigDecimal getResetTimestamp() {
        return this.resetTimestamp;
    }
    
    public void setResetTimestamp(BigDecimal resetTimestamp) {
        this.resetTimestamp = resetTimestamp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrLog.Id) ) return false;
		 LogmnrLog.Id castOther = ( LogmnrLog.Id ) other; 
         
		 return ( (this.getSession#()==castOther.getSession#()) || ( this.getSession#()!=null && castOther.getSession#()!=null && this.getSession#().equals(castOther.getSession#()) ) )
 && ( (this.getThread#()==castOther.getThread#()) || ( this.getThread#()!=null && castOther.getThread#()!=null && this.getThread#().equals(castOther.getThread#()) ) )
 && ( (this.getSequence#()==castOther.getSequence#()) || ( this.getSequence#()!=null && castOther.getSequence#()!=null && this.getSequence#().equals(castOther.getSequence#()) ) )
 && ( (this.getFirstChange#()==castOther.getFirstChange#()) || ( this.getFirstChange#()!=null && castOther.getFirstChange#()!=null && this.getFirstChange#().equals(castOther.getFirstChange#()) ) )
 && ( (this.getDbId()==castOther.getDbId()) || ( this.getDbId()!=null && castOther.getDbId()!=null && this.getDbId().equals(castOther.getDbId()) ) )
 && ( (this.getResetlogsChange#()==castOther.getResetlogsChange#()) || ( this.getResetlogsChange#()!=null && castOther.getResetlogsChange#()!=null && this.getResetlogsChange#().equals(castOther.getResetlogsChange#()) ) )
 && ( (this.getResetTimestamp()==castOther.getResetTimestamp()) || ( this.getResetTimestamp()!=null && castOther.getResetTimestamp()!=null && this.getResetTimestamp().equals(castOther.getResetTimestamp()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSession#() == null ? 0 : this.getSession#().hashCode() );
         result = 37 * result + ( getThread#() == null ? 0 : this.getThread#().hashCode() );
         result = 37 * result + ( getSequence#() == null ? 0 : this.getSequence#().hashCode() );
         result = 37 * result + ( getFirstChange#() == null ? 0 : this.getFirstChange#().hashCode() );
         result = 37 * result + ( getDbId() == null ? 0 : this.getDbId().hashCode() );
         result = 37 * result + ( getResetlogsChange#() == null ? 0 : this.getResetlogsChange#().hashCode() );
         result = 37 * result + ( getResetTimestamp() == null ? 0 : this.getResetTimestamp().hashCode() );
         return result;
   }   


}


