package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LogmnrCcol.Id generated by hbm2java
 */
public class LogmnrCcol.Id  implements java.io.Serializable {


     private BigDecimal logmnrUid;
     private BigDecimal con#;
     private BigDecimal intcol#;

    public LogmnrCcol.Id() {
    }

	
    public LogmnrCcol.Id(BigDecimal intcol#) {
        this.intcol# = intcol#;
    }
    public LogmnrCcol.Id(BigDecimal logmnrUid, BigDecimal con#, BigDecimal intcol#) {
       this.logmnrUid = logmnrUid;
       this.con# = con#;
       this.intcol# = intcol#;
    }
   
    public BigDecimal getLogmnrUid() {
        return this.logmnrUid;
    }
    
    public void setLogmnrUid(BigDecimal logmnrUid) {
        this.logmnrUid = logmnrUid;
    }
    public BigDecimal getCon#() {
        return this.con#;
    }
    
    public void setCon#(BigDecimal con#) {
        this.con# = con#;
    }
    public BigDecimal getIntcol#() {
        return this.intcol#;
    }
    
    public void setIntcol#(BigDecimal intcol#) {
        this.intcol# = intcol#;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrCcol.Id) ) return false;
		 LogmnrCcol.Id castOther = ( LogmnrCcol.Id ) other; 
         
		 return ( (this.getLogmnrUid()==castOther.getLogmnrUid()) || ( this.getLogmnrUid()!=null && castOther.getLogmnrUid()!=null && this.getLogmnrUid().equals(castOther.getLogmnrUid()) ) )
 && ( (this.getCon#()==castOther.getCon#()) || ( this.getCon#()!=null && castOther.getCon#()!=null && this.getCon#().equals(castOther.getCon#()) ) )
 && ( (this.getIntcol#()==castOther.getIntcol#()) || ( this.getIntcol#()!=null && castOther.getIntcol#()!=null && this.getIntcol#().equals(castOther.getIntcol#()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogmnrUid() == null ? 0 : this.getLogmnrUid().hashCode() );
         result = 37 * result + ( getCon#() == null ? 0 : this.getCon#().hashCode() );
         result = 37 * result + ( getIntcol#() == null ? 0 : this.getIntcol#().hashCode() );
         return result;
   }   


}


