package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.LogmnrGtXidInclude.Id;

/**
 * LogmnrGtXidInclude. generated by hbm2java
 */
public class LogmnrGtXidInclude.  implements java.io.Serializable {


     private LogmnrGtXidInclude.Id id;

    public LogmnrGtXidInclude.() {
    }

    public LogmnrGtXidInclude.(LogmnrGtXidInclude.Id id) {
       this.id = id;
    }
   
    public LogmnrGtXidInclude.Id getId() {
        return this.id;
    }
    
    public void setId(LogmnrGtXidInclude.Id id) {
        this.id = id;
    }




}


