package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Logstdby.historyId generated by hbm2java
 */
public class Logstdby.historyId  implements java.io.Serializable {


     private BigDecimal streamSequence#;
     private BigDecimal lmnrSid;
     private BigDecimal dbid;
     private BigDecimal firstChange#;
     private BigDecimal lastChange#;
     private BigDecimal source;
     private BigDecimal status;
     private Date firstTime;
     private Date lastTime;
     private String dgname;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private String spare3;

    public Logstdby.historyId() {
    }

    public Logstdby.historyId(BigDecimal streamSequence#, BigDecimal lmnrSid, BigDecimal dbid, BigDecimal firstChange#, BigDecimal lastChange#, BigDecimal source, BigDecimal status, Date firstTime, Date lastTime, String dgname, BigDecimal spare1, BigDecimal spare2, String spare3) {
       this.streamSequence# = streamSequence#;
       this.lmnrSid = lmnrSid;
       this.dbid = dbid;
       this.firstChange# = firstChange#;
       this.lastChange# = lastChange#;
       this.source = source;
       this.status = status;
       this.firstTime = firstTime;
       this.lastTime = lastTime;
       this.dgname = dgname;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.spare3 = spare3;
    }
   
    public BigDecimal getStreamSequence#() {
        return this.streamSequence#;
    }
    
    public void setStreamSequence#(BigDecimal streamSequence#) {
        this.streamSequence# = streamSequence#;
    }
    public BigDecimal getLmnrSid() {
        return this.lmnrSid;
    }
    
    public void setLmnrSid(BigDecimal lmnrSid) {
        this.lmnrSid = lmnrSid;
    }
    public BigDecimal getDbid() {
        return this.dbid;
    }
    
    public void setDbid(BigDecimal dbid) {
        this.dbid = dbid;
    }
    public BigDecimal getFirstChange#() {
        return this.firstChange#;
    }
    
    public void setFirstChange#(BigDecimal firstChange#) {
        this.firstChange# = firstChange#;
    }
    public BigDecimal getLastChange#() {
        return this.lastChange#;
    }
    
    public void setLastChange#(BigDecimal lastChange#) {
        this.lastChange# = lastChange#;
    }
    public BigDecimal getSource() {
        return this.source;
    }
    
    public void setSource(BigDecimal source) {
        this.source = source;
    }
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }
    public Date getFirstTime() {
        return this.firstTime;
    }
    
    public void setFirstTime(Date firstTime) {
        this.firstTime = firstTime;
    }
    public Date getLastTime() {
        return this.lastTime;
    }
    
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }
    public String getDgname() {
        return this.dgname;
    }
    
    public void setDgname(String dgname) {
        this.dgname = dgname;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public String getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(String spare3) {
        this.spare3 = spare3;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Logstdby.historyId) ) return false;
		 Logstdby.historyId castOther = ( Logstdby.historyId ) other; 
         
		 return ( (this.getStreamSequence#()==castOther.getStreamSequence#()) || ( this.getStreamSequence#()!=null && castOther.getStreamSequence#()!=null && this.getStreamSequence#().equals(castOther.getStreamSequence#()) ) )
 && ( (this.getLmnrSid()==castOther.getLmnrSid()) || ( this.getLmnrSid()!=null && castOther.getLmnrSid()!=null && this.getLmnrSid().equals(castOther.getLmnrSid()) ) )
 && ( (this.getDbid()==castOther.getDbid()) || ( this.getDbid()!=null && castOther.getDbid()!=null && this.getDbid().equals(castOther.getDbid()) ) )
 && ( (this.getFirstChange#()==castOther.getFirstChange#()) || ( this.getFirstChange#()!=null && castOther.getFirstChange#()!=null && this.getFirstChange#().equals(castOther.getFirstChange#()) ) )
 && ( (this.getLastChange#()==castOther.getLastChange#()) || ( this.getLastChange#()!=null && castOther.getLastChange#()!=null && this.getLastChange#().equals(castOther.getLastChange#()) ) )
 && ( (this.getSource()==castOther.getSource()) || ( this.getSource()!=null && castOther.getSource()!=null && this.getSource().equals(castOther.getSource()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getFirstTime()==castOther.getFirstTime()) || ( this.getFirstTime()!=null && castOther.getFirstTime()!=null && this.getFirstTime().equals(castOther.getFirstTime()) ) )
 && ( (this.getLastTime()==castOther.getLastTime()) || ( this.getLastTime()!=null && castOther.getLastTime()!=null && this.getLastTime().equals(castOther.getLastTime()) ) )
 && ( (this.getDgname()==castOther.getDgname()) || ( this.getDgname()!=null && castOther.getDgname()!=null && this.getDgname().equals(castOther.getDgname()) ) )
 && ( (this.getSpare1()==castOther.getSpare1()) || ( this.getSpare1()!=null && castOther.getSpare1()!=null && this.getSpare1().equals(castOther.getSpare1()) ) )
 && ( (this.getSpare2()==castOther.getSpare2()) || ( this.getSpare2()!=null && castOther.getSpare2()!=null && this.getSpare2().equals(castOther.getSpare2()) ) )
 && ( (this.getSpare3()==castOther.getSpare3()) || ( this.getSpare3()!=null && castOther.getSpare3()!=null && this.getSpare3().equals(castOther.getSpare3()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getStreamSequence#() == null ? 0 : this.getStreamSequence#().hashCode() );
         result = 37 * result + ( getLmnrSid() == null ? 0 : this.getLmnrSid().hashCode() );
         result = 37 * result + ( getDbid() == null ? 0 : this.getDbid().hashCode() );
         result = 37 * result + ( getFirstChange#() == null ? 0 : this.getFirstChange#().hashCode() );
         result = 37 * result + ( getLastChange#() == null ? 0 : this.getLastChange#().hashCode() );
         result = 37 * result + ( getSource() == null ? 0 : this.getSource().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getFirstTime() == null ? 0 : this.getFirstTime().hashCode() );
         result = 37 * result + ( getLastTime() == null ? 0 : this.getLastTime().hashCode() );
         result = 37 * result + ( getDgname() == null ? 0 : this.getDgname().hashCode() );
         result = 37 * result + ( getSpare1() == null ? 0 : this.getSpare1().hashCode() );
         result = 37 * result + ( getSpare2() == null ? 0 : this.getSpare2().hashCode() );
         result = 37 * result + ( getSpare3() == null ? 0 : this.getSpare3().hashCode() );
         return result;
   }   


}


