package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Logstdby.skipSupportId generated by hbm2java
 */
public class Logstdby.skipSupportId  implements java.io.Serializable {


     private BigDecimal action;
     private String name;
     private String name2;
     private String name3;
     private String name4;
     private String name5;
     private BigDecimal reg;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private String spare3;

    public Logstdby.skipSupportId() {
    }

	
    public Logstdby.skipSupportId(BigDecimal action, String name) {
        this.action = action;
        this.name = name;
    }
    public Logstdby.skipSupportId(BigDecimal action, String name, String name2, String name3, String name4, String name5, BigDecimal reg, BigDecimal spare1, BigDecimal spare2, String spare3) {
       this.action = action;
       this.name = name;
       this.name2 = name2;
       this.name3 = name3;
       this.name4 = name4;
       this.name5 = name5;
       this.reg = reg;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.spare3 = spare3;
    }
   
    public BigDecimal getAction() {
        return this.action;
    }
    
    public void setAction(BigDecimal action) {
        this.action = action;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getName2() {
        return this.name2;
    }
    
    public void setName2(String name2) {
        this.name2 = name2;
    }
    public String getName3() {
        return this.name3;
    }
    
    public void setName3(String name3) {
        this.name3 = name3;
    }
    public String getName4() {
        return this.name4;
    }
    
    public void setName4(String name4) {
        this.name4 = name4;
    }
    public String getName5() {
        return this.name5;
    }
    
    public void setName5(String name5) {
        this.name5 = name5;
    }
    public BigDecimal getReg() {
        return this.reg;
    }
    
    public void setReg(BigDecimal reg) {
        this.reg = reg;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public String getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(String spare3) {
        this.spare3 = spare3;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Logstdby.skipSupportId) ) return false;
		 Logstdby.skipSupportId castOther = ( Logstdby.skipSupportId ) other; 
         
		 return ( (this.getAction()==castOther.getAction()) || ( this.getAction()!=null && castOther.getAction()!=null && this.getAction().equals(castOther.getAction()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getName2()==castOther.getName2()) || ( this.getName2()!=null && castOther.getName2()!=null && this.getName2().equals(castOther.getName2()) ) )
 && ( (this.getName3()==castOther.getName3()) || ( this.getName3()!=null && castOther.getName3()!=null && this.getName3().equals(castOther.getName3()) ) )
 && ( (this.getName4()==castOther.getName4()) || ( this.getName4()!=null && castOther.getName4()!=null && this.getName4().equals(castOther.getName4()) ) )
 && ( (this.getName5()==castOther.getName5()) || ( this.getName5()!=null && castOther.getName5()!=null && this.getName5().equals(castOther.getName5()) ) )
 && ( (this.getReg()==castOther.getReg()) || ( this.getReg()!=null && castOther.getReg()!=null && this.getReg().equals(castOther.getReg()) ) )
 && ( (this.getSpare1()==castOther.getSpare1()) || ( this.getSpare1()!=null && castOther.getSpare1()!=null && this.getSpare1().equals(castOther.getSpare1()) ) )
 && ( (this.getSpare2()==castOther.getSpare2()) || ( this.getSpare2()!=null && castOther.getSpare2()!=null && this.getSpare2().equals(castOther.getSpare2()) ) )
 && ( (this.getSpare3()==castOther.getSpare3()) || ( this.getSpare3()!=null && castOther.getSpare3()!=null && this.getSpare3().equals(castOther.getSpare3()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAction() == null ? 0 : this.getAction().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getName2() == null ? 0 : this.getName2().hashCode() );
         result = 37 * result + ( getName3() == null ? 0 : this.getName3().hashCode() );
         result = 37 * result + ( getName4() == null ? 0 : this.getName4().hashCode() );
         result = 37 * result + ( getName5() == null ? 0 : this.getName5().hashCode() );
         result = 37 * result + ( getReg() == null ? 0 : this.getReg().hashCode() );
         result = 37 * result + ( getSpare1() == null ? 0 : this.getSpare1().hashCode() );
         result = 37 * result + ( getSpare2() == null ? 0 : this.getSpare2().hashCode() );
         result = 37 * result + ( getSpare3() == null ? 0 : this.getSpare3().hashCode() );
         return result;
   }   


}


