package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1



/**
 * Logstdby.edsTablesId generated by hbm2java
 */
public class Logstdby.edsTablesId  implements java.io.Serializable {


     private String owner;
     private String tableName;

    public Logstdby.edsTablesId() {
    }

    public Logstdby.edsTablesId(String owner, String tableName) {
       this.owner = owner;
       this.tableName = tableName;
    }
   
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Logstdby.edsTablesId) ) return false;
		 Logstdby.edsTablesId castOther = ( Logstdby.edsTablesId ) other; 
         
		 return ( (this.getOwner()==castOther.getOwner()) || ( this.getOwner()!=null && castOther.getOwner()!=null && this.getOwner().equals(castOther.getOwner()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOwner() == null ? 0 : this.getOwner().hashCode() );
         result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
         return result;
   }   


}


