package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1

/**
 * MviewLog generated by hbm2java
 */
public class MviewLog implements java.io.Serializable {

	private MviewLogId id;

	public MviewLog() {
	}

	public MviewLog(MviewLogId id) {
		this.id = id;
	}

	public MviewLogId getId() {
		return this.id;
	}

	public void setId(MviewLogId id) {
		this.id = id;
	}

}
