package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Ol.Id;

/**
 * Ol. generated by hbm2java
 */
public class Ol.  implements java.io.Serializable {


     private Ol.Id id;

    public Ol.() {
    }

    public Ol.(Ol.Id id) {
       this.id = id;
    }
   
    public Ol.Id getId() {
        return this.id;
    }
    
    public void setId(Ol.Id id) {
        this.id = id;
    }




}


