package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Rolling.parametersId generated by hbm2java
 */
public class Rolling.parametersId  implements java.io.Serializable {


     private BigDecimal scope;
     private String name;
     private BigDecimal id;
     private String descrip;
     private BigDecimal type;
     private BigDecimal datatype;
     private BigDecimal attributes;
     private String curval;
     private String lstval;
     private String defval;
     private BigDecimal minval;
     private BigDecimal maxval;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private String spare3;

    public Rolling.parametersId() {
    }

    public Rolling.parametersId(BigDecimal scope, String name, BigDecimal id, String descrip, BigDecimal type, BigDecimal datatype, BigDecimal attributes, String curval, String lstval, String defval, BigDecimal minval, BigDecimal maxval, BigDecimal spare1, BigDecimal spare2, String spare3) {
       this.scope = scope;
       this.name = name;
       this.id = id;
       this.descrip = descrip;
       this.type = type;
       this.datatype = datatype;
       this.attributes = attributes;
       this.curval = curval;
       this.lstval = lstval;
       this.defval = defval;
       this.minval = minval;
       this.maxval = maxval;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.spare3 = spare3;
    }
   
    public BigDecimal getScope() {
        return this.scope;
    }
    
    public void setScope(BigDecimal scope) {
        this.scope = scope;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }
    public BigDecimal getType() {
        return this.type;
    }
    
    public void setType(BigDecimal type) {
        this.type = type;
    }
    public BigDecimal getDatatype() {
        return this.datatype;
    }
    
    public void setDatatype(BigDecimal datatype) {
        this.datatype = datatype;
    }
    public BigDecimal getAttributes() {
        return this.attributes;
    }
    
    public void setAttributes(BigDecimal attributes) {
        this.attributes = attributes;
    }
    public String getCurval() {
        return this.curval;
    }
    
    public void setCurval(String curval) {
        this.curval = curval;
    }
    public String getLstval() {
        return this.lstval;
    }
    
    public void setLstval(String lstval) {
        this.lstval = lstval;
    }
    public String getDefval() {
        return this.defval;
    }
    
    public void setDefval(String defval) {
        this.defval = defval;
    }
    public BigDecimal getMinval() {
        return this.minval;
    }
    
    public void setMinval(BigDecimal minval) {
        this.minval = minval;
    }
    public BigDecimal getMaxval() {
        return this.maxval;
    }
    
    public void setMaxval(BigDecimal maxval) {
        this.maxval = maxval;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public String getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(String spare3) {
        this.spare3 = spare3;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Rolling.parametersId) ) return false;
		 Rolling.parametersId castOther = ( Rolling.parametersId ) other; 
         
		 return ( (this.getScope()==castOther.getScope()) || ( this.getScope()!=null && castOther.getScope()!=null && this.getScope().equals(castOther.getScope()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getDescrip()==castOther.getDescrip()) || ( this.getDescrip()!=null && castOther.getDescrip()!=null && this.getDescrip().equals(castOther.getDescrip()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && ( (this.getDatatype()==castOther.getDatatype()) || ( this.getDatatype()!=null && castOther.getDatatype()!=null && this.getDatatype().equals(castOther.getDatatype()) ) )
 && ( (this.getAttributes()==castOther.getAttributes()) || ( this.getAttributes()!=null && castOther.getAttributes()!=null && this.getAttributes().equals(castOther.getAttributes()) ) )
 && ( (this.getCurval()==castOther.getCurval()) || ( this.getCurval()!=null && castOther.getCurval()!=null && this.getCurval().equals(castOther.getCurval()) ) )
 && ( (this.getLstval()==castOther.getLstval()) || ( this.getLstval()!=null && castOther.getLstval()!=null && this.getLstval().equals(castOther.getLstval()) ) )
 && ( (this.getDefval()==castOther.getDefval()) || ( this.getDefval()!=null && castOther.getDefval()!=null && this.getDefval().equals(castOther.getDefval()) ) )
 && ( (this.getMinval()==castOther.getMinval()) || ( this.getMinval()!=null && castOther.getMinval()!=null && this.getMinval().equals(castOther.getMinval()) ) )
 && ( (this.getMaxval()==castOther.getMaxval()) || ( this.getMaxval()!=null && castOther.getMaxval()!=null && this.getMaxval().equals(castOther.getMaxval()) ) )
 && ( (this.getSpare1()==castOther.getSpare1()) || ( this.getSpare1()!=null && castOther.getSpare1()!=null && this.getSpare1().equals(castOther.getSpare1()) ) )
 && ( (this.getSpare2()==castOther.getSpare2()) || ( this.getSpare2()!=null && castOther.getSpare2()!=null && this.getSpare2().equals(castOther.getSpare2()) ) )
 && ( (this.getSpare3()==castOther.getSpare3()) || ( this.getSpare3()!=null && castOther.getSpare3()!=null && this.getSpare3().equals(castOther.getSpare3()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getScope() == null ? 0 : this.getScope().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getDescrip() == null ? 0 : this.getDescrip().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + ( getDatatype() == null ? 0 : this.getDatatype().hashCode() );
         result = 37 * result + ( getAttributes() == null ? 0 : this.getAttributes().hashCode() );
         result = 37 * result + ( getCurval() == null ? 0 : this.getCurval().hashCode() );
         result = 37 * result + ( getLstval() == null ? 0 : this.getLstval().hashCode() );
         result = 37 * result + ( getDefval() == null ? 0 : this.getDefval().hashCode() );
         result = 37 * result + ( getMinval() == null ? 0 : this.getMinval().hashCode() );
         result = 37 * result + ( getMaxval() == null ? 0 : this.getMaxval().hashCode() );
         result = 37 * result + ( getSpare1() == null ? 0 : this.getSpare1().hashCode() );
         result = 37 * result + ( getSpare2() == null ? 0 : this.getSpare2().hashCode() );
         result = 37 * result + ( getSpare3() == null ? 0 : this.getSpare3().hashCode() );
         return result;
   }   


}


