package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Rolling.connectionsId generated by hbm2java
 */
public class Rolling.connectionsId  implements java.io.Serializable {


     private BigDecimal sourceRdbid;
     private BigDecimal destRdbid;
     private BigDecimal attributes;
     private String serviceName;
     private BigDecimal connHandle;
     private Serializable connectTime;
     private Serializable sendTime;
     private Serializable disconnectTime;
     private Serializable updateTime;
     private BigDecimal sourcePid;
     private BigDecimal destPid;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private String spare3;

    public Rolling.connectionsId() {
    }

    public Rolling.connectionsId(BigDecimal sourceRdbid, BigDecimal destRdbid, BigDecimal attributes, String serviceName, BigDecimal connHandle, Serializable connectTime, Serializable sendTime, Serializable disconnectTime, Serializable updateTime, BigDecimal sourcePid, BigDecimal destPid, BigDecimal spare1, BigDecimal spare2, String spare3) {
       this.sourceRdbid = sourceRdbid;
       this.destRdbid = destRdbid;
       this.attributes = attributes;
       this.serviceName = serviceName;
       this.connHandle = connHandle;
       this.connectTime = connectTime;
       this.sendTime = sendTime;
       this.disconnectTime = disconnectTime;
       this.updateTime = updateTime;
       this.sourcePid = sourcePid;
       this.destPid = destPid;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.spare3 = spare3;
    }
   
    public BigDecimal getSourceRdbid() {
        return this.sourceRdbid;
    }
    
    public void setSourceRdbid(BigDecimal sourceRdbid) {
        this.sourceRdbid = sourceRdbid;
    }
    public BigDecimal getDestRdbid() {
        return this.destRdbid;
    }
    
    public void setDestRdbid(BigDecimal destRdbid) {
        this.destRdbid = destRdbid;
    }
    public BigDecimal getAttributes() {
        return this.attributes;
    }
    
    public void setAttributes(BigDecimal attributes) {
        this.attributes = attributes;
    }
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }
    public BigDecimal getConnHandle() {
        return this.connHandle;
    }
    
    public void setConnHandle(BigDecimal connHandle) {
        this.connHandle = connHandle;
    }
    public Serializable getConnectTime() {
        return this.connectTime;
    }
    
    public void setConnectTime(Serializable connectTime) {
        this.connectTime = connectTime;
    }
    public Serializable getSendTime() {
        return this.sendTime;
    }
    
    public void setSendTime(Serializable sendTime) {
        this.sendTime = sendTime;
    }
    public Serializable getDisconnectTime() {
        return this.disconnectTime;
    }
    
    public void setDisconnectTime(Serializable disconnectTime) {
        this.disconnectTime = disconnectTime;
    }
    public Serializable getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Serializable updateTime) {
        this.updateTime = updateTime;
    }
    public BigDecimal getSourcePid() {
        return this.sourcePid;
    }
    
    public void setSourcePid(BigDecimal sourcePid) {
        this.sourcePid = sourcePid;
    }
    public BigDecimal getDestPid() {
        return this.destPid;
    }
    
    public void setDestPid(BigDecimal destPid) {
        this.destPid = destPid;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public String getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(String spare3) {
        this.spare3 = spare3;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Rolling.connectionsId) ) return false;
		 Rolling.connectionsId castOther = ( Rolling.connectionsId ) other; 
         
		 return ( (this.getSourceRdbid()==castOther.getSourceRdbid()) || ( this.getSourceRdbid()!=null && castOther.getSourceRdbid()!=null && this.getSourceRdbid().equals(castOther.getSourceRdbid()) ) )
 && ( (this.getDestRdbid()==castOther.getDestRdbid()) || ( this.getDestRdbid()!=null && castOther.getDestRdbid()!=null && this.getDestRdbid().equals(castOther.getDestRdbid()) ) )
 && ( (this.getAttributes()==castOther.getAttributes()) || ( this.getAttributes()!=null && castOther.getAttributes()!=null && this.getAttributes().equals(castOther.getAttributes()) ) )
 && ( (this.getServiceName()==castOther.getServiceName()) || ( this.getServiceName()!=null && castOther.getServiceName()!=null && this.getServiceName().equals(castOther.getServiceName()) ) )
 && ( (this.getConnHandle()==castOther.getConnHandle()) || ( this.getConnHandle()!=null && castOther.getConnHandle()!=null && this.getConnHandle().equals(castOther.getConnHandle()) ) )
 && ( (this.getConnectTime()==castOther.getConnectTime()) || ( this.getConnectTime()!=null && castOther.getConnectTime()!=null && this.getConnectTime().equals(castOther.getConnectTime()) ) )
 && ( (this.getSendTime()==castOther.getSendTime()) || ( this.getSendTime()!=null && castOther.getSendTime()!=null && this.getSendTime().equals(castOther.getSendTime()) ) )
 && ( (this.getDisconnectTime()==castOther.getDisconnectTime()) || ( this.getDisconnectTime()!=null && castOther.getDisconnectTime()!=null && this.getDisconnectTime().equals(castOther.getDisconnectTime()) ) )
 && ( (this.getUpdateTime()==castOther.getUpdateTime()) || ( this.getUpdateTime()!=null && castOther.getUpdateTime()!=null && this.getUpdateTime().equals(castOther.getUpdateTime()) ) )
 && ( (this.getSourcePid()==castOther.getSourcePid()) || ( this.getSourcePid()!=null && castOther.getSourcePid()!=null && this.getSourcePid().equals(castOther.getSourcePid()) ) )
 && ( (this.getDestPid()==castOther.getDestPid()) || ( this.getDestPid()!=null && castOther.getDestPid()!=null && this.getDestPid().equals(castOther.getDestPid()) ) )
 && ( (this.getSpare1()==castOther.getSpare1()) || ( this.getSpare1()!=null && castOther.getSpare1()!=null && this.getSpare1().equals(castOther.getSpare1()) ) )
 && ( (this.getSpare2()==castOther.getSpare2()) || ( this.getSpare2()!=null && castOther.getSpare2()!=null && this.getSpare2().equals(castOther.getSpare2()) ) )
 && ( (this.getSpare3()==castOther.getSpare3()) || ( this.getSpare3()!=null && castOther.getSpare3()!=null && this.getSpare3().equals(castOther.getSpare3()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSourceRdbid() == null ? 0 : this.getSourceRdbid().hashCode() );
         result = 37 * result + ( getDestRdbid() == null ? 0 : this.getDestRdbid().hashCode() );
         result = 37 * result + ( getAttributes() == null ? 0 : this.getAttributes().hashCode() );
         result = 37 * result + ( getServiceName() == null ? 0 : this.getServiceName().hashCode() );
         result = 37 * result + ( getConnHandle() == null ? 0 : this.getConnHandle().hashCode() );
         result = 37 * result + ( getConnectTime() == null ? 0 : this.getConnectTime().hashCode() );
         result = 37 * result + ( getSendTime() == null ? 0 : this.getSendTime().hashCode() );
         result = 37 * result + ( getDisconnectTime() == null ? 0 : this.getDisconnectTime().hashCode() );
         result = 37 * result + ( getUpdateTime() == null ? 0 : this.getUpdateTime().hashCode() );
         result = 37 * result + ( getSourcePid() == null ? 0 : this.getSourcePid().hashCode() );
         result = 37 * result + ( getDestPid() == null ? 0 : this.getDestPid().hashCode() );
         result = 37 * result + ( getSpare1() == null ? 0 : this.getSpare1().hashCode() );
         result = 37 * result + ( getSpare2() == null ? 0 : this.getSpare2().hashCode() );
         result = 37 * result + ( getSpare3() == null ? 0 : this.getSpare3().hashCode() );
         return result;
   }   


}


