package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Rolling.statusId generated by hbm2java
 */
public class Rolling.statusId  implements java.io.Serializable {


     private BigDecimal revision;
     private BigDecimal phase;
     private BigDecimal batchid;
     private BigDecimal status;
     private BigDecimal coordid;
     private BigDecimal oprimary;
     private BigDecimal fprimary;
     private BigDecimal pid;
     private BigDecimal instance;
     private BigDecimal dbtotal;
     private BigDecimal dbactive;
     private String location;
     private Serializable initTime;
     private Serializable buildTime;
     private Serializable startTime;
     private Serializable switchTime;
     private Serializable finishTime;
     private BigDecimal lastInstid;
     private BigDecimal lastBatchid;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private String spare3;

    public Rolling.statusId() {
    }

    public Rolling.statusId(BigDecimal revision, BigDecimal phase, BigDecimal batchid, BigDecimal status, BigDecimal coordid, BigDecimal oprimary, BigDecimal fprimary, BigDecimal pid, BigDecimal instance, BigDecimal dbtotal, BigDecimal dbactive, String location, Serializable initTime, Serializable buildTime, Serializable startTime, Serializable switchTime, Serializable finishTime, BigDecimal lastInstid, BigDecimal lastBatchid, BigDecimal spare1, BigDecimal spare2, String spare3) {
       this.revision = revision;
       this.phase = phase;
       this.batchid = batchid;
       this.status = status;
       this.coordid = coordid;
       this.oprimary = oprimary;
       this.fprimary = fprimary;
       this.pid = pid;
       this.instance = instance;
       this.dbtotal = dbtotal;
       this.dbactive = dbactive;
       this.location = location;
       this.initTime = initTime;
       this.buildTime = buildTime;
       this.startTime = startTime;
       this.switchTime = switchTime;
       this.finishTime = finishTime;
       this.lastInstid = lastInstid;
       this.lastBatchid = lastBatchid;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.spare3 = spare3;
    }
   
    public BigDecimal getRevision() {
        return this.revision;
    }
    
    public void setRevision(BigDecimal revision) {
        this.revision = revision;
    }
    public BigDecimal getPhase() {
        return this.phase;
    }
    
    public void setPhase(BigDecimal phase) {
        this.phase = phase;
    }
    public BigDecimal getBatchid() {
        return this.batchid;
    }
    
    public void setBatchid(BigDecimal batchid) {
        this.batchid = batchid;
    }
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }
    public BigDecimal getCoordid() {
        return this.coordid;
    }
    
    public void setCoordid(BigDecimal coordid) {
        this.coordid = coordid;
    }
    public BigDecimal getOprimary() {
        return this.oprimary;
    }
    
    public void setOprimary(BigDecimal oprimary) {
        this.oprimary = oprimary;
    }
    public BigDecimal getFprimary() {
        return this.fprimary;
    }
    
    public void setFprimary(BigDecimal fprimary) {
        this.fprimary = fprimary;
    }
    public BigDecimal getPid() {
        return this.pid;
    }
    
    public void setPid(BigDecimal pid) {
        this.pid = pid;
    }
    public BigDecimal getInstance() {
        return this.instance;
    }
    
    public void setInstance(BigDecimal instance) {
        this.instance = instance;
    }
    public BigDecimal getDbtotal() {
        return this.dbtotal;
    }
    
    public void setDbtotal(BigDecimal dbtotal) {
        this.dbtotal = dbtotal;
    }
    public BigDecimal getDbactive() {
        return this.dbactive;
    }
    
    public void setDbactive(BigDecimal dbactive) {
        this.dbactive = dbactive;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Serializable getInitTime() {
        return this.initTime;
    }
    
    public void setInitTime(Serializable initTime) {
        this.initTime = initTime;
    }
    public Serializable getBuildTime() {
        return this.buildTime;
    }
    
    public void setBuildTime(Serializable buildTime) {
        this.buildTime = buildTime;
    }
    public Serializable getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Serializable startTime) {
        this.startTime = startTime;
    }
    public Serializable getSwitchTime() {
        return this.switchTime;
    }
    
    public void setSwitchTime(Serializable switchTime) {
        this.switchTime = switchTime;
    }
    public Serializable getFinishTime() {
        return this.finishTime;
    }
    
    public void setFinishTime(Serializable finishTime) {
        this.finishTime = finishTime;
    }
    public BigDecimal getLastInstid() {
        return this.lastInstid;
    }
    
    public void setLastInstid(BigDecimal lastInstid) {
        this.lastInstid = lastInstid;
    }
    public BigDecimal getLastBatchid() {
        return this.lastBatchid;
    }
    
    public void setLastBatchid(BigDecimal lastBatchid) {
        this.lastBatchid = lastBatchid;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public String getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(String spare3) {
        this.spare3 = spare3;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Rolling.statusId) ) return false;
		 Rolling.statusId castOther = ( Rolling.statusId ) other; 
         
		 return ( (this.getRevision()==castOther.getRevision()) || ( this.getRevision()!=null && castOther.getRevision()!=null && this.getRevision().equals(castOther.getRevision()) ) )
 && ( (this.getPhase()==castOther.getPhase()) || ( this.getPhase()!=null && castOther.getPhase()!=null && this.getPhase().equals(castOther.getPhase()) ) )
 && ( (this.getBatchid()==castOther.getBatchid()) || ( this.getBatchid()!=null && castOther.getBatchid()!=null && this.getBatchid().equals(castOther.getBatchid()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getCoordid()==castOther.getCoordid()) || ( this.getCoordid()!=null && castOther.getCoordid()!=null && this.getCoordid().equals(castOther.getCoordid()) ) )
 && ( (this.getOprimary()==castOther.getOprimary()) || ( this.getOprimary()!=null && castOther.getOprimary()!=null && this.getOprimary().equals(castOther.getOprimary()) ) )
 && ( (this.getFprimary()==castOther.getFprimary()) || ( this.getFprimary()!=null && castOther.getFprimary()!=null && this.getFprimary().equals(castOther.getFprimary()) ) )
 && ( (this.getPid()==castOther.getPid()) || ( this.getPid()!=null && castOther.getPid()!=null && this.getPid().equals(castOther.getPid()) ) )
 && ( (this.getInstance()==castOther.getInstance()) || ( this.getInstance()!=null && castOther.getInstance()!=null && this.getInstance().equals(castOther.getInstance()) ) )
 && ( (this.getDbtotal()==castOther.getDbtotal()) || ( this.getDbtotal()!=null && castOther.getDbtotal()!=null && this.getDbtotal().equals(castOther.getDbtotal()) ) )
 && ( (this.getDbactive()==castOther.getDbactive()) || ( this.getDbactive()!=null && castOther.getDbactive()!=null && this.getDbactive().equals(castOther.getDbactive()) ) )
 && ( (this.getLocation()==castOther.getLocation()) || ( this.getLocation()!=null && castOther.getLocation()!=null && this.getLocation().equals(castOther.getLocation()) ) )
 && ( (this.getInitTime()==castOther.getInitTime()) || ( this.getInitTime()!=null && castOther.getInitTime()!=null && this.getInitTime().equals(castOther.getInitTime()) ) )
 && ( (this.getBuildTime()==castOther.getBuildTime()) || ( this.getBuildTime()!=null && castOther.getBuildTime()!=null && this.getBuildTime().equals(castOther.getBuildTime()) ) )
 && ( (this.getStartTime()==castOther.getStartTime()) || ( this.getStartTime()!=null && castOther.getStartTime()!=null && this.getStartTime().equals(castOther.getStartTime()) ) )
 && ( (this.getSwitchTime()==castOther.getSwitchTime()) || ( this.getSwitchTime()!=null && castOther.getSwitchTime()!=null && this.getSwitchTime().equals(castOther.getSwitchTime()) ) )
 && ( (this.getFinishTime()==castOther.getFinishTime()) || ( this.getFinishTime()!=null && castOther.getFinishTime()!=null && this.getFinishTime().equals(castOther.getFinishTime()) ) )
 && ( (this.getLastInstid()==castOther.getLastInstid()) || ( this.getLastInstid()!=null && castOther.getLastInstid()!=null && this.getLastInstid().equals(castOther.getLastInstid()) ) )
 && ( (this.getLastBatchid()==castOther.getLastBatchid()) || ( this.getLastBatchid()!=null && castOther.getLastBatchid()!=null && this.getLastBatchid().equals(castOther.getLastBatchid()) ) )
 && ( (this.getSpare1()==castOther.getSpare1()) || ( this.getSpare1()!=null && castOther.getSpare1()!=null && this.getSpare1().equals(castOther.getSpare1()) ) )
 && ( (this.getSpare2()==castOther.getSpare2()) || ( this.getSpare2()!=null && castOther.getSpare2()!=null && this.getSpare2().equals(castOther.getSpare2()) ) )
 && ( (this.getSpare3()==castOther.getSpare3()) || ( this.getSpare3()!=null && castOther.getSpare3()!=null && this.getSpare3().equals(castOther.getSpare3()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRevision() == null ? 0 : this.getRevision().hashCode() );
         result = 37 * result + ( getPhase() == null ? 0 : this.getPhase().hashCode() );
         result = 37 * result + ( getBatchid() == null ? 0 : this.getBatchid().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getCoordid() == null ? 0 : this.getCoordid().hashCode() );
         result = 37 * result + ( getOprimary() == null ? 0 : this.getOprimary().hashCode() );
         result = 37 * result + ( getFprimary() == null ? 0 : this.getFprimary().hashCode() );
         result = 37 * result + ( getPid() == null ? 0 : this.getPid().hashCode() );
         result = 37 * result + ( getInstance() == null ? 0 : this.getInstance().hashCode() );
         result = 37 * result + ( getDbtotal() == null ? 0 : this.getDbtotal().hashCode() );
         result = 37 * result + ( getDbactive() == null ? 0 : this.getDbactive().hashCode() );
         result = 37 * result + ( getLocation() == null ? 0 : this.getLocation().hashCode() );
         result = 37 * result + ( getInitTime() == null ? 0 : this.getInitTime().hashCode() );
         result = 37 * result + ( getBuildTime() == null ? 0 : this.getBuildTime().hashCode() );
         result = 37 * result + ( getStartTime() == null ? 0 : this.getStartTime().hashCode() );
         result = 37 * result + ( getSwitchTime() == null ? 0 : this.getSwitchTime().hashCode() );
         result = 37 * result + ( getFinishTime() == null ? 0 : this.getFinishTime().hashCode() );
         result = 37 * result + ( getLastInstid() == null ? 0 : this.getLastInstid().hashCode() );
         result = 37 * result + ( getLastBatchid() == null ? 0 : this.getLastBatchid().hashCode() );
         result = 37 * result + ( getSpare1() == null ? 0 : this.getSpare1().hashCode() );
         result = 37 * result + ( getSpare2() == null ? 0 : this.getSpare2().hashCode() );
         result = 37 * result + ( getSpare3() == null ? 0 : this.getSpare3().hashCode() );
         return result;
   }   


}


