package com.abctreinamentos;
// Generated 16/03/2021 08:37:56 by Hibernate Tools 4.3.1


import com.abctreinamentos.Rolling.connectionsId;

/**
 * Rolling.connections generated by hbm2java
 */
public class Rolling.connections  implements java.io.Serializable {


     private Rolling.connectionsId id;

    public Rolling.connections() {
    }

    public Rolling.connections(Rolling.connectionsId id) {
       this.id = id;
    }
   
    public Rolling.connectionsId getId() {
        return this.id;
    }
    
    public void setId(Rolling.connectionsId id) {
        this.id = id;
    }




}


